---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-cop-phase2-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-cop-phase2
    namespace: cop-phase2
  - kind: ServiceAccount
    name: tsb-cop-phase2
    namespace: cop-phase2
  - kind: ServiceAccount
    name: cop-phase2-sink-connector
    namespace: cop-phase2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-cop-phase2
  namespace: cop-phase2