---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cop-phase2-view-role
  namespace: kube-system
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cop-phase2-view-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cop-phase2-view-role
subjects:
  - kind: Group
    name: cop-phase2-read-only
  - kind: Group
    name: cop-phase2-view-kube-system
