---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cop-phase2-admin-role
  namespace: cop-phase2
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cop-phase2-admin-binding
  namespace: cop-phase2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cop-phase2-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-cop-phase2
  - kind: Group
    name: cop-phase2-admin
  - kind: ServiceAccount
    name: jenkins-terraform
    namespace: jenkins