---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-api-gw-ob
  namespace: api-gw-ob
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-ob-admin-role
  labels:
    role: jenkins-agent
    component: ob