---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-cb
  namespace: cb-{{ ENV }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-cb
  labels:
    role: jenkins-agent
    component: cb