---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: vault-sco-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-sco
  namespace: sco
- kind: ServiceAccount
  name: tsb-sco
  namespace: sco
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: vault-sco
    namespace: sco