apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sco-cluster-binding-service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-service-discovery
subjects:
  - kind: ServiceAccount
    name: tsb-sco
    namespace: sco
