---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sco-admin-role
  namespace: sco
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sco-admin-binding
  namespace: sco
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sco-admin-role
subjects:
- kind: ServiceAccount
  name: tsb-sco
- kind: Group
  name: sco-admin
