---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: operator-network-policy
  namespace: scylla-operator
spec:
  types:
    - Ingress
    - Egress
  egress:    
    - action: Allow
      destination:
        nets:
          - "{{ VPC_CIDR }}"
  ingress:    
    - action: Allow
      source:
        nets:
          - "{{ VPC_CIDR }}"