apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-admission-webhook-access
  namespace: prometheus
spec:
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app == 'prometheus-operator'
      destination:
        ports:
          - 8443