{
 "title": "Shared Infrastructure - Prod Part 2",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "CD EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-node.*\"} == 1)/10*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "COB EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-sco-node.*\"} == 1)/3*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-sco-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "COP EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-cop-phase2-node.*\"} == 1)/3*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-cop-phase2-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "SCA EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-sca-node.*\"} == 1)/3*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-sca-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "SCO EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-scofl-node.*\"} == 1)/3*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-scofl-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "OBS EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-obs-node.*\"} == 1)/2*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-obs-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "ODS EKS Node Pool",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-highcompute-node.*\"} == 1)/20*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"prod-eks-highcompute-node.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  }
 ]
}