---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-infra-test-cm
  namespace: prometheus
data:
  aws-infra-test.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 953,
      "iteration": 1680694514528,
      "links": [],
      "panels": [
        {
          "datasource": null,
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "mappings": [
                {
                  "from": "3",
                  "id": 1,
                  "text": "OK",
                  "to": "6",
                  "type": 2,
                  "value": "3"
                },
                {
                  "from": "1",
                  "id": 2,
                  "text": "Under Capacity",
                  "to": "2",
                  "type": 2,
                  "value": ""
                },
                {
                  "from": "",
                  "id": 3,
                  "text": "NA",
                  "to": "",
                  "type": 1,
                  "value": "0"
                }
              ],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "red",
                    "value": null
                  },
                  {
                    "color": "#EAB839",
                    "value": 2
                  },
                  {
                    "color": "green",
                    "value": 3
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 7,
            "w": 6,
            "x": 0,
            "y": 0
          },
          "id": 75,
          "options": {
            "colorMode": "value",
            "graphMode": "none",
            "justifyMode": "auto",
            "orientation": "auto",
            "reduceOptions": {
              "calcs": [
                "lastNotNull"
              ],
              "fields": "",
              "values": false
            },
            "text": {},
            "textMode": "auto"
          },
          "pluginVersion": "7.5.15",
          "targets": [
            {
              "exemplar": true,
              "expr": "count(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"LeaderCount\"})",
              "interval": "",
              "legendFormat": "EKS Pool Status",
              "refId": "A"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "MSK Cluster status",
          "type": "stat"
        },
        {
          "collapsed": false,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 7
          },
          "id": 27,
          "panels": [],
          "title": "Row title",
          "type": "row"
        }
      ],
      "refresh": "1m",
      "schemaVersion": 27,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "allValue": null,
            "current": {
              "selected": false,
              "text": "node_systemd_unit_state{availabilityzone=\"eu-west-2a\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-3\",instanceid=\"i-0bf2a03325023dad6\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.70.193\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}",
              "value": "node_systemd_unit_state{availabilityzone=\"eu-west-2a\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-3\",instanceid=\"i-0bf2a03325023dad6\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.70.193\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}"
            },
            "datasource": null,
            "definition": "node_systemd_unit_state{instance=~\"shared-nonprod-scylla.*\",name=\"scylla-server.service\",state=\"active\",status=\"running\"}",
            "description": "Get number of scylla nodes",
            "error": null,
            "hide": 0,
            "includeAll": false,
            "label": null,
            "multi": false,
            "name": "scylla_count",
            "options": [
              {
                "selected": false,
                "text": "node_systemd_unit_state{availabilityzone=\"eu-west-2a\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-3\",instanceid=\"i-0bf2a03325023dad6\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.70.193\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}",
                "value": "node_systemd_unit_state{availabilityzone=\"eu-west-2a\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-3\",instanceid=\"i-0bf2a03325023dad6\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.70.193\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}"
              },
              {
                "selected": true,
                "text": "node_systemd_unit_state{availabilityzone=\"eu-west-2b\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-1\",instanceid=\"i-0cb53d0785a679c3a\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.72.127\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}",
                "value": "node_systemd_unit_state{availabilityzone=\"eu-west-2b\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-1\",instanceid=\"i-0cb53d0785a679c3a\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.72.127\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}"
              },
              {
                "selected": false,
                "text": "node_systemd_unit_state{availabilityzone=\"eu-west-2c\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-2\",instanceid=\"i-0931b30202adaebf5\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.74.240\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}",
                "value": "node_systemd_unit_state{availabilityzone=\"eu-west-2c\",environment=\"nonprod\",instance=\"shared-nonprod-scylla-db-2\",instanceid=\"i-0931b30202adaebf5\",instancetype=\"t3a.2xlarge\",job=\"ec2-discover-node-exporter\",name=\"scylla-server.service\",privateip=\"10.161.74.240\",prometheus=\"prometheus/prometheus-kube-prometheus-prometheus\",prometheus_replica=\"prometheus-prometheus-kube-prometheus-prometheus-0\",state=\"active\",status=\"running\",terraform=\"true\"}"
              }
            ],
            "query": {
              "query": "node_systemd_unit_state{instance=~\"shared-nonprod-scylla.*\",name=\"scylla-server.service\",state=\"active\",status=\"running\"}",
              "refId": "StandardVariableQuery"
            },
            "refresh": 0,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tags": [],
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "AWS Infra Real",
      "uid": "pwdinfa",
      "version": 2
    }  