{
 "title": "Shared Infrastructure - Prod Part 1",
 "description": "Main Infrastructure - ScyllaDB, Kafka, Consul, Consul-Vault & Vault",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Shared Scylla",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-scylla.*\"} == 1))/6*100",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-scylla.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "ODS Scylla",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-scylla.*\"} == 1)/6*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-scylla.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Kafka Brokers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-worker-.*\"} == 1)/6*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-worker-.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Kafka Controller",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-controller-.*\"} == 1)/1*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-controller-.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Kafka Zookeeper",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-service-.*\"} == 1)/3*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"shared-prod-hdf-service-.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Consul",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-consul.*\"} == 1)/6*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-consul.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Consul Vault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-vault-consul.*\"} == 1)/6*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-vault-consul.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Vault",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-vault.*\"} == 1)/6*100)",
     "legendFormat": "Uptime"
    },
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\",instance=~\"core-prod-vault.*\"} == 1)",
     "legendFormat": "Number of Nodes"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://consul.prod.aws.uk.tsb\", job=\"blackbox\"}",
     "legendFormat": "Consul"
    },
    {
     "expr": "probe_http_status_code{instance=\"https://vault.prod.aws.uk.tsb\", job=\"blackbox\"}",
     "legendFormat": "Vault"
    }
   ]
  }
 ]
}