---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bs-ca-chain-configmap
  namespace: prometheus
data:
  bs-ca-chain.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFSzCCAzOgAwIBAgIQalf3vE65561JekrUP4LLBzANBgkqhkiG9w0BAQsFADA4
    MRYwFAYDVQQKEw1CYW5jIFNhYmFkZWxsMR4wHAYDVQQDExVCYW5jIFNhYmFkZWxs
    IENBIFJhaXowHhcNMTUwOTI0MDkzMTQ2WhcNMzUwOTI0MDk0MTM4WjA4MRYwFAYD
    VQQKEw1CYW5jIFNhYmFkZWxsMR4wHAYDVQQDExVCYW5jIFNhYmFkZWxsIENBIFJh
    aXowggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDQRJuXWQAh7Ge3KKi5
    mOl62GqbBNT/3BGzSfFP7Xatc1n2Nz/enZ9zLbIXjlk2+/ISnvo0czbJHlmYVF+D
    neNTWBul5qxhg1ccBhWp7uDrmOKckbSQ2lXO/2y1XrrsHTAk8Cewzvg41K6uzPVC
    SIv3k5sgZZC9MdSTcZtZAY4NqynFBtgUoOYSJDFHL8tXINf9UvpyDrAvhU5JBNur
    Z8aZMPtFx/4TDJ4xqNsBi4u3k30prMb4bCMyCFtiWV9/tArALN6i7j4PBhToJY1t
    uRx9EGBmXf9W2lQ0g9vC05WhTEedu7CmlINI9f0BSqdu70ROAd2Hvw0bN9BT9Hu6
    6CL8F/PJkO4ifzyxtEQPZqn5hUHBsW81lmygCYWowcoL0Ch8gKkxlYK+hL/2qIT2
    ewK5cplKNIV+BmKtC+Z04dXQWNmGptPjoe7Qft/kdhjeESg03lPK7L9X4Zci+Z+V
    G4Wp+K6DyWTXKg7RaV9/nPOBAtsBz3f2r8ennsy999SxJlOJ4qGuIrWN/ZiOQ8nk
    zWIRN4odm1pqoWO7YnYV2nRwayfbhD2X6ismIlp7/N/VbfTxak2Z4ffsvJqa/fWF
    3ShVu0LqJqQZq8rEDdf60GCrA6mRplf0+Cj93zUV9iOaoV31hd9s6fNC0MCGP4b4
    u1Y/DPVo03wAzcN5SBJ8KzLzvQIDAQABo1EwTzALBgNVHQ8EBAMCAYYwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQUz9HC6bRsRBOA7i0PleBzzth3MqUwEAYJKwYB
    BAGCNxUBBAMCAQAwDQYJKoZIhvcNAQELBQADggIBAMKTr85hyWLDi0e9lutKQCNd
    P9rCf7Pq2xnZsKWgaxCNkiMCynjtplCB+8zDALF0QPY4JRXETsgTwzd7BFocsYIf
    4/E8ynQAOiadCQxU8PCBOFkwJTfmp7j2x6jBo+Cc6iKd0dKzoPJBCQkDyzIBVki6
    qVhnAWi5Rul0yP5nZYoFxZLltyGiV2MgtEn9JxtLIy6LND0ZrpApYvFwILVXNwrM
    z8hlpjdgssxpgVn/9bnoZ1cnQHdyBG3F6GFc3wHo5He9YWRVk4PT0Lx7LlQoPSpC
    74Ho8DZNC0Tmm9Fj8HraKLkQWA8RRfSsm1WDpv4fXIYDoSvWB/+QpdWY0zO8F1J8
    rpYfl/v+mLbT4baV3Bq2INXF/vz+M70nUGAazxbc0FAa7jFMnJGifJveu2kNhGnR
    tI5UO3zGEVHie8UVn4MK4dY/oLmGgdcItbRZxh94nskMDyMhJcQk+w5AM48a30lc
    JxJaolLC0U4oFW81iC43qpRrPm06dFava/ZQzbg2vVQJ/BLTUAfK2BHHRRhERXW0
    fOCFwuDC0R2XFK9sjWYZVb86ykreukvllhzOyb0CicONpQFLsW8JBW2rse/DJgU0
    YXVOEIxE+kFs9CpP26F+3IhfzFP4dA8MP3xqHKOEapVAwmphrjyIFb4ZY6XX1IEE
    G8sCKsq4M5qtZ1WH+cu0
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIF9TCCA92gAwIBAgITVAAAACr9SmVcyA6PBwAAAAAAKjANBgkqhkiG9w0BAQsF
    ADA4MRYwFAYDVQQKEw1CYW5jIFNhYmFkZWxsMR4wHAYDVQQDExVCYW5jIFNhYmFk
    ZWxsIENBIFJhaXowHhcNMTkxMDIyMTM0NDAzWhcNMjcxMDIyMTM1NDAzWjBAMRYw
    FAYDVQQKEw1CYW5jIFNhYmFkZWxsMSYwJAYDVQQDEx1CYW5jIFNhYmFkZWxsIENB
    IFNlcnZpZG9yZXMgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKMo
    Z8uA66DjU02KUxfnJcLVl8C1mmzXNgfnEHZPEE4TNTCKBnoISzLtgWY+AqZwhGmR
    hT9HLp0oRK2fpnKruWpgmHmHSvPKBTQ2DLgaen4a4DpbqdhzlWuJlUvd06Lxc65d
    aLkB3UK31Di8qegDqslg7NB0Tu0R3TDxHiGhNwVwxuEdtoeEnKRMvN5LYOWwqbE7
    Ua+rAYkFe+Th6nEhsbc0E2N5531s9ozAcOeehdeRfdAdGst752Ym/myhS6nFV+gM
    gosOPMZnSZoaICMjuSFkX2S5MegAh1YIcrqhi9dRtTYjbuGZomYmehDCemkH8Lm6
    CyMD6ZfdV2C4v6Z9xhMCAwEAAaOCAe4wggHqMBIGCSsGAQQBgjcVAQQFAgMCAAIw
    IwYJKwYBBAGCNxUCBBYEFM31ExrZbykTSihIt3rdWo6DF+N6MB0GA1UdDgQWBBTp
    bpFhG4bFC7QbVNJqvjvl2S9ZYDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
    BgNVHQ8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBTP0cLp
    tGxEE4DuLQ+V4HPO2HcypTCBjAYDVR0fBIGEMIGBMH+gfaB7hjhodHRwOi8vY3Js
    LmFkZ2JzLmNvbS9DUkwvQmFuYyUyMFNhYmFkZWxsJTIwQ0ElMjBSYWl6LmNybIY/
    aHR0cDovL3d3dy5iYW5jc2FiYWRlbGwuY29tL0NSTC9CYW5jJTIwU2FiYWRlbGwl
    MjBDQSUyMFJhaXouY3JsMIGjBggrBgEFBQcBAQSBljCBkzBEBggrBgEFBQcwAoY4
    aHR0cDovL2NybC5hZGdicy5jb20vQ1JML0JhbmMlMjBTYWJhZGVsbCUyMENBJTIw
    UmFpei5jcnQwSwYIKwYBBQUHMAKGP2h0dHA6Ly93d3cuYmFuY3NhYmFkZWxsLmNv
    bS9DUkwvQmFuYyUyMFNhYmFkZWxsJTIwQ0ElMjBSYWl6LmNydDANBgkqhkiG9w0B
    AQsFAAOCAgEAwwBLOEWm94wOmIIrBIPAZfvx3Ai8fgyIDgtYYCH+y4zUgZaFN3Gi
    Tm6qOuOEzZks3NXcUT4awA5veq9yG75yADg8XDzggnQj3Q8eS8vkfqyUbrENFHBA
    aA6/nYWB1GIVOBf+yjhDy2gbiEJq6JUXA19Ilyu80uLpRcGgiTyeaNrHn/n1xjlM
    dLG0hQuxIn6WLfux8uo7Bbnj5qpGOrhuYg9klR2Q7188lSYbrFrxEE6+izI6aLNW
    morCiM9/Cc6VLzQq6qA4zfimEaTDboKY1hC6yeDNtGupEmTK17naJUVWUdG3GwOG
    Sqv6ogQlbFw6dixXTk/4MtHm6Un1Z53VADRQFt7Z1/9TqZpnJqzLNPV1Ms1I2DrK
    NEDepnYEyMbiqwzMc8W9FAUDU4dNdekcmEJQ5vcHcmZYF/PDj2bHmGaSSfUWHqZq
    8Eh8tpzAhojZjRaN13cxNeMcBXDoGe3odpftMWiNHHrMqps+JIjlomRgjlRhB3Cn
    Z+iJj8VBr8nrzaSOoCLG5UzM2bXw90cIh+3I/RkJInxL+Q2bmtHtKklIVtTv621F
    dEiYp6eLYgTcjtpiweyYmqYOtbcLcheuNqt6cGl/9d1nK1GW08PiIoba4deXmKz5
    Szbs2LMxadiq92ab5cY/2M638ZyTUbE7ALvEgLOVwTjSp9xtzkEhY3U=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIGTTCCBDWgAwIBAgIUcaGM1YWYVfTi3ERZgyfI7BnjR3QwDQYJKoZIhvcNAQEL
    BQAwgaExCzAJBgNVBAYTAkdCMRIwEAYDVQQIDAlFZGluYnVyZ2gxFjAUBgNVBAoM
    DVRTQiBCYW5rIFBsYy4xDTALBgNVBAsMBENJU08xEjAQBgNVBAcMCUVkaW5idXJn
    aDEgMB4GA1UEAwwXVFNCIFRFU1QgUEtJIFJvb3QgQ0EgUjExITAfBgkqhkiG9w0B
    CQEWEnRzYl9jaXNvQHRzYi5jby51azAeFw0yMTAxMjAxMzU2MTdaFw00MTAxMTUx
    MzU2MTdaMIGhMQswCQYDVQQGEwJHQjESMBAGA1UECAwJRWRpbmJ1cmdoMRYwFAYD
    VQQKDA1UU0IgQmFuayBQbGMuMQ0wCwYDVQQLDARDSVNPMRIwEAYDVQQHDAlFZGlu
    YnVyZ2gxIDAeBgNVBAMMF1RTQiBURVNUIFBLSSBSb290IENBIFIxMSEwHwYJKoZI
    hvcNAQkBFhJ0c2JfY2lzb0B0c2IuY28udWswggIiMA0GCSqGSIb3DQEBAQUAA4IC
    DwAwggIKAoICAQCyguIVpCIZ6SljgF6NrgmIPduUwfRY9d0N/x0nxMxSuzRBxfF7
    Hvh8rjsch1sa7ysRP5oow+5dAZ8x+AxhTENJgfdeU8HTQmwXr8tkBsEIyosy7bVW
    WCDCQCYvg0AMKdE7drkDf2IVn79RpoIVkM9nHvr3vSlvwQMTgZyHziNtGpWDk/m1
    fggdyB+zBr+nOb6T8Nlnb7bZB9dhNZxIAHMBY0sKjIwP9JdqYQHbmHg/GTh4jhoz
    7xu2Lwgh3hKrUVeTBRVsPpq/4EiX4Urcw0ffEu4bpXVRUTESpcM/0farxFyPLHvN
    2kO0f+08Eaen3giVkD18VTYMxHgvYU2FbdzbcnpRaRH62Uv6o2R4BtU6M+Jz17HD
    v6XmjOBuO4ID0BI86k4Oj1/8sDxusvgooF1q76fppFd7Zx+ZfWaUdyAkU7gyWljh
    8aM8BoAnR9sJ/U/ponY3Goe/rduKMhVPscy9EoKq7JNq4YHTTxJHToFpm2s8DJfX
    wcq6vdBhONNv4x2j+hGLIr4jXFIcvBXwDeW2jS1bJR+IasyrFdBUvRstHu6gm90J
    VAEnu0Su9zyhFSHtoXMtupNhjTbGpuDMpn2yJS63Oa0anczM21fv0R/HOnAqA4N3
    EiRTp7uZ2GlGl8RkbQ/ozi3gG4kOmGsHaAeqLLT0+bfWNMJCOhYri6hfXQIDAQAB
    o3sweTAdBgNVHQ4EFgQUXDrLino4hTRHK2QMR4ATsBbeFe0wHwYDVR0jBBgwFoAU
    XDrLino4hTRHK2QMR4ATsBbeFe0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
    BAMCAYYwFgYDVR0gBA8wDTALBgkrBgEEAYO7IAIwDQYJKoZIhvcNAQELBQADggIB
    ACEnOViuYT8gHXZw6EHD7gbvOtK1lQ6KzwkUs594Js6D7IwmNKPxjbAyrjUVi83K
    JuqLbO7x4Buu9oj10H245aStS8pPjtMHUREPiFIwfNPW9arbqmAaz5nauh6tmYJj
    Lktfb4YGxCPUmQd4HijOgJZ60fVec5aVGq+8M+BhJvfZMhD0gQjXIdV5Z5avJ7Q4
    L+fQJyf4RzDBelXHFekQNdk1+5YOmu52ie2ztubM5DXEEKZ++NP6YciBVomUda13
    k/olEqZVKvYF6gqzWOv7iRPab/3sc+kycsANTkxJZeYhJfgMUOTKJ7PWyGPyZfqZ
    opA1ZGLsBQkUfhNl44Tope04WF7gpbU8mOSVDPaOamHSX4eJNESUzdOgDkmj1ibE
    w8PgsrvltSYHJyahDaEYnQNdRGhsbjG8u014B89cfpa1aFfB20/YTaxb3cfaw7s+
    J+uyEjsZZ4jAPV7qu5D8edbVPMRSv0t1n9ODbSH8hz8I7lXhK+kJmThdc34m5hIT
    D+Yax//EY/xxQOZOW2GH5/CbvTwTis67PvPumLr0CoXXpRC0eP7JqTWHVQBuUjom
    ZX9yYDpa/WTJL5p+oS1sd8NciABH3kvA431zILyyzE3xfa9VOCaQQMrZtThbpWN3
    bFnk6hwiugdOtrqUly67XPjM8tNFQIcm/o7kk3yZrKtI
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFwTCCA6mgAwIBAgIULMiqq0ASsEAqmz27JmL6S32sUhowDQYJKoZIhvcNAQEL
    BQAwZDELMAkGA1UEBhMCR0IxFTATBgNVBAoMDFRTQiBCYW5rIHBsYzENMAsGA1UE
    CwwEQ0lTTzESMBAGA1UEBwwJRWRpbmJ1cmdoMRswGQYDVQQDDBJUU0IgUEtJIFJv
    b3QgQ0EgUjEwHhcNMjEwMjIzMTQxNjQzWhcNNDEwMjE4MTQxNjQzWjBkMQswCQYD
    VQQGEwJHQjEVMBMGA1UECgwMVFNCIEJhbmsgcGxjMQ0wCwYDVQQLDARDSVNPMRIw
    EAYDVQQHDAlFZGluYnVyZ2gxGzAZBgNVBAMMElRTQiBQS0kgUm9vdCBDQSBSMTCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL3yCV3vDSO68DA0A/dhr0Uz
    v1uvPI3uEpqQfo6VmlW7UDX6u6JBoIBc7URCTLvCoBMktmZR2qNXqadkcyJ9utez
    61prRHjl4Fn4GsoiMyL0LoEiDKo7FHW3ZNjpdn5dXZ54NaVCaIvLE1S2jnNOKLpk
    SfUEcASKYl1QwvBPQT11XICr77qblAZKrSyoWC5sW/AiFUuZ4YzhMF8K4neNzgOE
    D7EiXYKr3MxFImqKq/H5OMYoIelAr4ttBvVGYUrieKnu7fIehhwkWTA3pLvP5ETV
    Xh3804rpdBhj377h4M+reouon01H7DAMa59LigKBmYbJCGlb2wSS/NgX3x1yZuE1
    78U+4Uoq8YnffZzdaobHIsuFscCW9IKywnmlSxQJMUqWdrIhVP6F5/vOufSFoh1t
    B3uXTZxe/MpkEq7Dpt5vzy8ukILpmO2s0Mi0Dyu5zgGICoElCA/xTExhXztF64WY
    L4nVwnEzvZnsVF7gDtFPEqeHOzKaISjDfOT61E+A/dtJ9rTRX9D+Z5Dna1G0sa97
    VsAEK7IoVw6YLz6c3vNECfyRrmyyij1MUAOzTRLzPV+u1Zf9zcOdp0uovOywmwuh
    GiFd+/EfALTONTdOCYGHA6VS78RLtDw6AnnM5wA/8vf7J2MqCFlmNxEFXnZb/cOI
    Skuqt9B6cF6Q0sYydAGpAgMBAAGjazBpMB0GA1UdDgQWBBQiBjYohHEMWMlXd/Ca
    zMzS+9hYYDAfBgNVHSMEGDAWgBQiBjYohHEMWMlXd/CazMzS+9hYYDAPBgNVHRMB
    Af8EBTADAQH/MBYGA1UdIAQPMA0wCwYJKwYBBAGDuyABMA0GCSqGSIb3DQEBCwUA
    A4ICAQAUhD8TvcwxIhxp1ySPhfwspQmljanY6JwG0hEMCjLQMIiRvZWaGJDVWPDB
    HjubeYltl89n6LR0nexv9l+vmZ8iB5ffe9OdXWxWe5PHqCthO6Y9iBhCczuKwM61
    tKN1dH/NactxCz41xOal1WcYgloagZ5oRqfcJNjLGwFS/i/IalFdbaizUH4cPTJc
    oCAexuelMTPIC9cy07fGG50YtsKuwn/gTwEzDXn8zwEkjFxeE68uIGze29aMGTmx
    rNZFJiGCz6rP5BTWKULW8CWmSik86Ay7CKzaRvJQF6MQBjJAQXY5MwJJRAbwbHck
    1wJRy6zZhyNgoQSEFKil3fjfJ9V+nAql0icKZL0Rbk8hsPQv7IiMWFpdJdE7+qEz
    8xkAf8Z19+Y6l0uy1fEEC94FeomLl7KnRXPZxqfiz8B7TWbGPTvIh1v3ICutkIou
    +AWKb5MPx2pfEFSIReQsPfleLIARKxYGxRYPR4quCq6XK3teIWzjbAZj6D/FS9Em
    u2K9prKLitcNkTXDEzSqvOxRLGgD4/TZCcQsl7gRONdUQXYFWTOWH9CVvirsqDNU
    W68y10ywP1pjF1dHRgfMVH8fqL28T7Yp0XtYXFmXwlxutj7lh2Eb2vwcnMs288Kn
    t5E8aUGOFfheLYrD6wvF9t/xcmuibHosl02cAiFhZWVuzMz8wQ==
    -----END CERTIFICATE-----
