{
 "title": "CB Business Metrics Dashboards",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CB Orchestrator Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CB Orchestrator Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job)(rate(tsbcb_message_process_time_seconds_sum {namespace=\"cb\"}[5m]))/ sum by (namespace, job)(rate(tsbcb_message_process_time_seconds_count{namespace=\"cb\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CB Orchestrator Response Time v2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job)(rate(tsbcb_message_full_process_time_seconds_sum {namespace=\"cb\"}[5m]))/ sum by (namespace, job)(rate(tsbcb_message_full_process_time_seconds_count{namespace=\"cb\"}[5m]))",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "sum by (namespace, job, module)(rate(tsbcb_message_process_time_seconds_sum {namespace=\"cb\"}[5m]))/sum by (namespace, job, module)(rate(tsbcb_message_process_time_seconds_count{namespace=\"cb\"}[5m]))",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CB Authentication API Response Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "CB Auth API Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"cb\",uri=~\".*enrol.*|.*verify.*\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"cb\",uri=~\".*enrol.*|.*verify.*\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "CB Apps Up State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CDC Customer Data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-cdc-customer-data\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Authentication API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace=\"cb\",uri=~\".*verify.*\"}[5m]))*60)",
     "legendFormat": "{{job}} {{uri}}"
    },
    {
     "expr": "(sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace=\"cb\",uri=~\".*enrol.*\"}[5m]))*60)",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "Enrich Sub Topology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-enrich\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Fulfill Sub Topology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-fulfill\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "LP Adaptor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (rate(lp_adapter_rdkafka_topic_partition_msgs {namespace=\"cb\"}[5m]))*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HMAC Generation Topology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-hmac-generation-topology\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Natural Language Process Handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (rate(spring_kafka_listener_seconds_count {namespace=\"cb\", job=\"tsb-cb-nlp-handler\"}[5m]))*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Spring API Gateway",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace, routeId)(rate(spring_cloud_gateway_requests_seconds_count{ namespace=\"cb\", routeId=~\".*verify.*\"}[5m]))*60)",
     "legendFormat": "{{routeId}}"
    },
    {
     "expr": "(sum by (job, namespace, routeId)(rate(spring_cloud_gateway_requests_seconds_count{ namespace=\"cb\", routeId=~\".*enrol.*\"}[5m]))*60)",
     "legendFormat": "{{routeId}}"
    }
   ]
  },
  {
   "title": "ADS Customer Lookup Topology",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-ads-customer-lookup-topology\"})*60)"
    }
   ]
  },
  {
   "title": "CB Orchestrator",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-orchestrator\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CB Housekeeping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"cb\", job=\"tsb-cb-housekeeping\"})*60)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CB POD Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "CB Application POD Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=~\"tsb-cb.*\",namespace=\"cb\"}",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{statefulset=~\"tsb-cb.*\",namespace=\"cb\"}",
       "legendFormat": "{{statefulset}}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"nginx-ingress-ingress-nginx-controller\",namespace=\"cb\"}",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CDC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "User Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application, namespace) (records_in_total{application=~\"tsb-cb-pr-ingest-tbbv-bs-codigos-acceso|tsb-cb-pr-ingest-tbbv-bs-auth-data|tsb-cb-pr-ingest-tbbv-bs-usuarios|tsb-cb-pr-ingest-tbbv-bs-contratos\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}}"
      },
      {
       "expr": "sum by (application, namespace) (records_in_total_access_codes_total{application=\"tsb-cb-pr-ingest-das-users\",input=\"ACCESS_CODES\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}} {{input}}"
      },
      {
       "expr": "sum by (application, namespace) (records_in_total_credentials_total{application=\"tsb-cb-pr-ingest-das-users\",input=\"CREDENTIALS\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}} {{input}}"
      },
      {
       "expr": "sum by (application, namespace) (records_in_total_users_by_das_user_total{application=\"tsb-cb-pr-ingest-das-users\",input=\"USERS_BY_DAS_USER\",namespace=\"cb\"})",
       "legendFormat": "{{application}} {{input}}"
      },
      {
       "expr": "sum by (application, namespace) (records_out_total{application=\"tsb-cb-pr-ingest-das-users\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}}"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_users_in_total{namespace=\"cb\"})",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_users_out_total{namespace=\"cb\"})\n",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Device Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application, namespace) (records_in_total{application=\"tsb-cb-pr-ingest-tbbv-bs-enrollments\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}}"
      },
      {
       "expr": "sum by (application, namespace) (records_out_total{application=\"tsb-cb-pr-ingest-tbbv-bs-enrollments\",namespace=\"cb\"})\n",
       "legendFormat": "{{application}}"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_devices_in_total{namespace=\"cb\"})\n\n",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_devices_out_total{namespace=\"cb\"})\n",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Profile Queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (application, namespace) (records_in_total{application=\"tsb-cb-pr-ingest-pe-11\",namespace=\"cb\"})",
       "legendFormat": "{{application}}-records_in_total"
      },
      {
       "expr": "sum by (application, namespace) (records_out_total{application=\"tsb-cb-pr-ingest-pe-11\",namespace=\"cb\"})",
       "legendFormat": "{{application}}-records_out_total"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_profiles_in_total{namespace=\"cb\"})",
       "legendFormat": "{{job}}-cdc_profiles_in"
      },
      {
       "expr": "sum by (job, namespace) (tsbcb_cdc_profiles_out_total{namespace=\"cb\"})",
       "legendFormat": "{{job}}-cdc_profiles_out"
      }
     ]
    }
   ]
  }
 ]
}