{
 "title": "COB  Microservices Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, uri)(http_server_requests_seconds_count{namespace=\"cob\", service=~\"tsb-onboarding-restproxy.*\",uri!~\"/actuator/prometheus|/health|/\\\\*\\\\*\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(namespace, service)(http_server_requests_seconds_sum{namespace=\"cob\", service=~\"tsb-onboarding-restproxy.*\",uri!=\"/actuator/prometheus|/health\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Failure Rate(%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, service) (rate(http_server_requests_seconds_count {namespace=\"cob\",service=~\"tsb-onboarding-restproxy.*\",outcome!=\"SUCCESS\",uri!=\"/actuator/prometheus|/health\"}[5m])) / sum by (namespace, service) (rate(http_server_requests_seconds_count {namespace=\"cob\",service=~\"tsb-onboarding-restproxy.*\",uri!=\"/actuator/prometheus|/health\"}[5m]))) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}