{
 "title": "COB - kafka dashboards",
 "time": { "from": "2022-06-23T21:48:45.465Z", "to": "2022-07-21T21:48:45.465Z" },
 "panels": [
  {
   "title": "Proteo_EA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_ea_requests_made_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_ea_successful_requests_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_ea_failed_requests_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_failure"
    }
   ]
  },
  {
   "title": "Proteo_FA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_fa_requests_made_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_fa_successful_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_fa_failed_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_failed"
    }
   ]
  },
  {
   "title": "Kafka consumer rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, service) (kafka_consumer_request_rate{namespace=\"cob\"})"
    }
   ]
  }
 ]
}