{
 "title": "COB - External  Services Connectivity",
 "time": { "from": "2022-06-23T21:48:45.465Z", "to": "2022-07-21T21:48:45.465Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proteo_Evaluate_Apply",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_ea_requests_made_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_ea_successful_requests_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_ea_failed_requests_total{job=\"tsb-onboarding-proteo-call-evaluate\",namespace=\"cob\"})",
     "legendFormat": "EA_failure"
    }
   ]
  },
  {
   "title": "Onfido_token_generation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (onfido_token_requests_made_total{job=\"tsb-onboarding-identity-onfido-generate-token\",namespace=\"cob\"})",
     "legendFormat": "Onfido_token_total_request"
    },
    {
     "expr": "sum by (job, namespace) (onfido_token_successful_requests_total{job=\"tsb-onboarding-identity-onfido-generate-token\",namespace=\"cob\"})",
     "legendFormat": "Onfido_token_success"
    },
    {
     "expr": "sum by (job, namespace) (onfido_token_failed_requests_total{job=\"tsb-onboarding-identity-onfido-generate-token\",namespace=\"cob\"})",
     "legendFormat": "Onfido_token_failed"
    }
   ]
  },
  {
   "title": "Proteo_Finalize_apply",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_fa_requests_made_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_fa_successful_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_fa_failed_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_failed"
    }
   ]
  },
  {
   "title": "Onfido_Create_applicant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (onfido_ca_requests_made_total{job=\"tsb-onboarding-identity-onfido-create-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_CA_total_request"
    },
    {
     "expr": "sum by (job, namespace) (onfido_ca_successfull_requests_total{job=\"tsb-onboarding-identity-onfido-create-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_CA_success"
    },
    {
     "expr": "sum by (job, namespace) (onfido_ca_failed_requests_total{job=\"tsb-onboarding-identity-onfido-create-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_CA_failed"
    }
   ]
  },
  {
   "title": "Proteo_Activation_Code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_activationcode_requests_made_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_activationcode_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_activationcode_successful_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_activationcode_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_activationcode_failed_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_activationcode_failed"
    }
   ]
  },
  {
   "title": "Onfido_Get_applicant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (onfido_ga_requests_made_total{job=\"tsb-onboarding-identity-onfido-get-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_GA_total_request"
    },
    {
     "expr": "sum by (job, namespace) (onfido_ga_successfull_requests_total{job=\"tsb-onboarding-identity-onfido-get-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_GA_success"
    },
    {
     "expr": "sum by (job, namespace) (onfido_ga_failed_requests_total{job=\"tsb-onboarding-identity-onfido-get-applicant\",namespace=\"cob\"})",
     "legendFormat": "Onfido_GA_failed"
    }
   ]
  },
  {
   "title": "Proteo_OpenAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_openam_requests_made_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_OpenAM_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_openam_successful_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_OpenAM_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_openam_failed_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_OpenAM_failed"
    }
   ]
  },
  {
   "title": "Onfido_download_asset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (onfido_da_requests_made_total{job=\"tsb-onboarding-identity-onfido-download-asset\",namespace=\"cob\"})",
     "legendFormat": "Onfido_download_total_request"
    },
    {
     "expr": "sum by (job, namespace) (onfido_da_successfull_requests_total{job=\"tsb-onboarding-identity-onfido-download-asset\",namespace=\"cob\"})",
     "legendFormat": "Onfido_download_success"
    },
    {
     "expr": "sum by (job, namespace) (onfido_da_failed_requests_total{job=\"tsb-onboarding-identity-onfido-download-asset\",namespace=\"cob\"})",
     "legendFormat": "Onfido_download_failure"
    }
   ]
  },
  {
   "title": "Proteo_Welcome_Letter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (proteo_welcomeletter_requests_made_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_WelcomeLetter_total"
    },
    {
     "expr": "sum by (job, namespace) (proteo_welcomeletter_successful_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_WelcomeLetter_success"
    },
    {
     "expr": "sum by (job, namespace) (proteo_welcomeletter_failed_requests_total{job=\"tsb-onboarding-proteo-call-finalize\",namespace=\"cob\"})",
     "legendFormat": "FA_WelcomeLetter_failed"
    }
   ]
  },
  {
   "title": "Kafka consumer rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, service) (kafka_consumer_request_rate{namespace=\"cob\"})"
    }
   ]
  }
 ]
}