---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cop-microservices-cm
  namespace: prometheus
data:
  COPMicroservices.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 184,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (job, namespace) (rate(integration_service_cop_requests_received_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Integration Service request processing Rate",
              "refId": "A"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_restproxy_cop_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Rest Proxy request processing Rate",
              "refId": "B"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_restproxy_cop_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Rest Proxy request processing Rate",
              "refId": "C"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_enrichment_cop_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Enrichment",
              "refId": "D"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_name_verification_cop_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Name Verification",
              "refId": "E"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_openbanking_cop_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Openbanking",
              "refId": "F"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Service Request Rates",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:62",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "$$hashKey": "object:63",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 4,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (job, namespace) (rate(integration_service_requests_successful_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Integration Service request processing Rate",
              "refId": "A"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_restproxy_successful_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Rest Proxy request processing Rate",
              "refId": "B"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_restproxy_successful_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Rest Proxy request processing Rate",
              "refId": "C"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_name_verification_successful_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Enrichment",
              "refId": "D"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_enrichment_successful_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Name Verification",
              "refId": "E"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_openbanking_successful_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Openbanking",
              "refId": "F"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Success Response Rates",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:100",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "$$hashKey": "object:101",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 9
          },
          "hiddenSeries": false,
          "id": 6,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (job, namespace) (rate(integration_service_requests_failed_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Integration Service request processing Rate",
              "refId": "A"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_restproxy_failed_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Rest Proxy request processing Rate",
              "refId": "B"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_restproxy_failed_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Rest Proxy request processing Rate",
              "refId": "C"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_enrichment_failed_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Enrichment",
              "refId": "D"
            },
            {
              "expr": "sum by (job, namespace) (rate(inbound_name_verification_failed_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Inbound Name Verification",
              "refId": "E"
            },
            {
              "expr": "sum by (job, namespace) (rate(outbound_openbanking_failed_requests_total {namespace=\"cop\"}[1m])*60)",
              "interval": "",
              "legendFormat": "Outbound Openbanking",
              "refId": "F"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Failed Response Rates",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:141",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "$$hashKey": "object:142",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "COP Microservices Dashboard",
      "uid": "X7-qbbm7k",
      "version": 1
    }