{
 "title": "Consul-Vault CB",
 "description": "Dashboard for Project-Environment EC2 Nodes",
 "templating": {
  "list": [
   { "name": "project", "label": "Project", "query": "label_values(project)" },
   { "name": "subsystem", "label": "Subsystem", "query": "label_values(up{},subsystem)" },
   { "name": "environment", "query": "label_values(up{},environment)" },
   {
    "name": "instance",
    "query": "label_values(up{environment=~\"$environment\"},instance)"
   },
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(up{environment=~\"$environment\"},name)"
   }
  ]
 },
 "panels": [
  { "title": "EC2 CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU System Load (5m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"system|irq|softirq|iowait\"}[5m])) * 100)"
    },
    {
     "expr": "(avg by (instance) (irate(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU User Load (5m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"user\"}[5m])) * 100)"
    },
    {
     "expr": "(avg by (instance) (irate(wmi_cpu_time_total{instance=\"$instance\",mode=~\"user\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Idle Load (5m)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 13, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"idle\"}[5m])) * 100)"
    },
    {
     "expr": "(avg by (instance) (irate(wmi_cpu_time_total{instance=\"$instance\",mode=~\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))"
    },
    {
     "expr": "count(count(wmi_cpu_time_total{instance=\"$instance\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Current CPU Utilization",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"system|irq|softirq|iowait\"}[5m])) * 100)",
     "legendFormat": "System"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"user\"}[5m])) * 100)",
     "legendFormat": "User"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"idle\"}[5m])) * 100)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "System"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"user\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "User"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"idle\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"system|irq|softirq|iowait\"}[5m])) * 100)",
     "legendFormat": "System"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"user\"}[5m])) * 100)",
     "legendFormat": "User"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"idle\"}[5m])) * 100)",
     "legendFormat": "Idle"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "System"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"user\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "User"
    },
    {
     "expr": "sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"idle\"})/sum(wmi_cpu_time_total{instance=\"$instance\",mode=~\"dpc|interrupt|privileged|user|idle\"})*100",
     "legendFormat": "Idle"
    },
    {
     "expr": "(avg by (instance) (1 - irate(node_cpu_seconds_total{instance=\"$instance\",mode=~\"idle\"}[5m])) * 100)",
     "legendFormat": "Total Used"
    }
   ]
  },
  { "title": "EC2 Memory Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Current Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((node_memory_MemFree_bytes{instance=\"$instance\"}) + (node_memory_Cached_bytes{instance=\"$instance\"})) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100"
    },
    {
     "expr": "(wmi_memory_available_bytes{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Current Cached Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100"
    },
    {
     "expr": "(wmi_memory_cache_bytes{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Current Swap Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100"
    },
    {
     "expr": "(wmi_memory_swap_pages_written_total{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Current Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 11 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=\"$instance\"} - wmi_memory_available_bytes{instance=\"$instance\"} - wmi_memory_cache_bytes{instance=\"$instance\"} - wmi_memory_swap_pages_written_total {instance=\"$instance\"}) / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((node_memory_MemFree_bytes{instance=\"$instance\"}) + (node_memory_Cached_bytes{instance=\"$instance\"})) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Available"
    },
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Used"
    },
    {
     "expr": "((node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Cached"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Swap"
    },
    {
     "expr": "(wmi_memory_available_bytes{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Available"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=\"$instance\"} - wmi_memory_available_bytes{instance=\"$instance\"} - wmi_memory_cache_bytes{instance=\"$instance\"} - wmi_memory_swap_pages_written_total {instance=\"$instance\"}) / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Used"
    },
    {
     "expr": "((wmi_memory_cache_bytes{instance=\"$instance\"}) / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Cached"
    },
    {
     "expr": "(wmi_memory_swap_pages_written_total{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((node_memory_MemFree_bytes{instance=\"$instance\"}) + (node_memory_Cached_bytes{instance=\"$instance\"})) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"} - node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "((node_memory_Cached_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Cached Memory"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Swap Memory"
    },
    {
     "expr": "(wmi_memory_available_bytes{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=\"$instance\"} - wmi_memory_available_bytes{instance=\"$instance\"} - wmi_memory_cache_bytes{instance=\"$instance\"} - wmi_memory_swap_pages_written_total {instance=\"$instance\"}) / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "((wmi_memory_cache_bytes{instance=\"$instance\"}) / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Cached Memory"
    },
    {
     "expr": "(wmi_memory_swap_pages_written_total{instance=\"$instance\"} / (wmi_cs_physical_memory_bytes{instance=\"$instance\"})) * 100",
     "legendFormat": "Swap Memory"
    }
   ]
  },
  { "title": "EC2 Volumes Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{instance=~\"$instance\"} / node_filesystem_size_bytes{instance=\"$instance\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "1 - wmi_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}  / wmi_logical_disk_size_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"} ",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Volume Read/Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps", "label": "read b/s (-) / write b/s (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Write bytes"
    },
    {
     "expr": "sum(irate(wmi_logical_disk_read_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m]))",
     "legendFormat": "Read bytes"
    },
    {
     "expr": "sum(irate(wmi_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m]))",
     "legendFormat": "Write bytes"
    }
   ]
  },
  {
   "title": "Volume Read/Write Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    {
     "format": "opm",
     "label": "read ops/min (-) / write ops/min (+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Read ops"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Write ops"
    },
    {
     "expr": "irate(wmi_logical_disk_split_ios_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "legendFormat": "I/O ops"
    }
   ]
  },
  {
   "title": "Volume Total Read/Write Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    {
     "format": "ms",
     "label": "read total time (-) / write total time (+)"
    }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_time_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Read time"
    },
    {
     "expr": "sum(irate(node_disk_write_time_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Write time"
    },
    {
     "expr": "sum(irate(wmi_logical_disk_read_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Read time"
    },
    {
     "expr": "sum(irate(wmi_logical_disk_write_seconds_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Write time"
    }
   ]
  },
  { "title": "EC2 Network Traffic Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "Bps", "label": "In  b/s (-) / out b/s (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Traffic In"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Traffic Out"
    },
    {
     "expr": "sum(irate(wmi_net_bytes_received_total{instance=\"$instance\"}[5m]))",
     "legendFormat": "Traffic In"
    },
    {
     "expr": "sum(irate(wmi_net_bytes_sent_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "Traffic Out"
    }
   ]
  }
 ]
}