{
 "title": "Scylla COP - Part2",
 "templating": {
  "list": [
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=~\"ec2-discover-node-exporter\",instance=~\".*scylla.*\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Optimization</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Optimization</h1>"
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "singlestat",
   "description": "All of the requests should be prepared\n\nPrepared statements remove the overhead of parsing the query every time and allow optimal routing of requests from client to server",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(irate(scylla_query_processor_statements_prepared{job=~\"ec2-discover-scylla-default\"}[5m])) /(sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])) + sum(irate(scylla_cql_inserts{job=~\"ec2-discover-scylla-default\"}[5m])) + sum(irate(scylla_cql_updates{job=~\"ec2-discover-scylla-default\"}[5m])) + sum(irate(scylla_cql_deletes{job=~\"ec2-discover-scylla-default\"}[5m])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "graph",
   "description": "All of the requests should be prepared\n",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_query_processor_statements_prepared{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "singlestat",
   "description": "All requests should be paged\n\nNon Paged request sources:\n- Client modifying the fetch size\n\nNon Paged requests require reading all the results and returning them in a single request.",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(irate(scylla_cql_unpaged_select_queries{job=~\"ec2-discover-scylla-default\"}[5m]))/sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "graph",
   "description": "Non-Paged requests require reading all the results and returning them in a single request",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_unpaged_select_queries{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Token Aware",
   "type": "singlestat",
   "description": "All of the requests should be Token Aware\n\nNon Token Aware requests sources:\n* Non-Prepared Stamements\n* Client not using a Token Aware load balancing policy\n\nTokenAware requests are sent to a Scylla node that is also a replica. Token Un-Aware requests require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 2 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - floor(100*(sum(irate(scylla_storage_proxy_coordinator_reads_local_node{job=~\"ec2-discover-scylla-default\"}[5m])) +sum(irate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{job=~\"ec2-discover-scylla-default\"}[5m])))/(sum(irate(scylla_cql_inserts{job=~\"ec2-discover-scylla-default\"}[5m]) + irate(scylla_cql_updates{job=~\"ec2-discover-scylla-default\"}[5m]) + irate(scylla_cql_deletes{job=~\"ec2-discover-scylla-default\"}[5m]) + irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Token Aware Queries",
   "type": "graph",
   "description": "Requests that are not token aware indicates that requests are not routed to the right node, which require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) - sum(irate(scylla_storage_proxy_coordinator_reads_local_node{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) + sum(irate(scylla_cql_inserts{job=~\"ec2-discover-scylla-default\"}[5m]) + irate(scylla_cql_updates{job=~\"ec2-discover-scylla-default\"}[5m]) + irate(scylla_cql_deletes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) - sum(irate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)\n"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "singlestat",
   "description": "Reversed CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with ORDER BY that is different from the \"CLUSTERING ORDER BY\" of the table\nAlternatives:\n\n* Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_reverse_queries{job=~\"ec2-discover-scylla-default\"}[5m])) / sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "graph",
   "description": "Reversed CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reverse_queries{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "singlestat",
   "description": "ALLOW FILTERING CQL Reads, the percentage of read requests with 'ALLOW FILTERING'\n\nALLOW FILTERING CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned - check \n\"ALLOW FILTERING CQL Read Filtered Rows to check what percentage of the data is used\"\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_filtered_read_requests{job=~\"ec2-discover-scylla-default\"}[5m])) / sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "graph",
   "description": "Read requests with ALLOW FILTERING\n\nALLOW FILTERING CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_read_requests{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING Filtered Rows",
   "type": "singlestat",
   "description": "ALLOW FILTERING Filtered rows, the percentage of rows that were read and then filtered.\n\nALLOW FILTERING CQL Reads entail additional processing on server side. \nReading a row and then filter it is a waste of resources.\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_filtered_rows_dropped_total{job=~\"ec2-discover-scylla-default\"}[5m]))  /sum(irate(scylla_cql_filtered_rows_read_total{job=~\"ec2-discover-scylla-default\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Read Filtering",
   "type": "graph",
   "description": "CQL Queries with ALLOW FILTERING should be avoided.\nDropped rows are rows that were read but were filtered by the server.\nWhen dropped rows is relatively high you should consider the alternatives",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_read_total{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "rows read {{instance}}"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_matched_total{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "rows matched {{instance}}"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_dropped_total{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "rows dropped {{instance}}"
    }
   ]
  },
  {
   "title": "CQL ANY Queries",
   "type": "singlestat",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ANY CL Queries",
   "type": "graph",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "singlestat",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "graph",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\",consistency_level=\"ALL\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cross DC Information</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cross DC Information</h1>"
  },
  {
   "title": "CQL ONE Queries",
   "type": "singlestat",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\",consistency_level=\"ONE\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ONE CL Queries",
   "type": "graph",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\",consistency_level=\"ONE\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "singlestat",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\",consistency_level=\"QUORUM\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "graph",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 22 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"ec2-discover-scylla-default\",consistency_level=\"QUORUM\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Errors</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Errors</h1>"
  },
  {
   "title": "Local Reads Error",
   "type": "graph",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_read_errors_local_node{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local Write Error",
   "type": "graph",
   "description": "Number of write requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_write_errors_local_node{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AIO Error",
   "type": "graph",
   "description": "Number of AIO Errors",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_reactor_aio_errors{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads Unavailable Error",
   "type": "graph",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_read_unavailable{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Unavailable Error",
   "type": "graph",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_write_unavailable{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Range Unavailable Error",
   "type": "graph",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_range_unavailable{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "C++ Exceptions instance",
   "type": "graph",
   "description": "Number of C++ exceptions thrown.\n\n A peak in the number of exceptions is an indication of a potential problem.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_reactor_cpp_exceptions{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  },
  {
   "title": "Compactions I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_compaction_delay{job=~\"ec2-discover-scylla-default\"} ) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 50 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 50 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_query_delay{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 56 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_commitlog_delay{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_memtable_flush_delay{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 68 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_read_delay{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_operations{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_write_delay{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 80 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_bytes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}