{
 "title": "COP Microservices Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Outbound Rest Proxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( outbound_restproxy_cop_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( outbound_restproxy_successful_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( outbound_restproxy_failed_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Outbound Cop Authorisation (HMAC Validation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( cop_authorisation_cop_requests_received_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( cop_authorisation_requests_successful_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( cop_authorisation_requests_failed_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Outbound Openbanking Topology (Fetch bankcode)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( outbound_openbanking_cop_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( outbound_openbanking_successful_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( outbound_openbanking_failed_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": " Outbound Integration Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( integration_service_cop_requests_received_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( integration_service_requests_successful_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( integration_service_requests_failed_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Openbanking Authorisation (Auth Token Fetch)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( openbanking_authorisation_cop_requests_received_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( openbanking_authorisation_requests_successful_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( openbanking_authorisation_requests_failed_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Inbound Rest-proxy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( inbound_restproxy_cop_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_restproxy_successful_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_restproxy_failed_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Inbound Enrichment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (rate( inbound_enrichment_cop_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_enrichment_successful_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_enrichment_failed_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Inbound Name-verification",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nsum by (job, namespace) (rate( inbound_name_verification_cop_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_name_verification_successful_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum by (job, namespace) (rate( inbound_name_verification_failed_requests_total {namespace=\"cop\"}[1m])*60)",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}