{
 "title": "Scylla COP - Part1",
 "templating": {
  "list": [
   { "name": "func", "label": "Function", "query": "sum,avg,max,min,stddev,stdvar" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(up{job=~\"ec2-discover-node-exporter\",instance=~\".*scylla.*\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"ec2-discover-node-exporter\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"ec2-discover-node-exporter\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Joining",
   "type": "singlestat",
   "description": "Number of nodes that reported their status as Starting or Joining",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{job=~\"ec2-discover-node-exporter\"}==1) +  count(scylla_node_operation_mode{job=~\"ec2-discover-node-exporter\"}==2)OR vector(0)",
     "labelSelector": "*",
     "legendFormat": "Joining",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Leaving",
   "type": "singlestat",
   "description": "Number of nodes that reported their status as  Leaving, Decommissioned, Draining or Drained",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{job=~\"ec2-discover-node-exporter\"}>3)OR vector(0)",
     "legendFormat": "Leaving"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table-old",
   "description": "Nodes Information table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{job=~\"ec2-discover-scylla-default\"} + on (instance) group_left() scylla_node_operation_mode{job=~\"ec2-discover-scylla-default\"}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"ec2-discover-node-exporter\"}) by (instance) - sum(node_filesystem_avail_bytes{job=~\"ec2-discover-node-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Served - Coordinator",
   "type": "graph",
   "description": "Amount of requests served as the coordinator. Imbalances here represent dispersion at the client-side level or connection balancing level, not your data model.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_transport_requests_served{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) + $func(irate(scylla_thrift_served{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Active Alerts", "type": "table-old", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CPU Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CPU Info</h1>"
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"ec2-discover-node-exporter\"}[1m]) * 100)",
     "legendFormat": "{{instance}} Total CPU Used"
    }
   ]
  },
  {
   "title": "Scylla Reactor Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "$func(scylla_reactor_utilization{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}} reactor_utilization"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory Info</h1>"
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-(node_memory_MemFree_bytes{job=~\"ec2-discover-node-exporter\"}/(node_memory_MemTotal_bytes{job=~\"ec2-discover-node-exporter\"})*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((node_memory_SwapFree_bytes{job=~\"ec2-discover-node-exporter\"}) / (node_memory_SwapTotal_bytes{job=~\"ec2-discover-node-exporter\"})) * 100",
     "legendFormat": "{{name}} Swap Memory Utilization"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Volume details</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Volume details</h1>"
  },
  {
   "title": "% Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=~\"/var/lib/scylla|/var/lib/scylla/commitlog\"} / node_filesystem_size_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=~\"/var/lib/scylla|/var/lib/scylla/commitlog\"}",
     "legendFormat": "{{name}}   {{device}} --> {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=~\"/var/lib/scylla\"} - node_filesystem_free_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=~\"/var/lib/scylla\"}",
     "legendFormat": "Used size: {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=~\"/var/lib/scylla\"}",
     "legendFormat": "Total size: {{mountpoint}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Info</h1>"
  },
  {
   "title": "Total Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 58 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=\"/var/lib/scylla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=\"/var/lib/scylla\"})-sum(node_filesystem_avail_bytes{job=~\"ec2-discover-node-exporter\",mountpoint=\"/var/lib/scylla\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",job=~\"ec2-discover-node-exporter\"}) by (instance,mountpoint) - sum(node_filesystem_avail_bytes{fstype=\"xfs\",job=~\"ec2-discover-node-exporter\"}) by (instance,mountpoint)",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_bytes_written{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_reads_completed{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_bytes_read{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network info</h1>"
  },
  {
   "title": "Interface Rx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_receive_packets{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Tx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_packets_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Rx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Tx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes{job=~\"ec2-discover-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Latencies - Coordinator</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Latencies - Coordinator</h1>"
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_sum{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)/($func(rate(scylla_storage_proxy_coordinator_write_latency_count{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) + 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "95th percentile write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_sum{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)/($func(rate(scylla_storage_proxy_coordinator_read_latency_count{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance) + 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "95th percentile read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 104 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache by instance</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache by instance</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 104 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts</h1>"
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "Number of rows that were read from the cache, without needing to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_cache_row_hits{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "description": "Number of rows that were not present in the cache, and had to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_cache_row_misses{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Timeouts/Minutes",
   "type": "graph",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_write_timeouts{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Timeouts/Minutes",
   "type": "graph",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 106 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_read_timeouts{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 112 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cluster Cache</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cluster Cache</h1>"
  },
  {
   "title": "Cache Total Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 114 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_total{job=~\"ec2-discover-scylla-default\"})"
    }
   ]
  },
  {
   "title": "Cache Used (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 114 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_used{job=~\"ec2-discover-scylla-default\"})/sum(scylla_cache_bytes_total{job=~\"ec2-discover-scylla-default\"})*100"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_hits{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Row Hits 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_hits{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Partition Hits 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Active Reads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_active_reads{job=~\"ec2-discover-scylla-default\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cache Merges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_partition_merges{job=~\"ec2-discover-scylla-default\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_misses{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Row Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_misses{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Partition Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_concurrent_misses_same_key{job=~\"Scylla Exporter - .*\"}[2m]))",
     "legendFormat": "Cache Concurrent Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_reads_with_misses{job=~\"Scylla Exporter - .*\"}[2m]))",
     "legendFormat": "Cache Reads Misses 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_evictions{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Row Evictions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_evictions{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Partition Evictions 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Insertions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_insertions{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Row Insertions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_insertions{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Partition Insertions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_static_row_insertions{job=~\"Scylla Exporter - .*\"}[2m]))",
     "legendFormat": "Cache Static Row Insertions 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Removals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_removals{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Row Removals 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_removals{job=~\"ec2-discover-scylla-default\"}[2m]))",
     "legendFormat": "Cache Partition Removals 2m Avg"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 137 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL - Coordinator</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL - Coordinator</h1>"
  },
  {
   "title": "CQL Insert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_inserts{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_deletes{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_updates{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client CQL connections",
   "type": "graph",
   "description": "amount of CQL connections currently established",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_transport_current_connections{job=~\"ec2-discover-scylla-default\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Batches",
   "type": "graph",
   "description": "Number of CQL batches command, each batched command is counted once",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_batches{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Command In Batches",
   "type": "graph",
   "description": "Number of CQL command batched. Each batch would add the number of commands inside the batch",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_statements_in_batches{job=~\"ec2-discover-scylla-default\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}