{
 "title": "COP-Phase2  Microservices Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Outbound Obconnect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\"}[5m])) * 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\", status=\"200\"}[5m])) * 10",
     "legendFormat": "OK 200"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\", status=\"404\"}[5m])) * 10",
     "legendFormat": "Not Found 404"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\", status=\"403\"}[5m])) * 10",
     "legendFormat": "Forbidden 403"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\", status=\"502\"}[5m])) * 10",
     "legendFormat": "Bad Gateway 502"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\", status=\"503\"}[5m])) * 10",
     "legendFormat": "Service Not Available"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(http_server_requests_seconds_sum {namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[5m])) / sum by (namespace, container) (rate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[5m]))"
    }
   ]
  },
  {
   "title": "AverageThrough put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, container) (rate(http_server_requests_seconds_count {namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", method=\"POST\"}[5m])) * 60)"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{deployment=~\"tsb-cop2-outbound-obconnect.*\",namespace=\"cop-phase2\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[2m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cop-phase2\",container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_working_set_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Eden Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Eden Space\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Eden Space\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Survivor Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Survivor Space\"})"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Tenured Gen (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Tenured Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Tenured Gen\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\", id=\"Tenured Gen\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Inbound Fetch Name Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\"}[5m])) * 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\", status=\"200\"}[5m])) * 10",
     "legendFormat": "OK 200"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\", status=\"404\"}[5m])) * 10",
     "legendFormat": "Not Found 404"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\", status=\"403\"}[5m])) * 10",
     "legendFormat": "Forbidden 403"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\", status=\"502\"}[5m])) * 10",
     "legendFormat": "Bad Gateway 502"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\", status=\"503\"}[5m])) * 10",
     "legendFormat": "Service Not Available"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(http_server_requests_seconds_sum {namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"}[5m])) / sum by (namespace, container) (rate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"}[5m]))"
    }
   ]
  },
  {
   "title": "AverageThrough put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, container) (rate(http_server_requests_seconds_count {namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", method=\"POST\"}[5m])) * 60)"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{deployment=~\"tsb-cop2-fetch-name-details.*\",namespace=\"cop-phase2\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"}[2m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cop-phase2\",container=\"tsb-cop2-fetch-name-details\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_working_set_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Eden Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Eden Space\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Eden Space\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Survivor Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Survivor Space\"})"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Tenured Gen (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Tenured Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Tenured Gen\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-fetch-name-details\", id=\"Tenured Gen\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "HMAC Validator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\"}[5m])) * 10",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\", status=\"200\"}[5m])) * 10",
     "legendFormat": "OK 200"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\", status=\"404\"}[5m])) * 10",
     "legendFormat": "Not Found 404"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\", status=\"403\"}[5m])) * 10",
     "legendFormat": "Forbidden 403"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\", status=\"502\"}[5m])) * 10",
     "legendFormat": "Bad Gateway 502"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\", status=\"503\"}[5m])) * 10",
     "legendFormat": "Service Not Available"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(http_server_requests_seconds_sum {namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\"}[5m])) / sum by (namespace, container) (rate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\"}[5m]))"
    }
   ]
  },
  {
   "title": "AverageThrough put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, container) (rate(http_server_requests_seconds_count {namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", method=\"POST\"}[5m])) * 60)"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{deployment=~\"tsb-cop2-hmac-validator.*\",namespace=\"cop-phase2\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[2m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cop-phase2\",container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 74 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_working_set_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Eden Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Eden Space\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Eden Space\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Survivor Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Survivor Space\"})"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Tenured Gen (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Tenured Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Tenured Gen\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-hmac-validator\", id=\"Tenured Gen\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "API Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\"}[5m])) * 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\", status=\"200\"}[5m])) * 10",
     "legendFormat": "OK 200"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\", status=\"404\"}[5m])) * 10",
     "legendFormat": "Not Found 404"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\", status=\"403\"}[5m])) * 10",
     "legendFormat": "Forbidden 403"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\", status=\"502\"}[5m])) * 10",
     "legendFormat": "Bad Gateway 502"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\", status=\"503\"}[5m])) * 10",
     "legendFormat": "Service Not Available"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(http_server_requests_seconds_sum {namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\"}[5m])) / sum by (namespace, container) (rate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\"}[5m]))"
    }
   ]
  },
  {
   "title": "AverageThrough put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, container) (rate(http_server_requests_seconds_count {namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", method=\"POST\"}[5m])) * 60)"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{deployment=~\"tsb-cop2-api-gateway.*\",namespace=\"cop-phase2\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[2m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cop-phase2\",container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 103 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_working_set_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Eden Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Eden Space\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Eden Space\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Survivor Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Survivor Space\"})"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Tenured Gen (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Tenured Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Tenured Gen\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-api-gateway\", id=\"Tenured Gen\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "MI Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\"}[5m])) * 10",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\", status=\"200\"}[5m])) * 10",
     "legendFormat": "OK 200"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\", status=\"404\"}[5m])) * 10",
     "legendFormat": "Not Found 404"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\", status=\"403\"}[5m])) * 10",
     "legendFormat": "Forbidden 403"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\", status=\"502\"}[5m])) * 10",
     "legendFormat": "Bad Gateway 502"
    },
    {
     "expr": "sum(irate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\", status=\"503\"}[5m])) * 10",
     "legendFormat": "Service Not Available"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, container) (rate(http_server_requests_seconds_sum {namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\"}[5m])) / sum by (namespace, container) (rate(http_server_requests_seconds_count{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\"}[5m]))"
    }
   ]
  },
  {
   "title": "AverageThrough put",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, container) (rate(http_server_requests_seconds_count {namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", method=\"POST\"}[5m])) * 60)"
    }
   ]
  },
  {
   "title": "Service Pod Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(kube_deployment_status_replicas_available{deployment=~\"tsb-cop2-mi-topology.*\",namespace=\"cop-phase2\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}[2m]))",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=\"cop-phase2\",container=\"tsb-cop2-outbound-obconnect\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"cop-phase2\", container=\"tsb-cop2-outbound-obconnect\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (container_memory_working_set_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Eden Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Eden Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Eden Space\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Eden Space\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Survivor Space (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Survivor Space\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Survivor Space\"})"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Survivor Space\"})"
    }
   ]
  },
  {
   "title": "Tenured Gen (heap)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 16, "y": 140 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (container) (jvm_memory_used_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Tenured Gen\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by (container) (jvm_memory_committed_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Tenured Gen\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg by (container) (jvm_memory_max_bytes{namespace=\"cop-phase2\", container=\"tsb-cop2-mi-topology\", id=\"Tenured Gen\"})",
     "legendFormat": "Limit"
    }
   ]
  }
 ]
}