{
 "title": "TSB-ODS-SYS-API-2",
 "time": { "from": "2021-03-03T18:14:39.832Z", "to": "2021-06-06T19:33:39.064Z" },
 "panels": [
  {
   "title": "DV01",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-dv01-account\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-dv01-account\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for DV01",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-dv01-account\"}))"
      }
     ]
    },
    {
     "title": "Error log count for DV01 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-dv01-account-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-dv01-account-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests DV01",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-dv01-account\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-dv01-account\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-dv01-account\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-dv01-account\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-dv01-account\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-dv01-account\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "DV01 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-dv01-account\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-dv01-account-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "DV01 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-account.*\"}[5m])"
      }
     ]
    },
    {
     "title": "DV01 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-account.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap DV01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap DV01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-dv01-account\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage DV01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-dv01-account-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-dv01-account\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum DV01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-dv01-account-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-dv01-account-lookup\"}"
      }
     ]
    },
    {
     "title": "DV01 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-account.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-accoun.*\"}"
      }
     ]
    },
    {
     "title": "DV01 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-account.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dv01-account.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in DV01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-dv01-account\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "DP01",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-dp01-product\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-dp01-product\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for DP01",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-dp01-product\"}))"
      }
     ]
    },
    {
     "title": "Error log count for DP01 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-dp01-product-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-dp01-product-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests DP01",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-dp01-product\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-dp01-product\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-dp01-product\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-dp01-product\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-dp01-product\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-dp01-product\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "DP01 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-dp01-product\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-dp01-product-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "DP01 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}[5m])"
      }
     ]
    },
    {
     "title": "DP01 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap DP01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap DP01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-dp01-product\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage DP01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-dp01-product-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-dp01-product\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum DP01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-dp01-product-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-dp01-product-lookup\"}"
      }
     ]
    },
    {
     "title": "DP01 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}"
      }
     ]
    },
    {
     "title": "DP01 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-dp01-product.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in DP01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-dp01-product\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "BS95",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-bs95-product\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-bs95-product\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for BS95",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs95-product\"}))"
      }
     ]
    },
    {
     "title": "Error log count for BS95Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs95-product-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-bs95-product-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests BS95",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-bs95-product\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs95-product\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs95-product\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs95-product\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs95-product\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-bs95-product\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "BS95 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs95-product\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs95-product-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "BS95 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}[5m])"
      }
     ]
    },
    {
     "title": "BS95 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS95 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS95 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs95-product\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS95 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs95-product-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs95-product\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS95 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs95-product-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs95-product-lookup\"}"
      }
     ]
    },
    {
     "title": "BS95 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}"
      }
     ]
    },
    {
     "title": "BS95 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs95-product.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in BS95",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-bs95-product\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "BS01",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-bs01-corporate-information\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-bs01-corporate-information\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for BS01 ",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs01-corporate-information\"}))"
      }
     ]
    },
    {
     "title": "Error log count for BS01 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests BS01",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-bs01-corporate-information\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs01-corporate-information\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs01-corporate-information\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs01-corporate-information\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs01-corporate-information\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-bs01-corporate-information\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "BS01 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs01-corporate-information\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs01-corporate-information-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "BS01 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}[5m])"
      }
     ]
    },
    {
     "title": "BS01 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS01Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs01-corporate-information\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs01-corporate-information\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS01 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs01-corporate-information-lookup\"}"
      }
     ]
    },
    {
     "title": "BS01 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}"
      }
     ]
    },
    {
     "title": "BS01 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs01-corporate-information.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in BS01",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-bs01-corporate-information\"}"
      }
     ]
    }
   ]
  }
 ]
}