{
 "title": "TSB-ODS-LOANS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PR01",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records Consumed from Kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-loan-pr\"}"
      }
     ]
    },
    {
     "title": "Average records per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processLoansStream_time_pr01_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}/tsbods_processLoansStream_time_pr01_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"})"
      }
     ]
    },
    {
     "title": "Error Log Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
      }
     ]
    },
    {
     "title": "In And Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_pr01_loans_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_pr01_loans_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PR06",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records Consumed from Kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-loan-pr06\"}"
      }
     ]
    },
    {
     "title": "Average records per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_PR06_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr06\"}/tsbods_processTransactionsStream_time_PR06_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr06\"})"
      }
     ]
    },
    {
     "title": "Error Log Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr06\"}))"
      }
     ]
    },
    {
     "title": "In And Out",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_loans_pr06_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr06\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_loans_pr06_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr06\"}))"
      }
     ]
    }
   ]
  }
 ]
}