{
 "title": "TSB ODS SUB API (CLI, COP)",
 "time": { "from": "2022-03-23T11:44:06.790Z", "to": "2022-03-23T11:58:00.613Z" },
 "panels": [
  {
   "title": "CLI Customer API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for Rest Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Error log count for Lookup Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cli-customer-search-lookup\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-api-cli-customer-search\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "Number of Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-api-cli-customer-search-lookup\"}))"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cli-customer-search\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cli-customer-search-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "No of 4XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-api-cli-customer-search\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "COP Customer Search API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for Rest Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Error log count for Lookup Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cop-customer-search-lookup\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-api-cop-customer-search\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "Number of Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-api-cop-customer-search-lookup\"}))"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cop-customer-search\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cop-customer-search-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "No of 4XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-api-cop-customer-search\"}"
      }
     ]
    }
   ]
  }
 ]
}