{
 "title": "TSB-ODS-SYS-API-1",
 "time": { "from": "2021-04-19T10:27:01.420Z", "to": "2021-04-19T10:37:01.420Z" },
 "panels": [
  {
   "title": "KC03",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc03-transaction\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-kc03-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC03Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 196 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc03-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC03Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 196 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 204 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests KC03",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 204 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-kc03-transaction\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 212 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc03-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc03-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 212 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc03-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc03-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 220 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-kc03-transaction\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "KC03 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 220 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc03-transaction\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc03-transaction-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "KC03 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 228 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "KC03 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 228 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 236 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC03 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 236 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 244 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC03 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 244 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 252 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc03-transaction\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC03 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 252 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc03-transaction-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc03-transaction\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC03 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 260 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC03 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 268 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      }
     ]
    },
    {
     "title": "KC03 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 268 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 276 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "KC13",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC13 Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC13Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests KC13",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 203 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-kc13-pending-transaction\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 211 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc13-pending-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc13-pending-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 211 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc13-pending-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc13-pending-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 219 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-kc13-pending-transaction\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "KC13 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 219 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc13-pending-transaction\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "KC13 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 227 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "KC13 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 227 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC13 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC13 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc13-pending-transaction\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC13 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC13 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC13 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 267 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}"
      }
     ]
    },
    {
     "title": "KC13 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 267 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc13-pending-transaction.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in KC13",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 275 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "KC43",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc43-transaction\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-kc43-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC43 Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc43-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC43 Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests KC43",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-kc43-transaction\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc43-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc43-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-kc43-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-kc43-transaction\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request KC03",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-kc43-transaction\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "KC43 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc43-transaction\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-kc43-transaction-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "KC03 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc43-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "KC43 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc43-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap KC43 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap KC43 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc43-transaction\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage KC43 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-kc43-transaction-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc43-transaction\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum KC43 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC43 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc43-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      }
     ]
    },
    {
     "title": "KC43 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc43-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in KC43",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "BS46",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 189 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for BS46 Transaction Type",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}))"
      }
     ]
    },
    {
     "title": "Error log count for BS46 Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in BS46 ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 205 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests BS46",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 205 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-bs46-transaction-type\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Time to process 200 success requests BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 213 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs46-transaction-type\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs46-transaction-type\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Time to process 5XX Error requests BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 213 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-bs46-transaction-type\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-bs46-transaction-type\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 221 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-bs46-transaction-type\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "BS46 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 221 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs46-transaction-type\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-bs46-transaction-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "BS46 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 229 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs46-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "BS46 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 229 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-kc03-transaction.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 237 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-type\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap BS46 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 237 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 245 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-type\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap BS46 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 245 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 253 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs46-transaction-type\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage BS46 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 253 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-bs46-transaction-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 261 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum BS46 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 261 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "BS46 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs46-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs46-transaction.*\"}"
      }
     ]
    },
    {
     "title": "BS46 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 269 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs46-transaction.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-bs46-transaction.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in BS46",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 277 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
      }
     ]
    }
   ]
  }
 ]
}