{
 "title": "TSB-ODS-SingleApplications-PR,IA,BS Tables",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "StaticTables-BS-DP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records Static-BS-DP Application Consumed from Kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-static-tables-bs-dp\"}"
      }
     ]
    },
    {
     "title": "Average records per second Static-BS-DP Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_bs09_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}/tsbods_processTransactionsStream_time_bs09_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"})"
      },
      {
       "expr": "(tsbods_processTransactionsStream_time_bs46_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}/tsbods_processTransactionsStream_time_bs46_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"})"
      },
      {
       "expr": "(tsbods_processStream_time_bs95_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}/tsbods_processStream_time_bs95_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"})"
      },
      {
       "expr": "(tsbods_processStream_time_bs01_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}/tsbods_processStream_time_bs01_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"})"
      },
      {
       "expr": "(tsbods_processStream_time_dp01_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}/tsbods_processStream_time_dp01_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for static-BS-DP Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      }
     ]
    },
    {
     "title": "static-BS-DP  Records  In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_bs09_transactions_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_dp01_product_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_bs01_corporateInformation_in_total {namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_bs46_transactonTypes_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_bs95_product_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_bs09_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_bs01_corporateInformation_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_dp01_product_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_bs46_transactonTypes_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_bs95_product_out_total {namespace=\"ods\",job=\"tsb-ods-cdc-static-tables-bs-dp\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "IA33",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records IA33 Application Consumed from Kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"ttsb-ods-cdc-virtual-correspondance-ia\"}"
      }
     ]
    },
    {
     "title": "Average Records Per Second IA33 Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_ia33_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-virtual-correspondance-ia\"}/tsbods_processTransactionsStream_time_ia33_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-virtual-correspondance-ia\"})"
      }
     ]
    },
    {
     "title": "Error log Count for IA33 Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-virtual-correspondance-ia\"}))"
      }
     ]
    },
    {
     "title": "IA33 Records In and Out Of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_ia33_transactions_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-virtual-correspondance-ia\"}))"
      }
     ]
    }
   ]
  },
  { "title": "Loan-PR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Records Loan PR Application consumed from Kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-loan-pr\"}"
    }
   ]
  },
  {
   "title": "Average records per second Loan PR Application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processLoansStream_time_pr42_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}/tsbods_processLoansStream_time_pr42_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"})"
    },
    {
     "expr": "(tsbods_processLoansStream_time_pr01_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}/tsbods_processLoansStream_time_pr01_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"})"
    }
   ]
  },
  {
   "title": "Error Log Count Loan PR Application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
    }
   ]
  },
  {
   "title": "Loan PR Records In and Out Of Application",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_pr01_loans_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_pr01_loans_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_pr42_loans_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_pr42_loans_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr\"}))"
    }
   ]
  }
 ]
}