{
 "title": "TSB-ODS-API-Ingress",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ingress Pod Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\",namespace=\"ods\",pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"})"
    }
   ]
  },
  {
   "title": "process_requests_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_ingress_controller_nginx_process_requests_total{namespace=\"ods\",controller_pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"}"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{namespace=\"ods\",pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"})"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count({controller_pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\",controller_namespace=\"ods\"} == 0)"
    }
   ]
  },
  {
   "title": "Avg CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{namespace=\"ods\",controller_pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"}[2m]))"
    }
   ]
  },
  {
   "title": "Avg Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{namespace=\"ods\",controller_pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"})"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\",controller_class=~\"nginx\",controller_namespace=\"ods\"}[2m]))"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{namespace=\"ods\"}) by (host) - time()"
    }
   ]
  }
 ]
}