{
 "title": "TSB-ODS-SYS-API-3",
 "time": { "from": "2021-03-03T18:14:39.832Z", "to": "2021-06-06T19:33:39.064Z" },
 "panels": [
  {
   "title": "PE09",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe09-addresses\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe09-addresses\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE09",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe09-addresses\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE09 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe09-addresses-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-pe09-addresses-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE09",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe09-addresses\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe09-addresses\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe09-addresses\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe09-addresses\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe09-addresses\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe09-addresses\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE09 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe09-addresses\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe09-addresses-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE09 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE09 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE09 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE09 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe09-addresses\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE09 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe09-addresses-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe09-addresses\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE09 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe09-addresses-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe09-addresses-lookup\"}"
      }
     ]
    },
    {
     "title": "PE09 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}"
      }
     ]
    },
    {
     "title": "PE09 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe09-addresses.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE09",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe09-addresses\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PE11",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe11-customer\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe11-customer\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE11",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe11-customer\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE11 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe11-customer-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-pe11-customer-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE11",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe11-customer\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe11-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe11-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe11-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe11-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe11-customer\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE11 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe11-customer\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe11-customer-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE11 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE11 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE11 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE11 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe11-customer\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE11 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe11-customer-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe11-customer\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE11 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe11-customer-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe11-customer-lookup\"}"
      }
     ]
    },
    {
     "title": "PE11 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}"
      }
     ]
    },
    {
     "title": "PE11 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe11-customer.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE11",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe11-customer\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PE17",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE17",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE17 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE17",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe17-customer-addresses-link\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE17 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe17-customer-addresses-link\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE17 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE17 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE17 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE17 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe17-customer-addresses-link\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE17 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE17 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link-lookup\"}"
      }
     ]
    },
    {
     "title": "PE17 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}"
      }
     ]
    },
    {
     "title": "PE17 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe17-customer-addresses-link.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE17",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe17-customer-addresses-link\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PEA6",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pea6-addresses-history\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pea6-addresses-history\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PEA6",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pea6-addresses-history\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PEA6 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PEA6",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pea6-addresses-history\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pea6-addresses-history\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pea6-addresses-history\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pea6-addresses-history\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pea6-addresses-history\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pea6-addresses-history\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PEA6 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pea6-addresses-history\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pea6-addresses-history-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PEA6 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PEA6 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PEA6 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PEA6 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pea6-addresses-history\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PEA6 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pea6-addresses-history\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PEA6 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pea6-addresses-history-lookup\"}"
      }
     ]
    },
    {
     "title": "PEA6 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}"
      }
     ]
    },
    {
     "title": "PEA6 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pea6-addresses-history.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PEA6",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pea6-addresses-history\"}"
      }
     ]
    }
   ]
  }
 ]
}