{
 "title": "TSB-ODS-CSS-tables",
 "time": { "from": "2021-12-07T00:50:21.595Z", "to": "2021-12-07T12:50:21.595Z" },
 "panels": [
  { "title": "MG30", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Records mg30 Ingestors consumed from kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-mg30\"}"
    }
   ]
  },
  {
   "title": "Total Records MG30 Records consumed from kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-mortgages-mg30\"}"
    }
   ]
  },
  {
   "title": "Average number of records consumed MG30  ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}"
    }
   ]
  },
  {
   "title": "Average records per second Mg30 Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processTransactionsStream_time_mg30_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg30\"}/tsbods_processTransactionsStream_time_mg30_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg30\"})"
    }
   ]
  },
  {
   "title": "Error Log Count for MG30 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}))"
    }
   ]
  },
  {
   "title": "Error Log count for MG30 Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg30\"}))"
    }
   ]
  },
  {
   "title": "ta62 Records ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_pr30_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_pr30_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}))"
    }
   ]
  },
  {
   "title": "MG30 consumer  Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) ( tsb_ods_mg30_transactions_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg30\"}))"
    },
    {
     "expr": "(sum by (job, namespace) ( tsb_ods_mg30_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg30\"}))"
    }
   ]
  },
  {
   "title": "PR02",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records PR02 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pr-02-headless-service\"}"
      }
     ]
    },
    {
     "title": "Total Records PR02 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-loan-pr02\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed PR02 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pr-02-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PR02 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_pr02_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr02\"}/tsbods_processTransactionsStream_time_pr02_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr02\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for PR02 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pr-02-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for Pr02 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr02\"}))"
      }
     ]
    },
    {
     "title": "Pr02 Records ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pr02_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pr-02-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pr02_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pr-02-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Pr02 consumer  Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_pr02_loans_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr02\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_pr02_loans_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-loan-pr02\"}))"
      }
     ]
    }
   ]
  },
  { "title": "TA62", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Total Records Ta62 Ingestors consumed from kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-ta62\"}"
    }
   ]
  },
  {
   "title": "Total Records TA62 Records consumed from kafka",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-cards-ta62\"}"
    }
   ]
  },
  {
   "title": "Average number of records consumed TA62ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}"
    }
   ]
  },
  {
   "title": "Average records per second TA62 Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processTransactionsStream_time_ta62_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta62\"}/tsbods_processTransactionsStream_time_ta62_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta62\"})"
    }
   ]
  },
  {
   "title": "Error Log Count for TA62 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
    }
   ]
  },
  {
   "title": "Error Log count for TA62 Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta62\"}))"
    }
   ]
  },
  {
   "title": "ta62 Records ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_ta62_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_ta62_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
    }
   ]
  },
  {
   "title": "TA62 consumer  Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_ta62_transactions_in_total {namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta62\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_ta62_transactions_out_total {namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta62\"}))"
    }
   ]
  }
 ]
}