{
 "title": "TSB-ODS-SYS-API-Ingress",
 "time": { "from": "2021-03-03T18:14:39.832Z", "to": "2021-06-06T19:33:39.064Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingress Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of Pods Running",
     "type": "graph",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_ready{condition=\"true\",namespace=\"$namespace\",pod=~\"tsb-ods-sys-api-ingress-nginx-controller.*\"})"
      }
     ]
    },
    {
     "title": "Controller Connections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
      }
     ]
    },
    {
     "title": "Controller Success Rate (non-4|5xx responses)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m]))"
      }
     ]
    },
    {
     "title": "Config Reloads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Last Config Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_namespace=~\"$namespace\"} == 0)"
      }
     ]
    },
    {
     "title": "Ingress Request Volume",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Ingress Success Rate (non-4|5xx responses)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Average Memory Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
       "legendFormat": "nginx"
      }
     ]
    },
    {
     "title": "Average CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
       "legendFormat": "nginx"
      }
     ]
    },
    {
     "title": "Ingress Percentile Response Times and Transfer Rates",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
       "legendFormat": "{{ ingress }}"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
       "legendFormat": "{{ ingress }}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
       "legendFormat": "{{ destination_service }}"
      },
      {
       "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      },
      {
       "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
       "legendFormat": "{{ ingress }}"
      }
     ]
    },
    {
     "title": "Ingress Certificate Expiry",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{kubernetes_pod_name=~\"$controller\",namespace=~\"$namespace\",ingress=~\"$ingress\"}) by (host) - time()",
       "legendFormat": "{{ host }}"
      }
     ]
    }
   ]
  }
 ]
}