{
 "title": "TSB-ODS-Performance-Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "PE06 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records  PE06 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe06\"}"
      }
     ]
    },
    {
     "title": "Total Records PE06 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE06 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processCustomerContractStream_time_pe06_seconds_count{ job=\"tsb-ods-cdc-customer-pe06\", namespace=\"ods\"}/tsbods_processCustomerContractStream_time_pe06_seconds_count{job=\"tsb-ods-cdc-customer-pe06\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE06)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE06  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe06_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe06_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}))"
      }
     ]
    },
    {
     "title": "PE06 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_customercontract_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe06\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_customercontract_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe06\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE06 transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe06\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE06  ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE09 Applications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records  PE09 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-addresses-pe09\"}"
      }
     ]
    },
    {
     "title": "Total Records PE09ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-09-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE09 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processRequestStream_time_pe09_seconds_count{ job=\"tsb-ods-cdc-addresses-pe09\", namespace=\"ods\"}/tsbods_processRequestStream_time_pe09_seconds_sum{job=\"tsb-ods-cdc-addresses-pe09\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE09)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-06-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE09 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_addresses_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-addresses-pe09\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_addresses_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-addresses-pe09\"}))"
      }
     ]
    },
    {
     "title": "PE09  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe09_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-09-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe09_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-09-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE09 transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-addresses-pe09\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE09  ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-09-headless-service\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE10 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records PE10 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}"
      }
     ]
    },
    {
     "title": "Total Records PE10 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE10)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE10 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processStream_time_pe10_seconds_count{ job=\"tsb-ods-cdc-business-customer-pe10\", namespace=\"ods\"}/tsbods_processStream_time_pe10_seconds_sum{job=\"tsb-ods-cdc-business-customer-pe10\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "PE10  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe10_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe10_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}))"
      }
     ]
    },
    {
     "title": "PE10 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_businessCustomer_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-business-customer-pe10\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_businessCustomer_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-business-customer-pe10\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE10ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-10-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE10 transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-business-customer-pe10\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE11 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records PE11 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-11-headless-service\"}"
      }
     ]
    },
    {
     "title": "Total Records  PE16 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe16\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE11 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processRequestStream_time_pe11_seconds_count{ job=\"tsb-ods-cdc-customer-pe11\", namespace=\"ods\"}/tsbods_processRequestStream_time_pe11_seconds_sum{job=\"tsb-ods-cdc-customer-pe11\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE11)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-11-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE11 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_customer_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe11\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_customer_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe11\"}))"
      }
     ]
    },
    {
     "title": "PE11  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe11_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-11-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe11_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-11-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE11  ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-11-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE11  transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe11\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE16 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records  PE11 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe11\"}"
      }
     ]
    },
    {
     "title": "Total Records PE16 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-16-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE16 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processRequestStream_time_pe16_seconds_count{ job=\"tsb-ods-cdc-customer-pe16\", namespace=\"ods\"}/tsbods_processRequestStream_time_pe16_seconds_sum{job=\"tsb-ods-cdc-customer-pe16\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE16)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-16-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE16 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_customercontract_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe16\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_customercontract_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe16\"}))"
      }
     ]
    },
    {
     "title": "PE16  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe16_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-16-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe16_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-16-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE16  transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe16\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE16  ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-16-headless-service\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE17 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records  PE17 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-customer-address-pe17\"}"
      }
     ]
    },
    {
     "title": "Total Records PE17 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-17-headless-service\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE17 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processRequestStream_time_pe17_seconds_count{ job=\"tsb-ods-cdc-customer-address-pe17\", namespace=\"ods\"}/tsbods_processRequestStream_time_pe17_seconds_sum{job=\"tsb-ods-cdc-customer-address-pe17\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE17)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-17-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE17 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_in_customerAddress_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-address-pe17\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_customerAddress_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-address-pe17\"}))"
      }
     ]
    },
    {
     "title": "PE17  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe17_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-17-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe17_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-17-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE17 transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-customer-address-pe17\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE17 ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-17-headless-service\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "PE34 Application",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records PE34 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-pe-34-headless-service\"}"
      }
     ]
    },
    {
     "title": "Total Records  PE34 transactions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe34\"}"
      }
     ]
    },
    {
     "title": "Average records per second PE34 Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processRequestStream_time_pe34_seconds_count{ job=\"tsb-ods-cdc-customer-pe34\", namespace=\"ods\"}/tsbods_processRequestStream_time_pe34_seconds_sum{job=\"tsb-ods-cdc-customer-pe34\", namespace=\"ods\"})"
      }
     ]
    },
    {
     "title": "Average number of records consumed (PE34)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-34-headless-service\"}"
      }
     ]
    },
    {
     "title": "PE34 Transaction Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_customerContact_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe34\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_out_customerContact_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe34\"}))"
      }
     ]
    },
    {
     "title": "PE34  Ingestor Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pe34_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-34-headless-service\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pe34_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-34-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for  PE34  ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-pe-34-headless-service\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE34  transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-customer-pe34\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "ODS Pod Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ODS Applications Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=~\"tsb-ods.*\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{statefulset=~\"tsb-ods.*\",namespace=\"ods\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance testing related metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_used_bytes heap transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=~\"tsb-ods-cdc.*\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\", job=~\".*headless-service.*\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes nonheap ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",  job=~\".*tsb-ods-pr-ingest.*\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes nonheap transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\", job=~\".*transaction.*\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{namespace=\"ods\",job=~\".*tsb-ods-pr-ingest.*\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\", job=~\".*tsb-ods-pr-ingest.*\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=~\".*tsb-ods-cdc.*\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=~\".*tsb-ods-cdc.*\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{namespace=\"ods\", job=~\".*tsb-ods-pr-ingest.*\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=~\".*tsb-ods-cdc-transaction.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "producer_metrics_request_rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "producer_metrics_request_rate{job=~\".*tsb-ods-pr-ingest.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Kafka consumer commit rate trasaction",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_commit_rate_commits {job=~\".*tsb-ods-cdc.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "producer_metrics_record_send_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "producer_metrics_record_send_total{job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Kafka consumer commit rate ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_commit_rate_commits {job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "kafka_consumer_records_consumed_total_records_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "consumer_metrics_response_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_metrics_response_total{namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "consumer_metrics_request_rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_metrics_request_rate{ job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    }
   ]
  }
 ]
}