{
 "title": "TSB ODS SUB API (CLI,COP) - Reactive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "COP Customer API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cop-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-api-cop-customer-search\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "No of 4XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{method=\"POST\",status=~\"4.*\",job=\"tsb-ods-api-cop-customer-search\"})"
      }
     ]
    },
    {
     "title": "Error Log count for Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cop-customer-search\"}))"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-api-cop-customer-search\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-api-cop-customer-search\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-api-cop-customer-search\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-api-cop-customer-search\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-api-cop-customer-search\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cop-customer-search\",namespace=\"ods\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "CLI Customer API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-api-cli-customer-search\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-api-cli-customer-search\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "No of 4XX Error Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{method=\"POST\",status=~\"4.*\",job=\"tsb-ods-api-cli-customer-search\"})"
      }
     ]
    },
    {
     "title": "Error Log count for Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-api-cli-customer-search\"}))"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-api-cli-customer-search\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-api-cli-customer-search\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-api-cli-customer-search\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-api-cli-customer-search\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-api-cli-customer-search\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-api-cli-customer-search\",namespace=\"ods\"}"
      },
      {}
     ]
    }
   ]
  }
 ]
}