{
 "title": "TSB-ODS-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "BS46 Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime BS46 Transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}"
    }
   ]
  },
  {
   "title": "Start time BS46 ingestors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}*1000"
    }
   ]
  },
  {
   "title": "Start time BS46 transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime BS46 ingestor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}"
    }
   ]
  },
  {
   "title": "Total Records BS46 Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-cdc-transaction-bs46\"}"
    }
   ]
  },
  {
   "title": "Total Records BS46 Ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}"
    }
   ]
  },
  {
   "title": "Average number of records consumed (BS46)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}"
    }
   ]
  },
  {
   "title": "Average records per second BS46 Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processTransactionsStream_time_bs46_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}/tsbods_processTransactionsStream_time_bs46_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"})"
    }
   ]
  },
  {
   "title": "Error Log count for BS46 transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}))"
    }
   ]
  },
  {
   "title": "Error Log Count for BS46 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}))"
    }
   ]
  },
  {
   "title": "BS46 Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_bs46_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_bs46_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-bs-46-headless-service\"}))"
    }
   ]
  },
  {
   "title": "BS46 transaction  Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_in_transactonTypes_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_out_transactonTypes_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-bs46\"}))"
    }
   ]
  },
  { "title": "KC03 Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Uptime KC03 ingestor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}"
    }
   ]
  },
  {
   "title": "Uptime KC03 Transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}"
    }
   ]
  },
  {
   "title": "Start time KC03 transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 49 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}*1000"
    }
   ]
  },
  {
   "title": "Start time KC03 ingestors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 49 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}*1000"
    }
   ]
  },
  {
   "title": "Total Records KC03 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}"
    }
   ]
  },
  {
   "title": "Total Records KC03 transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-cdc-transaction-kc03\"}"
    }
   ]
  },
  {
   "title": "Average records per second KC03 Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processTransactionsStream_time_kc03_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}/tsbods_processTransactionsStream_time_kc03_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"})"
    }
   ]
  },
  {
   "title": "Average number of records consumed (KC03)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}"
    }
   ]
  },
  {
   "title": "KC03 Ingestor Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_kc03_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_kc03_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}))"
    }
   ]
  },
  {
   "title": "KC03 Transaction Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc03_transactions_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc03_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}))"
    }
   ]
  },
  {
   "title": "Error log count for KC03 ingestor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-03-headless-service\"}))"
    }
   ]
  },
  {
   "title": "Error log count for KC03 transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc03\"}))"
    }
   ]
  },
  { "title": "KC43 Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Uptime KC43 ingestor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 87 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}"
    }
   ]
  },
  {
   "title": "Uptime KC43 Transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 87 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}"
    }
   ]
  },
  {
   "title": "Start time KC43 ingestors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 92 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}*1000"
    }
   ]
  },
  {
   "title": "Start time KC43 transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 92 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}*1000"
    }
   ]
  },
  {
   "title": "Total Records KC43 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}"
    }
   ]
  },
  {
   "title": "Total Records KC43 transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-cdc-transaction-kc43\"}"
    }
   ]
  },
  {
   "title": "Average number of records consumed (KC43)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}"
    }
   ]
  },
  {
   "title": "Average records per second KC43 Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_processTransactionsStream_time_kc43_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}/tsbods_processTransactionsStream_time_kc43_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"})"
    }
   ]
  },
  {
   "title": "Error log count for KC43 transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}))"
    }
   ]
  },
  {
   "title": "Error log count for KC43 ingestor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}))"
    }
   ]
  },
  {
   "title": "KC43 Transaction Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc43_transacton_history_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc43_transacton_history_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc43\"}))"
    }
   ]
  },
  {
   "title": "KC43 Ingestor Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_kc43_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_kc43_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}))"
    }
   ]
  },
  { "title": "KC13 Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Start time KC13 transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 130 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"}*1000"
    }
   ]
  },
  {
   "title": "Uptime KC13 Transaction",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 130 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"}"
    }
   ]
  },
  {
   "title": "Uptime KC13 ingestor",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 135 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}"
    }
   ]
  },
  {
   "title": "Start time KC13 ingestors",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 135 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}*1000"
    }
   ]
  },
  {
   "title": "Total Records KC13 ingestors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}"
    }
   ]
  },
  {
   "title": "Total Records KC13 transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\", job=\"tsb-ods-cdc-pending-transaction-kc13\"}"
    }
   ]
  },
  {
   "title": "Average number of records consumed (KC13)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consumer_fetch_manager_metrics_records_consumed_rate {namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}"
    }
   ]
  },
  {
   "title": "Average records per second KC13 Transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(tsbods_pendingTransactionsStream_time_kc13_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"}/tsbods_pendingTransactionsStream_time_kc13_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"})"
    }
   ]
  },
  {
   "title": "KC13 Ingestor Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (records_in_total_kc13_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (records_out_total_kc13_total{namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-43-headless-service\"}))"
    }
   ]
  },
  {
   "title": "KC13 Transaction Records",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc13_pending_transactions_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"}))"
    },
    {
     "expr": "(sum by (job, namespace) (tsb_ods_kc13_pending_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-transaction-kc13\"}))"
    }
   ]
  },
  {
   "title": "Error log count for KC13 ingestor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-pr-ingest-kc-13-headless-service\"}))"
    }
   ]
  },
  {
   "title": "Error log count for KC13 transaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-pending-transaction-kc13\"}))"
    }
   ]
  },
  {
   "title": "ODS Pod Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 },
   "collapsed": true,
   "panels": [
    {
     "title": "ODS Applications Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=~\"tsb-ods.*\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_statefulset_status_replicas_ready{statefulset=~\"tsb-ods.*\",namespace=\"ods\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance testing related metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 173 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_used_bytes heap transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=~\"tsb-ods-cdc.*\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\", job=~\".*headless-service.*\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes nonheap ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",  job=~\".*tsb-ods-pr-ingest.*\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes nonheap transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\", job=~\".*transaction.*\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{namespace=\"ods\",job=~\".*tsb-ods-pr-ingest.*\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\", job=~\".*tsb-ods-pr-ingest.*\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=~\".*tsb-ods-cdc.*\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=~\".*tsb-ods-cdc.*\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{namespace=\"ods\", job=~\".*tsb-ods-pr-ingest.*\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=~\".*tsb-ods-cdc-transaction.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "producer_metrics_request_rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "producer_metrics_request_rate{job=~\".*tsb-ods-pr-ingest.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Kafka consumer commit rate trasaction",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_commit_rate_commits {job=~\".*tsb-ods-cdc.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "producer_metrics_record_send_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "producer_metrics_record_send_total{job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "Kafka consumer commit rate ingestor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_commit_rate_commits {job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "kafka_consumer_records_consumed_total_records_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{ namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "consumer_metrics_response_total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_metrics_response_total{namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "consumer_metrics_request_rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "consumer_metrics_request_rate{ job=~\".*tsb-ods-pr.*\", namespace=\"ods\"}"
      }
     ]
    }
   ]
  }
 ]
}