{
 "title": "TSB-ODS-SYS-API",
 "time": { "from": "2021-04-19T10:27:01.420Z", "to": "2021-04-19T10:37:01.420Z" },
 "panels": [
  {
   "title": "KC43",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "KC43 Transaction UPTIME",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    },
    {
     "title": "KC43 Transaction Lookup Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC43 Transaction Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    },
    {
     "title": "KC43 Transaction Lookup Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    },
    {
     "title": "Number Of 500 Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=\"500\",job=\"tsb-ods-sys-api-kc43-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC43 Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc43-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC43 Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of records consumed KC43 Response",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC43 Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc43-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "Number of Requests KC43",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tsb_ods_sys_api_kc03_in_total{job=\"tsb-ods-sys-api-kc43-transaction\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "KC13",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "KC13 Transaction UPTIME",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    },
    {
     "title": "KC13 Transaction Lookup Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC13 Transaction Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    },
    {
     "title": "KC13 Transaction Lookup Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    },
    {
     "title": "Number Of 500 Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=\"500\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC13 Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc13-pending-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC13Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of records consumed KC13 Response",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC13 Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc13-pending-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "Number of Requests KC13",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tsb_ods_sys_api_kc03_in_total{job=\"tsb-ods-sys-api-kc13-pending-transaction\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "KC03",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "KC03Transaction UPTIME",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    },
    {
     "title": "KC03Transaction Lookup Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "KC03Transaction Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    },
    {
     "title": "KC03 Transaction Lookup Start Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    },
    {
     "title": "Number Of 500 Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=\"500\",job=\"tsb-ods-sys-api-kc03-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for KC03Transaction",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc03-transaction\"}))"
      }
     ]
    },
    {
     "title": "Error log count for KC03Transaction Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of records consumed KC03Response",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    },
    {
     "title": "No of Records Consumed in KC03 Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-kc03-transaction-lookup\"}"
      }
     ]
    },
    {
     "title": "Number of Requests KC03",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tsb_ods_sys_api_kc03_in_total{job=\"tsb-ods-sys-api-kc03-transaction\"}"
      }
     ]
    }
   ]
  },
  { "title": "BS46", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "BS46 Transaction Type UPTIME",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
    }
   ]
  },
  {
   "title": "BS46 Transaction Lookup Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds {job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}"
    }
   ]
  },
  {
   "title": "BS46 Transaction Type Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
    }
   ]
  },
  {
   "title": "BS46 Transaction Lookup Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}"
    }
   ]
  },
  {
   "title": "No of 200 status code Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
    }
   ]
  },
  {
   "title": "Number Of 500 Error Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=\"500\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}))"
    }
   ]
  },
  {
   "title": "Error Log count for BS46 Transaction Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs46-transaction-type\"}))"
    }
   ]
  },
  {
   "title": "Error log count for BS46 Transaction Lookup",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}))"
    }
   ]
  },
  {
   "title": "No of records consumed BS46 Response",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
    }
   ]
  },
  {
   "title": "No of Records Consumed in BS46 Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_records_consumed_total_records_total{job=\"tsb-ods-sys-api-bs46-transaction-lookup\"}"
    }
   ]
  },
  {
   "title": "Number of Requests BS46",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tsb_ods_sys_api_bs46_in_total{job=\"tsb-ods-sys-api-bs46-transaction-type\"}"
    }
   ]
  }
 ]
}