{
 "title": "TSB-ODS-SYS-API-4",
 "time": { "from": "2021-03-03T18:14:39.832Z", "to": "2021-06-06T19:33:39.064Z" },
 "panels": [
  {
   "title": "PE34",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe34-customer-contact\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe34-customer-contact\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE34",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe34-customer-contact\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE34 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE34",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe34-customer-contact\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe34-customer-contact\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe34-customer-contact\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe34-customer-contact\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe34-customer-contact\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe34-customer-contact\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE34 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe34-customer-contact\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe34-customer-contact-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE34 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE34 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE34 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE34 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe34-customer-contact\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE34 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe34-customer-contact\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE34 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe34-customer-contact-lookup\"}"
      }
     ]
    },
    {
     "title": "PE34 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}"
      }
     ]
    },
    {
     "title": "PE34 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe34-customer-contact.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE34",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe34-customer-contact\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PE16",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe16-person-contract\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe16-person-contract\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE16",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe16-person-contract\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE16 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe16-person-contract-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-pe16-person-contract-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE16",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe16-person-contract\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe16-person-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe16-person-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe16-person-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe16-person-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe16-person-contract\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE16 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe16-person-contract\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe16-person-contract-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE16 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE16 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE16 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE16 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe16-person-contract\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE16 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe16-person-contract-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe16-person-contract\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE16 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe16-person-contract-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe16-person-contract-lookup\"}"
      }
     ]
    },
    {
     "title": "PE16 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}"
      }
     ]
    },
    {
     "title": "PE16 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe16-person-contract.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE16",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe16-person-contract\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PE10",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe10-business-customer\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe10-business-customer\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE10",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe10-business-customer\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE10 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe10-business-customer-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-pe10-business-customer-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE10",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe10-business-customer\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe10-business-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe10-business-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe10-business-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe10-business-customer\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe10-business-customer\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE10 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe10-business-customer\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe10-business-customer-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE10 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE10 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE10 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE10 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe10-business-customer\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE10 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe10-business-customer-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe10-business-customer\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE10 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe10-business-customer-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe10-business-customer-lookup\"}"
      }
     ]
    },
    {
     "title": "PE10 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}"
      }
     ]
    },
    {
     "title": "PE10 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe10-business-customer.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE10",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 273 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe10-business-customer\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "PE06",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "No of 200 status code Request",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{method=\"POST\",status=\"200\",job=\"tsb-ods-sys-api-pe06-contract\"}))"
      }
     ]
    },
    {
     "title": "Number Of 5XX Error Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_count{status=~\"5.*\",job=\"tsb-ods-sys-api-pe06-contract\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for PE06",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe06-contract\"}))"
      }
     ]
    },
    {
     "title": "Error log count for PE06 Lookup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",job=\"tsb-ods-sys-api-pe06-contract-lookup\"}))"
      }
     ]
    },
    {
     "title": "No of Records Consumed in PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (kafka_consumer_fetch_manager_records_consumed_total{job=\"tsb-ods-sys-api-pe06-contract-lookup\"}))"
      }
     ]
    },
    {
     "title": "Number of Requests PE06",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_server_requests_seconds_count{namespace=\"ods\",endpoint=\"web\", job=\"tsb-ods-sys-api-pe06-contract\",method=\"POST\"})"
      }
     ]
    },
    {
     "title": "Avg Process time for 200 Success in PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe06-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe06-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SUCCESS\", status=\"200\"}))"
      }
     ]
    },
    {
     "title": "Avg Process time for 5XX Error in PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (http_server_requests_seconds_sum{endpoint=\"web\", job=\"tsb-ods-sys-api-pe06-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}*1000))/(sum by (job, namespace) (http_server_requests_seconds_count{endpoint=\"web\", job=\"tsb-ods-sys-api-pe06-contract\", method=\"POST\", namespace=\"ods\", outcome=\"SERVER_ERROR\", status=~\"5.*\"}))"
      }
     ]
    },
    {
     "title": "Max time for Request PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 209 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(http_server_requests_seconds_max{job=\"tsb-ods-sys-api-pe06-contract\",method=\"POST\"})*1000"
      }
     ]
    },
    {
     "title": "PE06 Pod Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 209 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe06-contract\",namespace=\"ods\"}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{deployment=\"tsb-ods-sys-api-pe06-contract-lookup\",namespace=\"ods\"}"
      },
      {}
     ]
    },
    {
     "title": "PE06 Network Received Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_receive_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}[5m])"
      }
     ]
    },
    {
     "title": "PE06 Network Transmitted Bytes Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(container_network_transmit_bytes_total{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}[5m])"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes heap PE06 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 225 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract-lookup\",area=\"heap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes Non-heap PE06 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract-lookup\",area=\"nonheap\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe06-contract\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "process_cpu_usage PE06 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 241 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{job=\"tsb-ods-sys-api-pe06-contract-lookup\", namespace=\"ods\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe06-contract\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract\"}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_sum PE06 Lookup",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 249 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{namespace=\"ods\", job=\"tsb-ods-sys-api-pe06-contract-lookup\"}"
      },
      {
       "expr": "jvm_gc_pause_seconds_sum{namespace=\"ods\",job=\"tsb-ods-sys-api-pe06-contract-lookup\"}"
      }
     ]
    },
    {
     "title": "PE06 CPU Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 257 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}"
      }
     ]
    },
    {
     "title": "PE06 Memory Request & Limit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 257 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_resource_requests_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}"
      },
      {
       "expr": "kube_pod_container_resource_limits_memory_bytes{namespace=\"ods\",pod=~\"tsb-ods-sys-api-pe06-contract.*\"}"
      }
     ]
    },
    {
     "title": "No of 4XX Error in PE06",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{status=~\"4.*\",job=\"tsb-ods-sys-api-pe06-contract\"}"
      }
     ]
    }
   ]
  }
 ]
}