{
 "title": "TSB-ODS-New CSS Tables",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TA63",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records TA63 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-ta63\"}"
      }
     ]
    },
    {
     "title": "Total Records TA63 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-cards-ta63\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed TA63 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta63\"}"
      }
     ]
    },
    {
     "title": "Average records per second TA63 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_ta63_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta63\"}/tsbods_processTransactionsStream_time_ta63_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta63\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for TA63 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta63\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for TA63 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta63\"}))"
      }
     ]
    },
    {
     "title": "TA63 Records ingestors In and Out Of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_ta63_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta63\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pr30_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}))"
      }
     ]
    },
    {
     "title": "TA63 consumer  Records In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) ( tsb_ods_ta63_card_details_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta63\"}))"
      },
      {
       "expr": "(sum by (job, namespace) ( tsb_ods_ta63_card_details_out_total {namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta63\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "TA61",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records TA61 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-ta61\"}"
      }
     ]
    },
    {
     "title": "Total Records TA61 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-cards-ta61\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed TA61 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta61\"}"
      }
     ]
    },
    {
     "title": "Average records per second TA61 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_ta61_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta61\"}/tsbods_processTransactionsStream_time_ta61_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta61\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for TA61 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta61\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for TA61 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta61\"}))"
      }
     ]
    },
    {
     "title": "TA61 Records ingestors in and out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_ta61_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta61\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_pr30_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg30\"}))"
      }
     ]
    },
    {
     "title": "TA61 consumer  Records In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) ( tsb_ods_ta61_customer_in_total{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta61\"}))"
      },
      {
       "expr": "(sum by (job, namespace) ( tsb_ods_ta61_customer_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-cards-ta61\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "MG41",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records MG41 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-mg41\"}"
      }
     ]
    },
    {
     "title": "Total Records MG41 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\" tsb-ods-cdc-mortgages-mg41\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed MG41 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg41\"}"
      }
     ]
    },
    {
     "title": "Average records per second MG41 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_mg41_seconds_count{namespace=\"ods\",job=\" tsb-ods-cdc-mortgages-mg41\"}/tsbods_processTransactionsStream_time_mg41_seconds_sum{namespace=\"ods\",job=\" tsb-ods-cdc-mortgages-mg41\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for MG41 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg41\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for MG41 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\" tsb-ods-cdc-mortgages-mg41\"}))"
      }
     ]
    },
    {
     "title": "MG41 Records Ingestors In and Out Of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_mg41_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg41\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_ta62_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
      }
     ]
    },
    {
     "title": "MG41 consumer  Records In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg41_transactions_in_total {namespace=\"ods\",job=\" tsb-ods-cdc-mortgages-mg41\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg41_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg41\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "MG40",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records MG40 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-mg40\"}"
      }
     ]
    },
    {
     "title": "Total Records MG40 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-mortgages-mg40\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed MG40 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg40\"}"
      }
     ]
    },
    {
     "title": "Average records per second MG40 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_mg40obj_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg40\"}/tsbods_processTransactionsStream_time_mg40obj_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg40\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for MG40 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg40\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for MG40 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg40\"}))"
      }
     ]
    },
    {
     "title": "MG40 Records ingestors In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_pr30_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg40\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_ta62_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
      }
     ]
    },
    {
     "title": "MG40 consumer  Records In and Out Of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg40obj_transactions_in_total {namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg40\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg40obj_transactions_out_total{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg40\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "MG35",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Records MG35 Ingestors consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-ingestor-mg35\"}"
      }
     ]
    },
    {
     "title": "Total Records MG35 Records consumed from kafka",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_total{ namespace=\"ods\", job=\"tsb-ods-cdc-mortgages-mg35\"}"
      }
     ]
    },
    {
     "title": "Average number of records consumed MG35ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_consumer_fetch_manager_records_consumed_rate{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg35\"}"
      }
     ]
    },
    {
     "title": "Average records per second MG35 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(tsbods_processTransactionsStream_time_mg35_seconds_count{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg35\"}/tsbods_processTransactionsStream_time_mg35_seconds_sum{namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg35\"})"
      }
     ]
    },
    {
     "title": "Error Log Count for MG35 ingestors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg35\"}))"
      }
     ]
    },
    {
     "title": "Error Log count for MG35 Records",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (logback_events_total{level=\"error\",namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg35\"}))"
      }
     ]
    },
    {
     "title": "MG35 Records Ingestors In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (records_in_total_mg35_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-mg35\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (records_out_total_ta62_total{namespace=\"ods\",job=\"tsb-ods-cdc-ingestor-ta62\"}))"
      }
     ]
    },
    {
     "title": "MG35 consumer  Records In and Out of Application",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg35_transactions_in_total {namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg35\"}))"
      },
      {
       "expr": "(sum by (job, namespace) (tsb_ods_mg35_transactions_out_total {namespace=\"ods\",job=\"tsb-ods-cdc-mortgages-mg35\"}))"
      }
     ]
    }
   ]
  }
 ]
}