{
 "title": "ODS SUB API Gateway - AWS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Account Transaction API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/account/transactions\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Product Details API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/product/details\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Customer Details API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/details\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Customer Search API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/customer/search\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mortgage Transactions API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/mortgage/transactions\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Loan Transactions API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}"
      }
     ]
    },
    {
     "title": "Request count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_count_sample_count{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}\r\n"
      }
     ]
    },
    {
     "title": "5XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}"
      }
     ]
    },
    {
     "title": "Integration Latency Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_integration_latency_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}"
      }
     ]
    },
    {
     "title": "5XX Error Average",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_5_xxerror_average{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}"
      }
     ]
    },
    {
     "title": "4XX Error Sum",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "aws_apigateway_4_xxerror_sum{exported_job=\"aws_apigateway\", method=\"POST\", namespace=\"prometheus\",  resource=\"/ods/v1/aep/loan/transactions\"}"
      }
     ]
    }
   ]
  }
 ]
}