{
 "title": "SCA-CDC-Customer-Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of User Sessions record persisted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (total_records_of_user_sessions_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
     "legendFormat": "total_records_of_user_sessions"
    },
    {
     "expr": "sum by (application, namespace) (total_records_of_duplicate_user_sessions_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
     "legendFormat": "total_records_of_duplicate_user_sessions"
    },
    {
     "expr": "sum by (application, namespace) (total_records_of_invalid_user_sessions_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
     "legendFormat": "total_records_of_invalid_user_sessions_data"
    }
   ]
  },
  {
   "title": "Total number of Customer Cards records processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (total_records_of_retail_debit_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r\n\r",
     "legendFormat": "Retail_Debit_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_retail_credit_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Retail_Credit_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_business_debit_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Business_Debit_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_business_credit_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Business_Credit_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_cards_Without_Cust_Mapping_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Cards_Without_Numpersona"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_visa_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Visa_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_master_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Master_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_invalid_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Invalid_Cards"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_duplicate_cards_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Duplicate_Cards"
    }
   ]
  },
  {
   "title": "Total number of Devices records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (total_records_of_invalid_device_data_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r\n\r\n\r",
     "legendFormat": "Devices_Without_Enrollment_Type"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_devices_data_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Active_Devices"
    }
   ]
  },
  {
   "title": "Total number of Customer Contact records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (total_records_of_mobile_number_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Mobile_Number"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_phone_number_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Home_Phone_Number"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_duplicate_contact_data_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "Duplicate_Contact"
    }
   ]
  },
  {
   "title": "Total number of Users records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, namespace) (total_records_of_registered_users_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "registered_users"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_duplicate_user_data_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
     "legendFormat": "duplicate_users"
    },
    {
     "expr": "sum by (job, namespace) (total_records_of_invalid_users_data_total{job=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
     "legendFormat": "Invalid_Users"
    }
   ]
  }
 ]
}