{
 "title": "SCA CDC Ingestors",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total number of Session Banca records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_session_banca_total{application=\"tsb-sca-pr-ingest-tbbv-bs-session-banca\",input=\"SESSION_BANCA\",namespace=\"sca\"})",
     "legendFormat": "records_in_total_session_banca"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_session_banca_total{application=\"tsb-sca-pr-ingest-tbbv-bs-session-banca\",namespace=\"sca\"})",
     "legendFormat": "records_out_total_session_banca"
    }
   ]
  },
  {
   "title": "Total number of TA63 records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_ta63_total{application=\"tsb-sca-pr-ingest-ta63\",input=\"TA63\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_ta63_total{application=\"tsb-sca-pr-ingest-ta63\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of TA62 records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_ta62_total{application=\"tsb-sca-pr-ingest-ta62\",input=\"TA62\",namespace=\"sca\"})",
     "legendFormat": "tsb-sca-pr-ingest-ta62-IN "
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_ta62_total{application=\"tsb-sca-pr-ingest-ta62\",namespace=\"sca\"})",
     "legendFormat": "tsb-sca-pr-ingest-ta62-OUT"
    }
   ]
  },
  {
   "title": "Total number of TA61 records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_ta61_total{application=\"tsb-sca-pr-ingest-ta61\",input=\"TA61\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "\r\nsum by (application, namespace) (records_out_total_ta61_total{application=\"tsb-sca-pr-ingest-ta61\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of Enrollments records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_device_by_das_user_total{application=\"tsb-sca-pr-ingest-tbbv-bs-enrollments\",input=\"DEVICE_BY_DAS_USER\",namespace=\"sca\"})\r\n\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (record_out_total_device_by_das_user_total{application=\"tsb-sca-pr-ingest-tbbv-bs-enrollments\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of JoinCardCustomer records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_total_customer_card_details_total{application=\"tsb-sca-pr-join-cardcustomer\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Total number of Das User records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_total_users_by_das_user_total{application=\"tsb-sca-pr-ingest-das-users\",namespace=\"sca\"})\r",
     "legendFormat": "tsb-sca-pr-ingest-das-users"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_access_codes_total{application=\"tsb-sca-pr-ingest-das-users\",namespace=\"sca\"})",
     "legendFormat": "tsb-sca-pr-ingest-das-users-access-codes"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_credentials_total{application=\"tsb-sca-pr-ingest-das-users\",namespace=\"sca\"})",
     "legendFormat": "tsb-sca-pr-ingest-das-users-total-credentials"
    },
    {
     "expr": "sum by (application, namespace) (records_total_contracts_by_das_contract_total{application=\"tsb-sca-pr-ingest-das-users\",namespace=\"sca\"})",
     "legendFormat": "tsb-sca-pr-ingest-das-users-total-contracts"
    }
   ]
  },
  {
   "title": "Total number of Contratos records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_contract_total{application=\"tsb-sca-pr-ingest-tbbv-bs-contratos\",input=\"CONTRACT\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_contract_total{application=\"tsb-sca-pr-ingest-tbbv-bs-contratos\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of Usuarios records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_user_info_total{application=\"tsb-sca-pr-ingest-tbbv-bs-usuarios\",input=\"USER_INFO\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (record_out_total_user_info_total{application=\"tsb-sca-pr-ingest-tbbv-bs-usuarios\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of PE34 records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_pe34_total{application=\"tsb-sca-pr-ingest-pe34\",input=\"PE34\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "\r\nsum by (application, namespace) (records_out_total_pe34_total{application=\"tsb-sca-pr-ingest-pe34\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of Credentials records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_credentials_total{application=\"tsb-sca-pr-ingest-tbbv-bs-auth-data\",input=\"CREDENTIALS\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_credentials_total{application=\"tsb-sca-pr-ingest-tbbv-bs-auth-data\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of Access Codes records processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total_access_codes_total{application=\"tsb-sca-pr-ingest-tbbv-bs-codigos-acceso\",input=\"ACCESS_CODES\",namespace=\"sca\"})\r\r",
     "legendFormat": "{{application}}-IN"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total_access_codes_total{application=\"tsb-sca-pr-ingest-tbbv-bs-codigos-acceso\",namespace=\"sca\"})",
     "legendFormat": "{{application}}-OUT"
    }
   ]
  },
  {
   "title": "Total number of records processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (application, namespace) (records_in_total{application=~\"tsb-sca-pr-ingest-ta63|tsb-sca-pr-ingest-ta61|tsb-sca-pr-ingest-pe34|tsb-sca-pr-ingest-tbbv-bs-codigos-acceso|tsb-sca-pr-ingest-tbbv-bs-contratos|tsb-sca-pr-ingest-tbbv-bs-auth-data|tsb-sca-pr-ingest-tbbv-bs-usuarios|tsb-sca-pr-ingest-tbbv-bs-enrollments\",namespace=\"sca\"})",
     "legendFormat": "{{application}}"
    },
    {
     "expr": "sum by (application, namespace) (records_out_total{application=~\"tsb-sca-pr-ingest-ta63|tsb-sca-pr-ingest-ta61|tsb-sca-pr-ingest-pe34|tsb-sca-pr-ingest-tbbv-bs-codigos-acceso|tsb-sca-pr-ingest-tbbv-bs-contratos|tsb-sca-pr-ingest-tbbv-bs-auth-data|tsb-sca-pr-ingest-tbbv-bs-usuarios|tsb-sca-pr-ingest-tbbv-bs-enrollments\",namespace=\"sca\"})\r",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}