---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sca-cdc-customerdata-cm
  namespace: prometheus
data:
  CDCCustomerData.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 43,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 8,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (application, namespace) (total_records_of_invalid_device_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r\n\r\n\r",
              "interval": "",
              "legendFormat": "invalid_device",
              "refId": "A"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_active_devices{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "active_devices",
              "refId": "B"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_registered_user_with_biometric{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "registered_user_with_biometric",
              "refId": "C"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_registered_user_with_password{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
              "interval": "",
              "legendFormat": "registered_user_with_password",
              "refId": "D"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Total number of Devices record persisted",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (application, namespace) (total_records_of_retail_debit_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r\n\r",
              "interval": "",
              "legendFormat": "Retail_DC",
              "refId": "A"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_retail_credit_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Retail_CC",
              "refId": "B"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_business_debit_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Business_DC",
              "refId": "C"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_business_credit_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Business_CC",
              "refId": "D"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_cards_Without_Cust_Mapping_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Without_Cust_Mapping_Cards",
              "refId": "E"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_visa_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Visa_Cards",
              "refId": "F"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_master_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Master_Cards",
              "refId": "G"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_invalid_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Invalid_Cards",
              "refId": "H"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_duplicate_cards_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Duplicate_Cards",
              "refId": "I"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_active_retail_debit_cards{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Retail_DC_Active",
              "refId": "J"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_active_retail_credit_cards{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Retail_CC_Active",
              "refId": "K"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_active_business_debit_cards{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Business_DC_Active",
              "refId": "L"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_active_business_credit_cards{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
              "interval": "",
              "legendFormat": "Business_CC_Active",
              "refId": "M"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Total number of Customer Cards record persisted",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          },
          "hiddenSeries": false,
          "id": 6,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (application, namespace) (total_records_of_registered_users_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "registered_users",
              "refId": "A"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_duplicate_user_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "duplicate_users",
              "refId": "B"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_multiple_customers_mapped_to_same_user_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "multiple_customers_mapped_to_same_user",
              "refId": "C"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_multiple_users_mapped_to_same_customer_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r\n\r",
              "interval": "",
              "legendFormat": "multiple_users_mapped_to_same_customer",
              "refId": "D"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_invalid_users_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})",
              "interval": "",
              "legendFormat": "Invalid_Users",
              "refId": "E"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Total number of Users record persisted",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "Thanos",
          "fieldConfig": {
            "defaults": {
              "custom": {}
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 9
          },
          "hiddenSeries": false,
          "id": 4,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.2.1",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (application, namespace) (total_records_of_mobile_number_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Mobile_Number",
              "refId": "A"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_phone_number_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Phone_Number",
              "refId": "B"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_invalid_cards_mapped_to_same_customer_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Invalid_cards_mapped_to_same_customer",
              "refId": "C"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_duplicate_contact_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Duplicate_Contact",
              "refId": "D"
            },
            {
              "expr": "sum by (application, namespace) (total_records_of_invalid_contact_data_total{application=\"tsb-sca-cdc-customer-data\",namespace=\"sca\"})\r",
              "interval": "",
              "legendFormat": "Invalid_Contact",
              "refId": "E"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Total number of Customer Contact record persisted",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "schemaVersion": 26,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "SCA-CDC-Customer-Data",
      "uid": "SWdURhUMz",
      "version": 6
    }