{
 "title": "SCA Microservice Linear Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total SCA Authentication Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(auth_req_received_from_broadcom_total{job=\"tsb-sca-decision-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total authentication requests received"
    },
    {
     "expr": "sum(increase(total_authentication_decision_app_total{job=\"tsb-sca-decision-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total authentication decision returned as APP"
    },
    {
     "expr": "sum(increase(total_authentication_decision_OTP_total{job=\"tsb-sca-decision-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total authentication decision returned as OTP"
    },
    {
     "expr": "sum(increase(total_auth_req_failed_total{job=\"tsb-sca-decision-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total SCA Not Returned Response"
    }
   ]
  },
  {
   "title": "Total SCA Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(total_sca_requests_timedout_total{job=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of SCA requests timedout"
    },
    {
     "expr": "sum(increase(total_sca_customer_cancelled_requests_total{job=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of SCA customer cancelled requests"
    },
    {
     "expr": "sum(increase(total_sca_frauds_total{job=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of SCA Frauds"
    },
    {
     "expr": "sum(increase(total_sca_failures_total{job=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of SCA Failures"
    },
    {
     "expr": "sum(increase(total_sca_success_total{job=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of successful SCA requests"
    },
    {
     "expr": "sum(increase(total_broadcom_callback_failures_total{container=\"tsb-sca-app-responses-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "total_broadcom_callback_failures"
    }
   ]
  },
  {
   "title": "Total Push Notification Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(total_push_message_requests_received_total{container=\"tsb-sca-app-request-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "total_push_message_requests_received"
    },
    {
     "expr": "sum(increase(total_push_message_requests_success_total{container=\"tsb-sca-app-request-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "total_push_message_requests_success"
    },
    {
     "expr": "sum(increase(total_push_message_requests_failed_total{container=\"tsb-sca-app-request-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "total_push_message_requests_failed"
    }
   ]
  },
  {
   "title": "Total OTP Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(total_otp_requests_received_total{job=\"tsb-sca-send-otp-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of OTP requests received"
    },
    {
     "expr": "sum(increase(total_otp_requests_failed_to_send_imi_total{job=\"tsb-sca-send-otp-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of OTP requests failed to send to IMI"
    },
    {
     "expr": "sum(increase(total_fiserv_requests_failed_to_send_total{job=\"tsb-sca-fiserv-notify-topology\",namespace=\"sca\"}[90d]))",
     "legendFormat": "Total number of requests failed to send to Fiserv"
    }
   ]
  },
  {
   "title": "API Average Response time (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*transaction\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*transaction\"}[5m]))",
     "legendFormat": "Get Transaction API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*enrol-type\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*enrol-type\"}[5m]))",
     "legendFormat": "Enroll Type API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*stepup-auth-response\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*stepup-auth-response\"}[5m]))",
     "legendFormat": "Stepup Auth Response API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*validate-pwd\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*validate-pwd\"}[5m]))",
     "legendFormat": "Validate Pwd API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*auth-method\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*auth-method\"}[5m]))",
     "legendFormat": "Auth Method API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*init-app-auth\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*init-app-auth\"}[5m]))",
     "legendFormat": "Init App Auth API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*send-otp\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*send-otp\"}[5m]))",
     "legendFormat": "Sent OTP API Response Time"
    },
    {
     "expr": "sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace=\"sca\",uri=~\".*transactions-by-userid\"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace=\"sca\",uri=~\".*transactions-by-userid\"}[5m]))",
     "legendFormat": "Transaction By User ID API Response Time"
    }
   ]
  },
  {
   "title": "API Failure Rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*transaction\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*transaction\"}[5m]))) * 100",
     "legendFormat": "Get Transaction API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*enrol-type\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*enrol-type\"}[5m]))) * 100",
     "legendFormat": "Enroll Type API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*stepup-auth-response\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*stepup-auth-response\"}[5m]))) * 100",
     "legendFormat": "Stepup Auth Response API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*validate-pwd\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*validate-pwd\"}[5m]))) * 100",
     "legendFormat": "Validate Pwd API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*auth-method\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*auth-method\"}[5m]))) * 100",
     "legendFormat": "Auth Method API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*init-app-auth\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*init-app-auth\"}[5m]))) * 100",
     "legendFormat": "Init App Auth API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*send-otp\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*send-otp\"}[5m]))) * 100",
     "legendFormat": "Sent OTP API Failure Rate"
    },
    {
     "expr": "(sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",outcome!=\"SUCCESS\", uri=~\".*transactions-by-userid\"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\", uri=~\".*transactions-by-userid\"}[5m]))) * 100",
     "legendFormat": "Transaction By User ID API Failure Rate"
    }
   ]
  },
  {
   "title": "API Gateway Failure Rate (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by (namespace, job, routeId) (rate(gateway_requests_seconds_count{namespace=\"sca\",outcome!=\"SUCCESSFUL\"}[5m])) / sum by (namespace, job, routeId) (rate(gateway_requests_seconds_count{namespace=\"sca\"}[5m]))) * 100",
     "legendFormat": "{{routeId}} Failure Rate"
    }
   ]
  },
  {
   "title": "API Throughput (Requests per Second)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*transaction\"}[5m]))",
     "legendFormat": "Get Transaction API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*enrol-type\"}[5m]))",
     "legendFormat": "Enroll Type API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*stepup-auth-response\"}[5m]))",
     "legendFormat": "\t Stepup Auth Response API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*validate-pwd\"}[5m]))",
     "legendFormat": "Validate Pwd API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*auth-method\"}[5m]))",
     "legendFormat": "Auth Method API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*init-app-auth\"}[5m]))",
     "legendFormat": "Init App Auth API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*send-otp\"}[5m]))",
     "legendFormat": "Sent OTP API throughput"
    },
    {
     "expr": "sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace=\"sca\",uri=~\".*transactions-by-userid\"}[5m]))",
     "legendFormat": "Transaction By User ID API throughput"
    }
   ]
  },
  {
   "title": "Get Transactions By UserId API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\" ,job=\"tsb-sca-transaction-query-api\", uri=~\".*transactions-by-userid\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transactions-by-userid\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transactions-by-userid\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transactions-by-userid\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Get Transaction API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\" , job=\"tsb-sca-transaction-query-api\", uri=~\".*transaction\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transaction\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transaction\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-sca-transaction-query-api\", uri=~\".*transaction\", method=\"GET\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Stepup Auth API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", job=\"tsb-stepup-authentication-api\", uri=~\".*stepup-auth-response\", method=\"POST\"}[90d]))\r\n",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-stepup-authentication-api\", uri=~\".*stepup-auth-response\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-stepup-authentication-api\", uri=~\".*stepup-auth-response\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-stepup-authentication-api\", uri=~\".*stepup-auth-response\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Init App API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", job=\"tsb-sca-authentication-api\", uri=~\".*init-app-auth\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-sca-authentication-api\", uri=~\".*init-app-auth\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-sca-authentication-api\", uri=~\".*init-app-auth\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-sca-authentication-api\", uri=~\".*init-app-auth\", method=\"POST\"}[90d]))\r",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Auth Method API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\" , uri=~\".*auth-method\", job=\"tsb-sca-authentication-api\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-sca-authentication-api\", uri=~\".*auth-method\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-sca-authentication-api\", uri=~\".*auth-method\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-sca-authentication-api\", uri=~\".*auth-method\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Validate Password API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nsum(increase(http_server_requests_seconds_count {namespace=\"sca\", job=\"tsb-stepup-authentication-api\", uri=~\".*validate-pwd\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-stepup-authentication-api\", uri=~\".*validate-pwd\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-stepup-authentication-api\", uri=~\".*validate-pwd\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-stepup-authentication-api\", uri=~\".*validate-pwd\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  },
  {
   "title": "Send OTP API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\" , job=\"tsb-sca-authentication-api\", uri=~\".*send-otp\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of requests received"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"2..\", job=\"tsb-sca-authentication-api\", uri=~\".*send-otp\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of success response"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"4..\", job=\"tsb-sca-authentication-api\", uri=~\".*send-otp\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (4xx Errors)"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count {namespace=\"sca\", status =~\"5..\", job=\"tsb-sca-authentication-api\", uri=~\".*send-otp\", method=\"POST\"}[90d]))",
     "legendFormat": "Total number of failures (5xx Errors)"
    }
   ]
  }
 ]
}