{
 "title": "AWS MSK",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"LeaderCount\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_Count{job=\"shared-msk-jmx-exporter\", name=\"UncleanLeaderElectionsPerSec\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "singlestat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "singlestat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Kafka Broker  CPU Usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (rate(node_cpu_seconds_total{job=\"shared-msk-node-exporter\", mode=\"idle\"}[5m]) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "description": "% Heap Memory Usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "description": "Open File Descriptors",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "legendFormat": "{{instance}}" },
    { "legendFormat": "max {{instance}}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "% Heap Memory Usage",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-node_filesystem_avail_bytes{job=\"shared-msk-node-exporter\"}/node_filesystem_size_bytes{job=\"shared-msk-node-exporter\"}",
     "legendFormat": "{{instance}}{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "legendFormat": "{{instance}} Free Mem" },
    { "legendFormat": "{{instance}} Used Mem" },
    { "legendFormat": "{{instance}} Cached Mem" },
    { "legendFormat": "{{instance}} Swap Mem" }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "singlestat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.\n\nTotal in cluster",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicatedPartitions\"})",
     "legendFormat": "Under-replicated Partitions"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "singlestat",
   "description": "Number of partitions that don't have an active leader and are hence not writable or readable. Alert if value is greater than 0.\n\nTotal in cluster",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"OfflinePartitionsCount\"})",
     "legendFormat": "Offline Partitions"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "singlestat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"ActiveControllerCount\"})",
     "legendFormat": "Active Controller Count"
    }
   ]
  },
  {
   "title": "Under-replicated Partitions",
   "type": "graph",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |). Alert if value is greater than 0.\n\nTotal in cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicatedPartitions\"})",
     "legendFormat": "Under-replicated Partitions"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "description": "Number of partitions that don't have an active leader and are hence not writable or readable. Alert if value is greater than 0.\n\nTotal in cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"OfflinePartitionsCount\"})",
     "legendFormat": "Offline Partitions"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "graph",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"ActiveControllerCount\"})",
     "legendFormat": "Active Controller Count"
    }
   ]
  },
  {
   "title": "Log flush latency",
   "type": "graph",
   "description": "Log Flush Rate and Time (ms)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_log_LogFlushStats_Count{job=\"shared-msk-jmx-exporter\", name=\"LogFlushRateAndTimeMs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fetcher Lag",
   "type": "graph",
   "description": "This metric indicates the lag in the number of messages per follower replica, indicating that replication has potentially stopped or has been interrupted. This is a major problem when dealing with the real-time processing of incoming data and should be monitored. Also monitoring the replica.lag.time.max.ms configuration parameter you can measure the time for which the replica has not attempted to fetch new data from the leader.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_FetcherLagMetrics_Value{ job=\"shared-msk-jmx-exporter\", name=\"ConsumerLag\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer message rate",
   "type": "graph",
   "description": "This metric indicates the lag in the number of messages per follower replica, indicating that replication has potentially stopped or has been interrupted. This is a major problem when dealing with the real-time processing of incoming data and should be monitored. Also monitoring the replica.lag.time.max.ms configuration parameter you can measure the time for which the replica has not attempted to fetch new data from the leader.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "legendFormat": "{{topic}}" }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"MessagesInPerSec\", topic!=\"\"})",
     "legendFormat": "Messages In Per Second"
    }
   ]
  },
  {
   "title": "Bytes In Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"BytesInPerSec\", topic!=\"\"})",
     "legendFormat": "Bytes In Per Second"
    }
   ]
  },
  {
   "title": "Bytes Out Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"BytesOutPerSec\", topic!=\"\"})",
     "legendFormat": "Bytes Out Per Second"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"MessagesInPerSec\", topic=~\".+\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesInPerSec\", topic=~\".+\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesOutPerSec\", topic=~\".+\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"TotalProduceRequestsPerSec\"})",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"TotalFetchRequestsPerSec\"})",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"TotalFetchRequestsPerSec\"}) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{job=\"shared-msk-jmx-exporter\",  name=\"TotalProduceRequestsPerSec\", topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{job=\"shared-msk-jmx-exporter\",  name=\"TotalFetchRequestsPerSec\", topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{job=\"shared-msk-jmx-exporter\", name=\"FailedProduceRequestsPerSec\", topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{job=\"shared-msk-jmx-exporter\", name=\"FailedFetchRequestsPerSec\", topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Network Errors Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_RequestMetrics_MeanRate{job=\"shared-msk-jmx-exporter\", name=\"ErrorsPerSec\"}) by (request)",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "singlestat",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 73 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_MeanRate{job=\"shared-msk-jmx-exporter\", name=\"UncleanLeaderElectionsPerSec\"})",
     "legendFormat": "UncleanLeaderElectionsPerSec"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_MeanRate{job=\"shared-msk-jmx-exporter\", name=\"UncleanLeaderElectionsPerSec\"})",
     "legendFormat": "UncleanLeaderElectionsPerSec"
    }
   ]
  },
  {
   "title": "Partition Count by instance",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"PartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Leader Count by instance",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\",name=\"LeaderCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Lag by instance",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaFetcherManager_Value{job=\"shared-msk-jmx-exporter\", name=\"MaxLag\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent by instance",
   "type": "graph",
   "description": "Average fraction of time the request handler threads are idle. Values are between 0 (all resources are used) and 1 (all resources are available)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_MeanRate{job=\"shared-msk-jmx-exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent by Instance",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_SocketServer_Value{job=\"shared-msk-jmx-exporter\", name=\"NetworkProcessorAvgIdlePercent\"}*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Broker Running Ports",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 97 },
   "targets": [
    {
     "expr": "sum(kafka_server_FetcherStats_Count{job=\"shared-msk-jmx-exporter\"}) by (instance, brokerport)",
     "legendFormat": "Instance: {{instance}} - Kafka Broker Running Port: {{brokerPort}}"
    }
   ]
  }
 ]
}