{
 "title": "Consul Monitoring",
 "description": "Get performance metrics from Consul metrics prometheus endpoint /agent/metrics?format=prometheus. Tested with Consul 1.4.4, Prometheus 2.10.0 and Grafana 6.2.4. Although can potentially work with other versions.",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Instance",
    "query": "label_values(up{instance=~\".*consul.*\", instance!~\".*vault-consul.*\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consul Raft Leader",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "consul_raft_leader{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Servers (Peers) in Raft Cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "consul_raft_peers" }
   ]
  },
  {
   "title": "Members in Cluster",
   "type": "gauge",
   "description": "This increments whenever a Consul server becomes a leader.",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "consul_serf_lan_members{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Total Services",
   "type": "gauge",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "consul_catalog_services{}", "legendFormat": "Transactions" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"$consul\"}[5m]) / 12 * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "UP",
   "type": "graph",
   "description": "Is it running at all?",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job=~\"ec2-discover-node-exporter\",instance=~\"$consul\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unhealthy Consul Services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service_name, status, node) (consul_health_service_status{status!=\"passing\"})",
     "legendFormat": "{{node}} - {{service_name}} - {{status}}"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "consul_health_node_status{status!='passing'}",
     "legendFormat": "{{node}} - {{status}}"
    }
   ]
  },
  {
   "title": "Services and Checks",
   "type": "graph",
   "description": "This measures the number of bytes allocated by the Consul process. Consul keeps all of its data in memory. If Consul consumes all available memory, it will crash.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node,service_id,status) (consul_health_service_status)",
     "legendFormat": "{{node}} - {{service_id}} - {{status}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$consul\"}",
     "legendFormat": "{{instance}} max fds"
    },
    {
     "expr": "process_open_fds{instance=~\"$consul\"}",
     "legendFormat": "{{instance}} open fds"
    }
   ]
  },
  {
   "title": "Consul Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{instance=~\"$consul\"}",
     "legendFormat": "{{instance}} go threads"
    },
    {
     "expr": "consul_runtime_num_goroutines{instance=~\"$consul\"}",
     "legendFormat": "{{instance}} num goroutines"
    }
   ]
  }
 ]
}