{
 "title": "Kubernetes: POD Overview by Application",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{},namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(consumer_fetch_manager_metrics_records_lag_max{namespace=~\"$namespace\"}, application)"
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count by $namespace",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$namespace\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\"})",
     "legendFormat": "Statefulsets"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod.*\"}",
     "legendFormat": "{{pod}}-{{ container }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod.*\",container!=\"POD\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$pod.*\", image!=\"\", container!=\"POD\", image!=\"\"}[2m]))",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod.*\",container!=\"POD\"})",
     "legendFormat": "Requested: {{ container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod.*\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod.*\", container!=\"POD\", container!=\"\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(container_memory_working_set_bytes{namespace=~\"$namespace\",pod=~\"$pod.*\",  container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod.*\", container=~\"$container\"})",
     "legendFormat": "Requested: {{ container }}"
    },
    {
     "expr": "avg by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",pod=~\"$pod.*\", container=~\"$container\"})",
     "legendFormat": "Limit: {{ container }}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) + avg(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) "
    }
   ]
  },
  {
   "title": "POD Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate (container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate (container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod.*\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(consumer_fetch_manager_metrics_records_lag_max{application=~\"$application\",application!~\"\"}) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Consumer message rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(consumer_fetch_manager_metrics_records_consumed_rate{application=~\"$application\",application!~\"\"}) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Producer send error rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(producer_metrics_record_error_rate{application=~\"$application\",application!~\"\"}) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}