{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">IO Queue Information</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "$classes I/O Queue delay by [[by]]",
   "targets": [
    {
     "expr": "max(rate(scylla_io_queue_total_delay_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(    scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])",
     "legendFormat": "IO queue {{[[by]]}}"
    },
    {
     "expr": "max(rate(scylla_io_queue_total_exec_sec{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]]) or on() max(    scylla_io_queue_delay{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"} ) by ([[by]])",
     "legendFormat": "Disk {{[[by]]}}"
    }
   ]
  },
  {
   "title": "$classes Queue length by [[by]]",
   "targets": [
    {
     "expr": "max(scylla_io_queue_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])",
     "legendFormat": "queue length {{[[by]]}}"
    },
    {
     "expr": "max(scylla_io_queue_disk_queue_length{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}) by ([[by]])",
     "legendFormat": "disk queue length {{[[by]]}}"
    }
   ]
  },
  {
   "title": "$classes I/O Queue bandwidth by [[by]]",
   "targets": [
    {
     "expr": "sum(rate(scylla_io_queue_total_bytes{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "$classes I/O Queue IOPS by [[by]]",
   "targets": [
    {
     "expr": "sum(rate(scylla_io_queue_total_operations{class=\"$classes\", instance=~\"[[node]]\",cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Information by Task Group</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Time used by [[by]] - $group",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. This graph shows how much time was spent in $group group",
   "targets": [
    {
     "expr": "$func(rate(scylla_scheduler_runtime_ms{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\",group=~\"$group\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]])"
    }
   ]
  },
  {
   "title": "Time spent in task quota violations by [[by]] - $group",
   "description": "Scylla employs an event-loop like reactor that alternates between the execution of different groups of tasks periodically. The maximum amount of time during which a task group can run is called the     \"task quota\". Some task groups may disrespect that and run for longer. This may cause latency issues",
   "targets": [
    {
     "expr": "$func(rate(scylla_scheduler_time_spent_on_task_quota_violations_ms{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\",group=~\"$group\", shard=~\"[[shard]]\"}[1m])/1000) by ([[by]])"
    }
   ]
  },
  {
   "title": "Scheduler shares [[by]] - $group",
   "description": "Shares assigned to the $group. Shares determine how Scylla reactor distributes the task quotas between groups (Higher share gets more quotas)",
   "targets": [
    {
     "expr": "$func(scylla_scheduler_shares{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\",group=~\"$group\", shard=~\"[[shard]]\"}) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "content": "<h1 style=\"color:#5780C1; border-bottom: 3px solid #5780C1;\">Internal node Errors - $cluster</h1>"
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Local Reads Error by [[by]]",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "targets": [
    {
     "expr": "avg(rate(scylla_storage_proxy_coordinator_read_errors_local_node{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Local Write Error by [[by]]",
   "description": "Number of write requests that failed due to an 'unavailable' error",
   "targets": [
    {
     "expr": "avg(rate(scylla_storage_proxy_coordinator_write_errors_local_node{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  { "content": "##  " }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "Reads Unavailable Error by [[by]]",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "targets": [
    {
     "expr": "avg(rate(scylla_storage_proxy_coordinator_read_unavailable{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Write Unavailable Error by [[by]]",
   "description": "Number of write requests that failed on a local Node",
   "targets": [
    {
     "expr": "avg(rate(scylla_storage_proxy_coordinator_write_unavailable{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Range Unavailable Error by [[by]]",
   "description": "Number of write requests that failed on a local Node",
   "targets": [
    {
     "expr": "avg(rate(scylla_storage_proxy_coordinator_range_unavailable{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  }
 ]
}
{
 "title": "New row",
 "panels": [
  {
   "title": "AIO Error by [[by]]",
   "description": "Number of AIO Errors",
   "targets": [
    {
     "expr": "avg(rate(scylla_reactor_aio_errors{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "Ignored Future By [[by]]",
   "description": "Total number of abandoned failed futures, futures destroyed while still containing an exception.",
   "targets": [
    {
     "expr": "sum(rate(scylla_reactor_abandoned_failed_futures{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  },
  {
   "title": "C++ Exceptions [[by]]",
   "description": "Number of C++ exceptions thrown.\n\n An exception by itself does not indicate a problem",
   "targets": [
    {
     "expr": "sum(rate(scylla_reactor_cpp_exceptions{instance=~\"[[node]]\" ,cluster=~\"$cluster|$^\", dc=~\"$dc\", shard=~\"[[shard]]\"}[1m])) by ([[by]])"
    }
   ]
  }
 ]
}