{
 "title": "MSK Overview",
 "description": "Prometheus monitoring for MSK cluster",
 "tags": [
  "msk",
  "kafka"
 ],
 "time": { "from": "2022-08-23T08:38:32.218Z", "to": "2022-08-23T09:21:35.102Z" },
 "panels": [
  { "title": "Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages In Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"MessagesInPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec from Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesInPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesOutPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Per Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicatedPartitions\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderMinIsrPartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"PartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"ErrorsPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ReplicationBytesOutPerSec\"}) by (instance)"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"shared-msk-node-exporter\", mountpoint=\"/kafka/datalogs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Per Sec over the last 5 mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (rate(node_cpu_seconds_total{job=\"shared-msk-node-exporter\"}[5m]))",
     "legendFormat": "{{mode}} - {{instance}}"
    }
   ]
  },
  {
   "title": "ZookeeperDisconnectsPerSecond",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_SessionExpireListener_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ZooKeeperDisconnectsPerSec\"}"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ReplicationBytesInPerSec\"}) by (instance)"
    }
   ]
  }
 ]
}