{
 "title": "MSK Overview-2",
 "description": "Prometheus monitoring for MSK cluster",
 "tags": [
  "msk",
  "kafka"
 ],
 "time": { "from": "2022-08-23T08:38:32.218Z", "to": "2022-08-23T09:21:35.102Z" },
 "panels": [
  {
   "title": "Under replicated partitions by Topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_Partition_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicated\"}) by (topic)"
    }
   ]
  },
  {
   "title": "Log Flush Latency(ms)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(kafka_log_LogFlushStats_Count{job=\"shared-msk-jmx-exporter\", name=\"LogFlushRateAndTimeMs\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"OfflinePartitionsCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Fetch Queue Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_Fetch_queue_size{job=\"shared-msk-jmx-exporter\"}) without (instance)"
    }
   ]
  },
  {
   "title": "In-Sync Replica state change",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_controller_ControllerStats_Count{job=\"shared-msk-jmx-exporter\", name=\"IsrChangeRateAndTimeMs\"}[30m])) without (instance)"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ReplicationBytesInPerSec\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"GlobalTopicCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"GlobalPartitionCount\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Preferred Leader Imbalance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"shared-msk-jmx-exporter\", name=\"PreferredReplicaImbalanceCount\"}) without (instance)"
    }
   ]
  },
  { "title": "Per Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Messages In Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"MessagesInPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Sec from Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesInPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_server_BrokerTopicMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"BytesOutPerSec\", topic=~\".+\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Per Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderReplicatedPartitions\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"UnderMinIsrPartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"shared-msk-jmx-exporter\", name=\"PartitionCount\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"RequestsPerSec\", request=~\"Produce|FetchConsumer|FetchFollower\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(kafka_network_RequestMetrics_Count{job=\"shared-msk-jmx-exporter\", name=\"ErrorsPerSec\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ReplicationBytesOutPerSec\"}) by (instance)"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Available Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"shared-msk-node-exporter\", mountpoint=\"/kafka/datalogs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Per Sec over the last 5 mins",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance, mode) (rate(node_cpu_seconds_total{job=\"shared-msk-node-exporter\"}[5m]))",
     "legendFormat": "{{mode}} - {{instance}}"
    }
   ]
  },
  {
   "title": "ZookeeperDisconnectsPerSecond",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_SessionExpireListener_OneMinuteRate{job=\"shared-msk-jmx-exporter\", name=\"ZooKeeperDisconnectsPerSec\"}"
    }
   ]
  }
 ]
}