---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: thanos
  namespace: prometheus
spec:
  releaseName: thanos
  chart:
    repository: https://kubernetes-charts.banzaicloud.com
    name: thanos
    version: 0.3.28
  values:
    ## helm upgrade --install thanos banzaicloud-stable/thanos -f thanos-chart.yaml
    image:
      repository: quay.io/thanos/thanos
      tag: v0.18.0

    objstoreSecretOverride: thanos-s3-config

    store:
      serviceAccount: prometheus-sa
      nodeSelector:
        taints.eks.aws.uk.tsb/role: mgmt
      tolerations:
        - key: role
          operator: Equal
          value: mgmt
          effect: NoSchedule
      metrics:
        serviceMonitor:
          enabled: true
    sidecar:
      serviceAccount: prometheus-sa
      metrics:
        serviceMonitor:
          enabled: true
    query:
      serviceAccount: prometheus-sa
      nodeSelector:
        taints.eks.aws.uk.tsb/role: mgmt
      tolerations:
        - key: role
          operator: Equal
          value: mgmt
          effect: NoSchedule
      metrics:
        serviceMonitor:
          enabled: true
    compact:
      serviceAccount: prometheus-sa
      nodeSelector:
        taints.eks.aws.uk.tsb/role: mgmt
      tolerations:
        - key: role
          operator: Equal
          value: mgmt
          effect: NoSchedule
      extraArgs:
        - "--debug.max-compaction-level=3"
      # # Minimum age of fresh (non-compacted) blocks before they are being processed.
      # # Malformed blocks older than the maximum of consistency-delay and 30m0s will be removed.
      # consistencyDelay: 30m
      # # How long to retain raw samples in bucket. 0d - disables this retention
      # retentionResolutionRaw: 14d
      # # How long to retain samples of resolution 1 (5 minutes) in bucket. 0d - disables this retention
      # retentionResolution5m: 90d
      # # How long to retain samples of resolution 2 (1 hour) in bucket. 0d - disables this retention
      # retentionResolution1h: 120d
      metrics:
        serviceMonitor:
          enabled: true
    bucket:
      serviceAccount: prometheus-sa
      nodeSelector:
        taints.eks.aws.uk.tsb/role: mgmt
      tolerations:
        - key: role
          operator: Equal
          value: mgmt
          effect: NoSchedule