#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: vault-cop-binding
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: system:auth-delegator
#subjects:
#  - kind: ServiceAccount
#    name: vault-cop
#    namespace: cop
#  - kind: ServiceAccount
#    name: tsb-cop
#    namespace: cop
#  - kind: ServiceAccount
#    name: cop-sink-connector
#    namespace: cop
#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: vault-cop
#  namespace: cop
