---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cop-view-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cop-view-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cop-view-role
- kind: Group
  name: cop-read-only
subjects:
- kind: Group
  name: cop-view-kube-system