#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: cop-admin-role
#  namespace: cop
#rules:
#  - apiGroups: ["*"]
#    resources: ["*"]
#    verbs: ["*"]
#---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: cop-admin-binding
#  namespace: cop
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: cop-admin-role
#subjects:
#  - kind: ServiceAccount
#    name: tsb-cop
#  - kind: Group
#    name: cop-admin
#  - kind: ServiceAccount
#    name: jenkins-terraform
#    namespace: jenkins
