---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cb-logging-admin-role
  namespace: logging
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cb-logging-admin-binding
  namespace: logging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cb-logging-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-cb
    namespace: cb
  - kind: Group
    name: cb-admin