---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: filebeat
  namespace: logging
spec:
  releaseName: tsb-filebeat
  chart:
    repository: https://helm.elastic.co
    name: filebeat
    version: 7.10.1
  values:
    # Allows you to add any config files in /usr/share/filebeat
    # such as filebeat.yml
    image: docker.artifactory.mgmt.aws.uk.tsb/elastic-docker-remote/beats/filebeat
    tolerations:
      - key: role
        operator: Equal
        value: mgmt
        effect: NoSchedule
      - key: role
        operator: Equal
        value: sco
        effect: NoSchedule
    filebeatConfig:
      filebeat.yml: |
        filebeat.autodiscover:
          providers:
            - type: kubernetes
              node: ${NODE_NAME}
              hints.enabled: true
              hints.default_config:
                type: container
                paths:
                  - /var/lib/docker/containers/*${data.kubernetes.container.id}/*.log
                tags: ["kubernetes"]
                fields:
                  env_id: "{{ AWS_ENVIRONMENT }}"
                  cluster_id: "{{ CLUSTER_NAME }}"
                containers.ids:
                  - "${data.kubernetes.container.id}"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
          - add_cloud_metadata:
          - add_host_metadata:
        output.logstash:
          hosts: ["logstash.{{ AWS_ENVIRONMENT }}.internal:5050"]
          ttl: 60s
    helm:
      versions: v3
    extraEnvs:
      - name: http_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: https_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: no_proxy
        value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,.s3.eu-west-2.amazonaws.com,.cluster.local,.aws.uk.tsb