kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-prod-vpc
  namespace: prometheus
spec:
  podSelector:
    matchLabels: {}
  egress:
  - to:
    - ipBlock:
        cidr: 10.163.128.0/17
  ingress:
  - from:
    - ipBlock:
        cidr: 10.163.128.0/17
