---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: prometheus
  labels:
    prometheus: "data"
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-02377df3::fsap-0d10ee8f6c55fdf49"