---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: prometheus
  labels:
    prometheus: "data"
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-31b0e7c0::fsap-0a6d4d2b0069f897f"