---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: prometheus
  labels:
    prometheus: "data"
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-276b34d6::fsap-09a534cf4ea1ab5a6"
