---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.3.0
  values:
    git:
      url: https://$(GIT_AUTHUSER):$(GIT_AUTHKEY)@github.com/TSB-Bank/eks-config
      branch: nonprod
      readonly: true
    registry:
      disableScanning: true
    env:
      secretName: flux-git-auth
    extraEnvs:
      - name: http_proxy
        value: http://proxy-access.eu-west-2.aws.uk.tsb:3128
      - name: https_proxy
        value: http://proxy-access.eu-west-2.aws.uk.tsb:3128
      - name: no_proxy
        value: localhost,127.0.0.1,169.254.169.254,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,.cluster.local
      - name: KUSTOMIZE_PLUGIN_HOME
        value: /var/lib/kustomize/plugins
    extraVolumeMounts:
      - name: kustomize-plugins
        mountPath: /var/lib/kustomize/plugins
    extraVolumes:
      - name: kustomize-plugins
        configMap:
          name: kustomize-plugins
          items:
            - key: AWSTransformer
              path: v1/AWSTransformer/AWSTransformer