---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datalake-admin-role
  namespace: datalake
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datalake-admin-binding
  namespace: datalake
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datalake-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-datalake
  - kind: Group
    name: datalake-admin
  - kind: ServiceAccount
    name: jenkins-terraform
    namespace: jenkins
