---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eks-readonly
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","services","events","namespaces","nodes","persistentvolumes","persistenttvolumeclaims"]
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - apps
      - extensions
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1  
kind: ClusterRoleBinding
metadata:
  name: eks-readonly
roleRef:
    kind: ClusterRole
    name: eks-readonly
    apiGroup: rbac.authorization.k8s.io
subjects:
    - kind: User
      name: tsb-admins-eks
  