apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: aws-lb-controller
  namespace: kube-system
spec:
  selector: app.kubernetes.io/name == 'aws-load-balancer-controller'
  types:
    - Egress
    - Ingress
  egress:
    - metadata:
        annotations:
          from: aws-lb-controller
          to: metadata
      action: Allow
      protocol: TCP
      destination:
        nets:
          - 169.254.169.254/32
        ports:
          - 80
  ingress:
    - metadata:
        annotations:
          from: vpc
          to: aws-lb-controller 
      action: Allow
      destination:
        ports:
          - 443
      protocol: TCP
      source:
        selector: vpc == 'local' && layer == 'all'
