---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ IAM_ADMIN_ROLE_NAME }}
      username: admin
      groups:
        - system:masters