---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ CLUSTER_NAME }}-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ IAM_ADMIN_ROLE_NAME }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/cb-admin
      username: cb-admin
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco
      username: tsb-sco
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-datalake
      username: tsb-datalake
      groups:
        - datalake-view-kube-system
        - datalake-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-ods-admin-role
      username: ods-admin
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-ods
      username: tsb-ods
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-obs-admin-role
      username: obs-admin
      groups:
        - obs-view-kube-system
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-obs
      username: tsb-obs
      groups:
        - obs-view-kube-system
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-obs-dev-eks 
      username: tsb-obs-dev
      groups:
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_kubernetes
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca
      username: tsb-sca
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca-dev-eks
      username: tsb-sca-dev
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-dev-eks
      username: tsb-sco-dev
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-datalake-dev-eks
      username: tsb-datalake-dev
      groups:
        - datalake-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb-dev-eks
      username: tsb-cb-dev
      groups:
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop-dev-eks
      username: tsb-cop-dev
      groups:
        - cop-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cob-dev-eks
      username: tsb-cob-dev
      groups:
        - cob-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-eks-readonly
      username: tsb-admins-eks
      groups:
        - tsb-admins
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop2-prod-eks-readonly-role
      username: tsb-cop2-view
      groups:
        - tsb-cop2-view
        - tsb-eks-readonly        
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-nonprod-eks
      username: tsb-sco-readyonly
      groups:
        - tsb-nonprod-eks-sco
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-cob-view-role
      username: tsb-cob-readyonly
      groups:
        - eks-cob-view-role
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop2-nonprod-eks
      username: tsb-cop2-nonprod-eks
      groups:
        - cop-phase2-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb-nonprod-eks
      username: tsb-cb-nonprod-eks
      groups:
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-nonprod-role
      username: tsb-nonprod-eks-fullaccess
      groups:
        - Dev-Nonprod-Eks-Access
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop-phase2
      username: tsb-nonprod-eks-cop-phase2
      groups:
        - tsb-nonprod-cop-phase2
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_tsbsme-readonly_billing
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_readonly_billing
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb-nonprod-eks-rw
      username: tsb-cb-nonprod-eks-rw
      groups:
        - tsb-cb-nonprod-eks-rw
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cob-nonprod-eks-rw
      username: tsb-cob-nonprod-eks-rw
      groups:
        - tsb-cob-nonprod-eks-rw
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca-nonprod-eks-rw
      username: tsb-sca-nonprod-eks-rw
      groups:
        - tsb-sca-nonprod-eks-rw
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-nonprod-eks-rw
      username: tsb-sco-nonprod-eks-rw
      groups:
        - tsb-sco-nonprod-eks-rw
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop2-preprod-eks
      username: tsb-cop2-eks-readonly
      groups:
        - tsb-cop2-eks-readonly
        - tsb-forgerock-sbat-rw-dev-eks
    - rolearn: arn:aws:iam::$AWS_ACCOUNT:role/{{ SSO_ADMIN }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::$AWS_ACCOUNT:role/{{ SSO_READONLY }}
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::$AWS_ACCOUNT:role/{{ SSO_POWER }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/role-reporting-kube-info
      username: reporting-user
