---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  releaseName: aws-load-balancer-controller
  chart:
    repository: https://github.com/aws/eks-charts
    name: aws-load-balancer-controller
    version: 2.6.4
  values:
    cluster:
      dnsDomain: cluster.local
    clusterName: dev-eks
    env:
      HTTP_PROXY: http://eu-west-2.proxy.aws.uk.tsb:3128
      HTTPS_PROXY: http://eu-west-2.proxy.aws.uk.tsb:3128
      NO_PROXY: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.am   azonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.e   u-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,.s3.eu-west-2.amazonaws.com,.cluster.local,.aws.uk.tsb
    externalManagedTags: []
    image:
      pullPolicy: IfNotPresent
      repository: docker.artifactory.mgmt.aws.uk.tsb/rackspace/aws-load-balancer-controller
      tag: v2.4.6
    imagePullSecrets: artifactory-credentials
    region: eu-west-2
    replicaCount: 2
    resources: {}
    vpcId: {{ VPC_ID }}