---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ CLUSTER_NAME }}-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ IAM_ADMIN_ROLE_NAME }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/cb-admin
      username: cb-admin
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco
      username: tsb-sco
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-datalake
      username: tsb-datalake
      groups:
        - datalake-view-kube-system
        - datalake-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-ods-admin-role
      username: ods-admin
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-ods
      username: tsb-ods
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-obs-admin-role
      username: obs-admin
      groups:
        - obs-view-kube-system
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-obs
      username: tsb-obs
      groups:
        - obs-view-kube-system
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-obs-dev-eks
      username: tsb-obs-dev
      groups:
        - obs-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_kubernetes
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca
      username: tsb-sca
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca-dev-eks
      username: tsb-sca-dev
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-dev-eks
      username: tsb-sco-dev
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-datalake-dev-eks
      username: tsb-datalake-dev
      groups:
        - datalake-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb-dev-eks
      username: tsb-cb-dev
      groups:
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop-dev-eks
      username: tsb-cop-dev
      groups:
        - cop-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cob-dev-eks
      username: tsb-cob-dev
      groups:
        - cob-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-eks-readonly
      username: tsb-admins-eks
      groups:
        - tsb-admins
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-{{ AWS_ENVIRONMENT }}-readonly-access
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-nonprod-eks
      username: tsb-sco-readyonly
      groups:
        - tsb-nonprod-eks-sco
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-cob-view-role
      username: tsb-cob-readyonly
      groups:
        - eks-cob-view-role
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-ob-{{ AWS_ENVIRONMENT }}-role
      username: fr-admin
      groups:
        - fr-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-dev-role
      username: tsb-dev-eks-fullaccess
      groups:
        - Dev-Nonprod-Eks-Access
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/ods-user-dev-env-role
      username: tsb-ods-dev
      groups:
        - ods-view-kube-system
        - ods-admin
        - ods-user-dev-env-group
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/ods-jenkins-dev-env-role
      username: ods-jenkins-dev-env-user
      groups:
        - ods-jenkins-dev-env-group
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_tsbsme-readonly_billing
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_readonly_billing
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop2-dev-eks
      username: tsb-dev-eks-cop2
      groups:
        - tsb-dev-eks-cop2
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-forgerock-sbat-dev-eks-rw-role
      username: tsb-forgerock-sbat-rw-dev-eks
      groups:
        - tsb-forgerock-sbat-rw-dev-eks
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/role-reporting-kube-info
      username: reporting-user
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/AWSReservedSSO_AdministratorAccess_73b4990a5d43698d
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/AWSReservedSSO_ReadOnlyAccess_296da645e96ea4f0
      username: tsb-eks-readonly
      groups:
        - tsb-eks-readonly
