---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ CLUSTER_NAME }}-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ IAM_ADMIN_ROLE_NAME }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/cb-admin
      username: cb-admin
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin