---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
data:
  mapRoles: |
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ CLUSTER_NAME }}-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/{{ IAM_ADMIN_ROLE_NAME }}
      username: admin
      groups:
        - system:masters
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/cb-admin
      username: cb-admin
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco
      username: tsb-sco
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks-ods-admin-role
      username: ods-admin
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-ods
      username: tsb-ods
      groups:
        - ods-view-kube-system
        - ods-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rl_kubernetes
      username: tsb-cb
      groups:
        - cb-view-kube-system
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca
      username: tsb-sca
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sca-dev-eks
      username: tsb-sca-dev
      groups:
        - sca-view-kube-system
        - sca-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-sco-dev-eks
      username: tsb-sco-dev
      groups:
        - sco-view-kube-system
        - sco-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cb-dev-eks
      username: tsb-cb-dev
      groups:
        - cb-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cop-dev-eks
      username: tsb-cop-dev
      groups:
        - cop-admin
    - rolearn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-cob-dev-eks
      username: tsb-cob-dev
      groups:
        - cob-admin
