apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: aws-lb-controller
  namespace: kube-system
spec:
  selector: app.kubernetes.io/name == 'aws-lb-controller'
  types:
    - Egress
  egress:
    - metadata:
        annotations:
          from: aws-lb-controller
          to: metadata
      action: Allow
      protocol: TCP
      destination:
        nets:
          - 169.254.169.254/32
        ports:
          - 80