apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
  kmsKeyId: alias/ebs-internal
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: ebs-csi-controller
  namespace: kube-system
spec:
  selector: app.kubernetes.io/name == 'aws-ebs-csi-driver'
  types:
    - Egress
  egress:
    - metadata:
        annotations:
          from: ebs-csi-controller
          to: metadata
      action: Allow
      protocol: TCP
      destination:
        nets:
          - 169.254.169.254/32
        ports:
          - 80
