---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lambda-reporting
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - namespaces
      - pods
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lambda-reporting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lambda-reporting
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: tsb-lambda-user