---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: vault-cob-binding
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-cob
  namespace: cob
- kind: ServiceAccount
  name: tsb-cob
  namespace: cob
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: vault-cob
    namespace: cob