---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sca-vault-cb-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-sca
    namespace: sca
  - kind: ServiceAccount
    name: tsb-sca
    namespace: sca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sca
  namespace: sca
