apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sca-cluster-binding-service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-service-discovery
subjects:
  - kind: ServiceAccount
    name: tsb-sca
    namespace: sca
