apiVersion: v1
data:
  apiToken: ZHQwYzAxLkNIWTY3VUhSMzVFTEJFNkJRWjRXNUhQTC5KQzJST1dTWDdNTVBST1FDTlJXTjdIWDRaMlFMNkpNWEo3TFlOTEdXRjNBSEtFSFBNSUk2T1FTWjZQT1ozMjdECg==
  paasToken: ZHQwYzAxLkNIWTY3VUhSMzVFTEJFNkJRWjRXNUhQTC5KQzJST1dTWDdNTVBST1FDTlJXTjdIWDRaMlFMNkpNWEo3TFlOTEdXRjNBSEtFSFBNSUk2T1FTWjZQT1ozMjdECg==
kind: Secret
metadata:
  name: dynakube
  namespace: dynatrace
