---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: argon-broker
  namespace: jenkins
spec:
  releaseName: argon-broker
  chart:
    repository: https://argonsecurity.github.io/broker-deployment
    name: argon/argon-broker
    version: 1.0.5
  values:
    global:
      argonServer: https://app-broker.argon.io
      public_key: 3nc7ypt3d2ecu7ity
      token: 9b386178-ea4b-4bf8-a983-fa22a33463f4
      username: tsb
    envs:
      http_proxy: http://eu-west-2.proxy.aws.uk.tsb:3128
      https_proxy: http://eu-west-2.proxy.aws.uk.tsb:3128
      no_proxy: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,.s3.eu-west-2.amazonaws.com,.cluster.local,.aws.uk.tsb
    jenkins:
      url: "http://jenkins.jenkins.svc.cluster.local:8080"
