---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: obs-view-role
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: obs-view-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: obs-view-role
subjects:
  - kind: Group
    name: obs-view-kube-system
  - kind: ServiceAccount
    name: tsb-obs
    namespace: obs
