---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: obs-admin-role
  namespace: obs
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: obs-admin-binding
  namespace: obs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: obs-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-obs
  - kind: Group
    name: obs-admin
  - kind: ServiceAccount
    name: jenkins-terraform
    namespace: jenkins
