apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-09T18:58:48Z"
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::273312704578:role/InstanceRole-_wdmzjc
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::273312704578:role/rl_tsbsme_non_prod_admin
      username: admin
      groups:
        - system:masters