#This clusterrole is used by all projects and is mapped to multiple service accounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role-service-discovery
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ob-cluster-binding-service-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-service-discovery
subjects:
  - kind: ServiceAccount
    name: tsb-api-gw-ob
    namespace: api-gw-ob
