{
 "title": "Overview Scylla COP",
 "panels": [
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"scylla-node-exporter\"})",
     "legendFormat": "Total Nodes"
    }
   ]
  },
  {
   "title": "Unreachable",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scrape_samples_scraped{job=\"scylla-node-exporter\"}==0) OR vector(0)",
     "legendFormat": "Unreachable"
    }
   ]
  },
  {
   "title": "Joining",
   "type": "singlestat",
   "description": "Number of nodes that reported their status as Starting or Joining",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{job=~\"scylla-node-exporter\"}==1) +  count(scylla_node_operation_mode{job=~\"scylla-node-exporter\"}==2)OR vector(0)",
     "labelSelector": "*",
     "legendFormat": "Joining",
     "target": "Query",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Leaving",
   "type": "singlestat",
   "description": "Number of nodes that reported their status as  Leaving, Decommissioned, Draining or Drained",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(scylla_node_operation_mode{job=~\"scylla-node-exporter\"}>3)OR vector(0)",
     "legendFormat": "Leaving"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "description": "The percentage of the time during which Scylla utilized the CPU. Note that because Scylla does busy polling for some time before going idle, CPU utilization as seen by the operating system may be much higher. Your system is not yet CPU-bottlenecked until this metric is high.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(scylla_reactor_utilization{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}",
     "target": "select metric",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table-old",
   "description": "Nodes Information table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "0*scylla_scylladb_current_version{job=~\"scylla-default-metrics-exporter\"} + on (instance) group_left() scylla_node_operation_mode{job=~\"scylla-default-metrics-exporter\"}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=~\"scylla-node-exporter\"}) by (instance) - sum(node_filesystem_avail_bytes{job=~\"scylla-node-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests Served - Coordinator",
   "type": "graph",
   "description": "Amount of requests served as the coordinator. Imbalances here represent dispersion at the client-side level or connection balancing level, not your data model.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_transport_requests_served{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) + $func(irate(scylla_thrift_served{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Active Alerts", "type": "table-old", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CPU Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CPU Info</h1>"
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\", job=\"scylla-node-exporter\"}[1m]) * 100)",
     "legendFormat": "{{instance}} Total CPU Used"
    }
   ]
  },
  {
   "title": "Scylla Reactor Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "$func(scylla_reactor_utilization{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}} reactor_utilization"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Memory Info</h1>"
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-(node_memory_MemFree_bytes{job=~\"scylla-node-exporter\"}/(node_memory_MemTotal_bytes{job=~\"scylla-node-exporter\"})*100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100-((node_memory_SwapFree_bytes{job=~\"scylla-node-exporter\"}) / (node_memory_SwapTotal_bytes{job=~\"scylla-node-exporter\"})) * 100",
     "legendFormat": "{{name}} Swap Memory Utilization"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Volume details</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Volume details</h1>"
  },
  {
   "title": "% Filesystem Fullness",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_free_bytes{job=~\"scylla-node-exporter\",mountpoint=~\"/var/lib/scylla|/var/lib/scylla/commitlog\"} / node_filesystem_size_bytes{job=~\"scylla-node-exporter\",mountpoint=~\"/var/lib/scylla|/var/lib/scylla/commitlog\"}",
     "legendFormat": "{{name}}   {{device}} --> {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"scylla-node-exporter\",mountpoint=~\"/var/lib/scylla\"} - node_filesystem_free_bytes{job=~\"scylla-node-exporter\",mountpoint=~\"/var/lib/scylla\"}",
     "legendFormat": "Used size: {{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{job=~\"scylla-node-exporter\",mountpoint=~\"/var/lib/scylla\"}",
     "legendFormat": "Total size: {{mountpoint}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Disk Info</h1>"
  },
  {
   "title": "Total Storage",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 58 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{job=~\"scylla-node-exporter\",mountpoint=\"/var/lib/scylla\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{job=~\"scylla-node-exporter\",mountpoint=\"/var/lib/scylla\"})-sum(node_filesystem_avail_bytes{job=~\"scylla-node-exporter\",mountpoint=\"/var/lib/scylla\"}))",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{fstype=\"xfs\",job=~\"scylla-node-exporter\"}) by (instance,mountpoint) - sum(node_filesystem_avail_bytes{fstype=\"xfs\",job=~\"scylla-node-exporter\"}) by (instance,mountpoint)",
     "legendFormat": "{{instance}}: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_writes_completed_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_bytes_written{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_reads_completed{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 70 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_bytes_read{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 76 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network info</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Network info</h1>"
  },
  {
   "title": "Interface Rx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_packets_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_receive_packets{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Tx Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_packets_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_transmit_packets{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Rx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Interface Tx Bps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes{job=~\"scylla-node-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 90 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Latencies - Coordinator</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Latencies - Coordinator</h1>"
  },
  {
   "title": "Writes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_count{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_write_latency_sum{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)/($func(rate(scylla_storage_proxy_coordinator_write_latency_count{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) + 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "95th percentile write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile write latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 92 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_write_latency_bucket{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_count{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "$func(rate(scylla_storage_proxy_coordinator_read_latency_sum{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)/($func(rate(scylla_storage_proxy_coordinator_read_latency_count{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) + 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "95th percentile read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th percentile read latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(scylla_storage_proxy_coordinator_read_latency_bucket{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance, le))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 104 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache by instance</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cache by instance</h1>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 104 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Timeouts</h1>"
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "description": "Number of rows that were read from the cache, without needing to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_cache_row_hits{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "description": "Number of rows that were not present in the cache, and had to be fetched from storage.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 106 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "$func(irate(scylla_cache_row_misses{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Timeouts/Minutes",
   "type": "graph",
   "description": "Requests that Scylla tried to write but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "wpm" }
   ],
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_write_timeouts{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read Timeouts/Minutes",
   "type": "graph",
   "description": "Requests that Scylla tried to read but timed out. Timeouts are counted in the node that received the request (the coordinator), not at the replicas.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 106 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "$func(delta(scylla_storage_proxy_coordinator_read_timeouts{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 112 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cluster Cache</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cluster Cache</h1>"
  },
  {
   "title": "Cache Total Bytes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 114 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_total{job=~\"scylla-default-metrics-exporter\"})"
    }
   ]
  },
  {
   "title": "Cache Used (%)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 114 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(scylla_cache_bytes_used{job=~\"scylla-default-metrics-exporter\"})/sum(scylla_cache_bytes_total{job=~\"scylla-default-metrics-exporter\"})*100"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_hits{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Row Hits 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_hits{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Partition Hits 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Active Reads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_active_reads{job=~\"scylla-default-metrics-exporter\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cache Merges",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 118 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_partition_merges{job=~\"scylla-default-metrics-exporter\"}[2m]))"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_misses{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Row Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_misses{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Partition Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_concurrent_misses_same_key{job=~\"Scylla Exporter - .*\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Concurrent Misses 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_reads_with_misses{job=~\"Scylla Exporter - .*\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Reads Misses 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Evictions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_evictions{job=~\"scylla-default-metrics-exporter\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Row Evictions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_evictions{job=~\"scylla-default-metrics-exporter\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Partition Evictions 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Insertions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_insertions{job=~\"scylla-default-metrics-exporter\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Row Insertions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_insertions{job=~\"scylla-default-metrics-exporter\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Partition Insertions 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_static_row_insertions{job=~\"Scylla Exporter - .*\",environment=~\"$environment\"}[2m]))",
     "legendFormat": "Cache Static Row Insertions 2m Avg"
    }
   ]
  },
  {
   "title": "Cache Removals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scylla_cache_row_removals{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Row Removals 2m Avg"
    },
    {
     "expr": "sum(rate(scylla_cache_partition_removals{job=~\"scylla-default-metrics-exporter\"}[2m]))",
     "legendFormat": "Cache Partition Removals 2m Avg"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 137 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL - Coordinator</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">CQL - Coordinator</h1>"
  },
  {
   "title": "CQL Insert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_inserts{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Reads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Deletes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_deletes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Updates",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 139 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_updates{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client CQL connections",
   "type": "graph",
   "description": "amount of CQL connections currently established",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scylla_transport_current_connections{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Batches",
   "type": "graph",
   "description": "Number of CQL batches command, each batched command is counted once",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_batches{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CQL Command In Batches",
   "type": "graph",
   "description": "Number of CQL command batched. Each batch would add the number of commands inside the batch",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_statements_in_batches{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 151 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Optimization</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Optimization</h1>"
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "singlestat",
   "description": "All of the requests should be prepared\n\nPrepared statements remove the overhead of parsing the query every time and allow optimal routing of requests from client to server",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 153 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(irate(scylla_query_processor_statements_prepared{job=~\"scylla-default-metrics-exporter\"}[5m])) /(sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])) + sum(irate(scylla_cql_inserts{job=~\"scylla-default-metrics-exporter\"}[5m])) + sum(irate(scylla_cql_updates{job=~\"scylla-default-metrics-exporter\"}[5m])) + sum(irate(scylla_cql_deletes{job=~\"scylla-default-metrics-exporter\"}[5m])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL Non-Prepared Statements",
   "type": "graph",
   "description": "All of the requests should be prepared\n",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 153 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_query_processor_statements_prepared{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "singlestat",
   "description": "All requests should be paged\n\nNon Paged request sources:\n- Client modifying the fetch size\n\nNon Paged requests require reading all the results and returning them in a single request.",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 153 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (sum(irate(scylla_cql_unpaged_select_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))/sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Paged CQL Reads",
   "type": "graph",
   "description": "Non-Paged requests require reading all the results and returning them in a single request",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 153 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_unpaged_select_queries{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Non-Token Aware",
   "type": "singlestat",
   "description": "All of the requests should be Token Aware\n\nNon Token Aware requests sources:\n* Non-Prepared Stamements\n* Client not using a Token Aware load balancing policy\n\nTokenAware requests are sent to a Scylla node that is also a replica. Token Un-Aware requests require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 153 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - floor(100*(sum(irate(scylla_storage_proxy_coordinator_reads_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])) +sum(irate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])))/(sum(irate(scylla_cql_inserts{job=~\"scylla-default-metrics-exporter\"}[5m]) + irate(scylla_cql_updates{job=~\"scylla-default-metrics-exporter\"}[5m]) + irate(scylla_cql_deletes{job=~\"scylla-default-metrics-exporter\"}[5m]) + irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Non-Token Aware Queries",
   "type": "graph",
   "description": "Requests that are not token aware indicates that requests are not routed to the right node, which require extra hop and additional processing.\n\nNote that the metric shows incorrect values when batches are used.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 153 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) - sum(irate(scylla_storage_proxy_coordinator_reads_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) + sum(irate(scylla_cql_inserts{job=~\"scylla-default-metrics-exporter\"}[5m]) + irate(scylla_cql_updates{job=~\"scylla-default-metrics-exporter\"}[5m]) + irate(scylla_cql_deletes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance) - sum(irate(scylla_storage_proxy_coordinator_total_write_attempts_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)\n"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "singlestat",
   "description": "Reversed CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with ORDER BY that is different from the \"CLUSTERING ORDER BY\" of the table\nAlternatives:\n\n* Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 159 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_reverse_queries{job=~\"scylla-default-metrics-exporter\"}[5m])) / sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "Reversed CQL Reads",
   "type": "graph",
   "description": "Reversed CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 159 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_reverse_queries{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "singlestat",
   "description": "ALLOW FILTERING CQL Reads, the percentage of read requests with 'ALLOW FILTERING'\n\nALLOW FILTERING CQL Reads entail additional processing on server side\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned - check \n\"ALLOW FILTERING CQL Read Filtered Rows to check what percentage of the data is used\"\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 159 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_filtered_read_requests{job=~\"scylla-default-metrics-exporter\"}[5m])) / sum(irate(scylla_cql_reads{job=~\"scylla-default-metrics-exporter\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Reads",
   "type": "graph",
   "description": "Read requests with ALLOW FILTERING\n\nALLOW FILTERING CQL Reads entail additional processing on server side and should be avoided",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 159 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_read_requests{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING Filtered Rows",
   "type": "singlestat",
   "description": "ALLOW FILTERING Filtered rows, the percentage of rows that were read and then filtered.\n\nALLOW FILTERING CQL Reads entail additional processing on server side. \nReading a row and then filter it is a waste of resources.\n\nSources: CQL Read requests with \"ALLOW FILTERING\"\n\nALLOW FILTERING should be used when large parts of the filtered data is returned\n\nAlternatives:\n- Use a Secondary Index\n- Denormalize your data (use a Materialized View)",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 159 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * sum(irate(scylla_cql_filtered_rows_dropped_total{job=~\"scylla-default-metrics-exporter\"}[5m]))  /sum(irate(scylla_cql_filtered_rows_read_total{job=~\"scylla-default-metrics-exporter\"}[5m])) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "ALLOW FILTERING CQL Read Filtering",
   "type": "graph",
   "description": "CQL Queries with ALLOW FILTERING should be avoided.\nDropped rows are rows that were read but were filtered by the server.\nWhen dropped rows is relatively high you should consider the alternatives",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 159 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_read_total{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "rows read {{instance}}"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_matched_total{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "rows matched {{instance}}"
    },
    {
     "expr": "sum(irate(scylla_cql_filtered_rows_dropped_total{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "rows dropped {{instance}}"
    }
   ]
  },
  {
   "title": "CQL ANY Queries",
   "type": "singlestat",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 165 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ANY CL Queries",
   "type": "graph",
   "description": "Using consistency level ANY in a query may hurt persistency, if the node receiving the request will fail the data may be lost",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 165 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "singlestat",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 165 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ALL CL Queries",
   "type": "graph",
   "description": "Using consistency level ALL in a query may hurt availability, if a node is unavailable operations will fail",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 165 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\",consistency_level=\"ALL\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 171 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cross DC Information</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Cross DC Information</h1>"
  },
  {
   "title": "CQL ONE Queries",
   "type": "singlestat",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 173 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\",consistency_level=\"ONE\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL ONE CL Queries",
   "type": "graph",
   "description": "Using consistency level ONE in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_ONE instead",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\",consistency_level=\"ONE\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "singlestat",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 173 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor(100 *sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\",consistency_level=\"QUORUM\"}[5m]))/sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\"}[5m]))) OR vector(0)",
     "legendFormat": "aaa"
    }
   ]
  },
  {
   "title": "CQL QUORUM CL Queries",
   "type": "graph",
   "description": "Using consistency level QUORUM in a query when there is more than one DC may hurt performance, queries may end in the non-local DC. Use LOCAL_QUORUM instead",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 173 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(delta(scylla_query_processor_queries{job=~\"scylla-default-metrics-exporter\",consistency_level=\"QUORUM\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 179 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Errors</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">Errors</h1>"
  },
  {
   "title": "Local Reads Error",
   "type": "graph",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_read_errors_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local Write Error",
   "type": "graph",
   "description": "Number of write requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 181 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_write_errors_local_node{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AIO Error",
   "type": "graph",
   "description": "Number of AIO Errors",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 181 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_reactor_aio_errors{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Reads Unavailable Error",
   "type": "graph",
   "description": "Number of Read requests that failed due to an 'unavailable' error",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_read_unavailable{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Write Unavailable Error",
   "type": "graph",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 187 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_write_unavailable{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Range Unavailable Error",
   "type": "graph",
   "description": "Number of write requests that failed on a local Node",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 187 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg(irate(scylla_storage_proxy_coordinator_range_unavailable{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "C++ Exceptions instance",
   "type": "graph",
   "description": "Number of C++ exceptions thrown.\n\n A peak in the number of exceptions is an indication of a potential problem.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 193 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_reactor_cpp_exceptions{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 193 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 199 },
   "options": {
    "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
   },
   "content": "<h1 style=\"color:#5881c2; border-bottom: 3px solid #5881c2;\">I/O Queue</h1>"
  },
  {
   "title": "Compactions I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 201 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_compaction_delay{job=~\"scylla-default-metrics-exporter\"} ) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compactions I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_compaction_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)"
    }
   ]
  },
  {
   "title": "Query I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 201 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_query_delay{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 207 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_query_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 207 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 213 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_commitlog_delay{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Commitlog I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 213 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_commitlog_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 213 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_memtable_flush_delay{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memtable Flush I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 219 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_memtable_flush_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 219 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_read_delay{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Reads I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 225 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_read_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 225 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_operations{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "1000000*max(scylla_io_queue_streaming_write_delay{job=~\"scylla-default-metrics-exporter\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Streaming Writes I/O Queue bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 231 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(scylla_io_queue_streaming_write_total_bytes{job=~\"scylla-default-metrics-exporter\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}