---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: jenkins-agent
  namespace: obs
spec:
  serviceAccountSelector: role == 'jenkins-agent'
  types:
    - Ingress
    - Egress
  ingress:
    - metadata:
        annotations:
          from: jenkins-master
          to: jenkins-agent
      action: Allow
      source:
        selector: app.kubernetes.io/component == 'jenkins-master'
        namespaceSelector: projectcalico.org/name == 'jenkins'
  egress:
    - metadata:
        annotations:
          from: jenkins-agent
          to: jenkins-master
      action: Allow
      destination:
        selector: app.kubernetes.io/component == 'jenkins-master'
        namespaceSelector: projectcalico.org/name == 'jenkins'
    - metadata:
        annotations:
          from: jenkins-agent
          to: vpc
      action: Allow
      protocol: TCP
      destination:
        nets:
          - "{{ VPC_CIDR }}"
        ports:
          - 9042
    - metadata:
        annotations:
          from: jenkins-agent
          to: mgmt
      action: Allow
      protocol: TCP
      destination:
        nets:
          - 10.161.48.0/20
        ports:
          - 443
          - 80
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: obs-application
  namespace: obs
spec:
  types:
    - Egress
  egress:
    - metadata:
        annotations:
          from: obs-application
          to: vpc
      action: Allow
      source:
        serviceAccounts:
          names:
            - tsb-obs
            - default
      protocol: TCP
      destination:
        nets:
          - "{{ VPC_CIDR }}"
        ports:
          - 9042
          - 9142
          - 9092
          - 7790
          - 2181
          - 7788
          - 1883
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: obs-sa-policy
  namespace: obs
spec:
  types:
    - Egress
  egress:
    - metadata:
        annotations:
          from: obs-sa
          to: mgmt
      action: Allow
      source:
        serviceAccounts:
          names:
            - tsb-obs
            - default
      protocol: TCP
      destination:
        nets:
          - 10.161.48.0/20
        ports:
          - 80
          - 443
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: obs-nginx-ingress
  namespace: obs
spec:
  serviceAccountSelector: projectcalico.org/name == 'sa-tsb-ob-signing-service'
  types:
    - Ingress
  ingress:
    - metadata:
        annotations:
          from: vpc
          to: nginx
      action: Allow
      source:
        selector: vpc == 'local' && layer == 'all'
        namespaceSelector: global()
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: prometheus-ingress
  namespace: obs
spec:
  selector: namespace == 'cb'
  ingress:
    - action: Allow
      protocol: TCP
      source:
        selector: app == 'prometheus'
      destination:
        ports:
          - 8080
          - 3000