---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-obs
  namespace: obs
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-obs
  labels:
    role: jenkins-agent
    component: obs
