---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
spec:
  releaseName: jenkins
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
    version: 2.3.0
  values:
    master:
      image: jenkins/jenkins
      tag: lts-alpine
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
          external-dns.alpha.kubernetes.io/hostname: jenkins.{{ DNS_ZONE }}
      resources:
        limits:
          cpu: 500m
      # Environment variables that get added to the init container (useful for e.g. http_proxy)
      initContainerEnv:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal
      containerEnv:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal
    agent:
      image: jenkins/inbound-agent
      tag: 4.3-4
      componentName: jenkins-agent
      resources:
        limits:
          memory: 1Gi
      envVars:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal
      yamlTemplate: |-
        apiVersion: v1
        kind: Pod
        spec:
          securityContext:
            fsGroup: 1337
    serviceAccountAgent:
      create: true
      name: jenkins-agent
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/rax/jenkins