---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: jenkins
spec:
  releaseName: jenkins
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: jenkins
    version: 2.3.3
  values:
    master:
      image: jenkins/jenkins
      tag: lts-alpine
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8
          external-dns.alpha.kubernetes.io/hostname: jenkins.{{ DNS_ZONE }}
      resources:
        limits:
          cpu: 500m
      # Environment variables that get added to the init container (useful for e.g. http_proxy)
      initContainerEnv:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal,.cluster.local
      containerEnv:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal,.cluster.local
      installPlugins:
        - kubernetes:1.26.4
        - workflow-job:2.39
        - workflow-aggregator:2.6
        - credentials-binding:1.23
        - git:4.3.0
        - configuration-as-code:1.43
        - ansicolor:0.7.2
        - pipeline-aws:1.42
        - authorize-project:1.30
        - aws-global-configuration:1.5
        - command-launcher:1.4
        - custom-tools-plugin:0.7
        - docker-plugin:1.2.0 
        - envinject:2.3.0
        - extra-tool-installers:0.5
        - git-parameter:0.9.12
        - github-pullrequest:0.2.8
        - http_request:1.8.26
        - job-dsl:1.77
        - matrix-auth:2.6.2
        - jdk-tool:1.4
        - pipeline-utility-steps:2.6.1
        - pipeline-github:2.7
        - scm-filter-branch-pr:0.5.1
        - ws-cleanup:0.38
      JCasC:
        configScripts:
          github: |-
            unclassified:
              gitHubPluginConfig:
                hookUrl: "http://jenkins.{{ DNS_ZONE }}"
                configs:
                  - name: "GitHub"
                    credentialsId: "github"
                    manageHooks: true
          libraries: |-
            unclassified:
              globalLibraries:
                - name: "rax-jenkins-shared-library"
                  defaultVersion: "develop"
                  retriever:
                    modernSCM:
                      scm:
                        github:
                          credentialsId: "github-job"
                          repoOwner: "TSB-Bank"
                          repository: "rax-jenkins-shared-library"
                          traits:
                            - gitHubBranchDiscovery:
                                strategyId: 1
                            - gitHubPullRequestDiscovery:
                                strategyId: 1
                            - gitHubForkDiscovery:
                                strategyId: 1
                                trust: "gitHubTrustPermissions"
          proxy: |-
            jenkins:
              proxy:
                name: "eu-west-2.proxy.aws.uk.tsb"
                port: 3128
                noProxyHost: "localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal,.cluster.local"
      url: http://jenkins.{{ DNS_ZONE }}
      slaveJenkinsUrl: http://jenkins.jenkins.svc.cluster.local:8080
    agent:
      image: jenkins/inbound-agent
      tag: 4.3-4
      componentName: jenkins-agent
      resources:
        limits:
          memory: 1Gi
      envVars:
        - name: http_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: https_proxy
          value: http://eu-west-2.proxy.aws.uk.tsb:3128
        - name: no_proxy
          value: localhost,127.0.0.1,169.254.169.254,10.0.0.0/8,172.20.0.0/16,.eu-west-2.compute.internal,.eu-west-2.elb.amazonaws.com,vault.service.consul,ssm.eu-west-2.amazonaws.com,ssmmessages.eu-west-2.amazonaws.com,ec2.eu-west-2.amazonaws.com,ec2messages.eu-west-2.amazonaws.com,s3.eu-west-2.amazonaws.com,autoscaling.eu-west-2.amazonaws.com,secretsmanager.eu-west-2.amazonaws.com,kms.eu-west-2.amazonaws.com,ecr.eu-west-2.amazonaws.com,.eks.amazonaws.com,.ecr.eu-west-2.amazonaws.com,s3.amazonaws.com,.s3.eu-west-2.amazonaws.com,.internal,.cluster.local
      yamlTemplate: |-
        apiVersion: v1
        kind: Pod
        spec:
          securityContext:
            fsGroup: 1337
    additionalAgents:
      terraform:
        podName: terraform 
        componentName: jenkins-terraform
        yamlTemplate: |-
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins-terraform
      packer:
        podName: packer
        componentName: jenkins-packer
        yamlTemplate: |-
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins-packer