---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  selector: app.kubernetes.io/component == 'jenkins-master'
  types:
    - Ingress
    - Egress
  ingress:
    - metadata:
        annotations:
          from: lb
          to: jenkins-master
      action: Allow
      protocol: TCP
      source:
        nets:
          - "{{ VPC_CIDR }}"
      destination:
        ports:
          - 8080
    - metadata:
        annotations:
          from: jenkins-agent
          to: jenkins-master
      action: Allow
      source:
        serviceAccounts:
          selector: role == 'jenkins-agent'
          namespaceSelector: all()
  egress:
    - metadata:
        annotations:
          from: jenkins-master
          to: jenkins-agent
      action: Allow
      destination:
        serviceAccounts:
          selector: role == 'jenkins-agent'
          namespaceSelector: all()

---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  serviceAccountSelector: role == 'jenkins-agent'
  types:
    - Ingress
    - Egress
  ingress:
    - metadata:
        annotations:
          from: jenkins-master
          to: jenkins-agent
      action: Allow
      source:
        selector: app.kubernetes.io/component == 'jenkins-master'
  egress:
    - metadata:
        annotations:
          from: jenkins-agent
          to: jenkins-master
      action: Allow
      destination:
        selector: app.kubernetes.io/component == 'jenkins-master'

---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: jenkins-agent-packer
  namespace: jenkins
spec:
  serviceAccountSelector: role == 'jenkins-agent' && component == 'packer'
  types:
    - Egress
  egress:
    - metadata:
        annotations:
          from: jenkins-agent-packer
          to: vpc
      action: Allow
      protocol: TCP
      destination:
        nets:
          - "{{ VPC_CIDR }}"
        ports:
          - 22
          - 5985
          - 5986