---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-terraform
  namespace: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/jenkins-terraform

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-packer
  namespace: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/jenkins-packer