---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cb-admin-role
  namespace: cb
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cb-admin-binding
  namespace: cb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cb-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-cb
  - kind: Group
    name: cb-admin
  - kind: ServiceAccount
    name: jenkins-terraform
    namespace: jenkins