apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cob-pod-restart-alerts
  namespace: prometheus
spec:
  groups:
    - name: COB_PODS_RESTART_STATE
      rules:
  ###########################################COP_APP_ALL_DOWN_CRITICAL##########################################################
        - record: cob_pod_restart_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_pod_container_status_restarts_total{namespace="cob", pod=~"tsb-onboarding.*"} offset 5m)
        - alert: COB_pod_restart_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: cob_pod_restart_critical_{{ AWS_ENVIRONMENT }} > 2
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cob
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_AWS
            itopsbridge: "true"
          annotations:
            description: 'Conatainer {{ $labels.container }} in the Pod {{ $labels.pod }} has been restarted more than 3 in lat 5m restart count:{{ $value }}'
            summary: Critical conatainer {{ $labels.container }} restarting indicates that the pod  {{ $labels.pod }} is unhealthy.

