apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cob-email-responsetime-alerts
  namespace: prometheus
spec:
  groups:
  - name: COB_APPS_RESPONSETIME_STATE
    rules:
    - record: cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}
      expr: sum by (namespace, routeId)(rate(gateway_requests_seconds_sum{routeId="tsb-onboarding-restproxy-email-verification", namespace="cob"}[5m]))/ sum by (namespace, routeId)(rate(gateway_requests_seconds_count{routeId="tsb-onboarding-restproxy-email-verification", namespace="cob"}[5m]))
    - alert: COB_app_verify_email_critical_alert_{{ AWS_ENVIRONMENT }}
      expr: (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) > .6
      for: 5s
      labels:
        action: Application will be impacted
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: RED
        platform: AWS
        namespace: cob
        severity: CRITICAL
        priority: P3
        type: 8x5
        tsbci: SCO_AWS
        itopsbridge: "true"
      annotations:
        description: 'Application {{ $labels.job }} response time is more than 600 ms :{{ $value }}'
        summary: 'Red alert for response time reached for application'
        #################################################################
    - alert: COB_app_verify_email_high_alert_{{ AWS_ENVIRONMENT }}
      expr: (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) > .525 and (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) <=.6
      for: 5s
      labels:
        action: Application will be impacted
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: YELLOW
        platform: AWS
        namespace: cob
        severity: MAJOR
        priority: P4
        type: 8x5
        tsbci: SCO_AWS
        itopsbridge: "true"
      annotations:
        description: 'Application {{ $labels.job }} response time is more than 525 ms :{{ $value }}'
        summary: 'Yellow alert for response time reached for application'
        ###################################################################
    - alert: COB_app_verify_email_medium_alert_{{ AWS_ENVIRONMENT }}
      expr: (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) > .450 and (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) <=.525
      for: 5s
      labels:
        action: Application will be impacted
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: YELLOW
        platform: AWS
        namespace: cob
        severity: MINOR
        priority: P4
        type: 8x5
        tsbci: SCO_AWS
        itopsbridge: "true"
      annotations:
        description: 'Application {{ $labels.job }} response time is more than 450 ms :{{ $value }}'
        summary: 'Yellow alert for response time reached for application'
        #################################################################
    - alert: COB_app_verify_email_low_alert_{{ AWS_ENVIRONMENT }}
      expr: (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) > .375 and (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) <=.450
      for: 5s
      labels:
        action: Application is likely impacted
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: YELLOW
        platform: AWS
        namespace: cob
        severity: MINOR
        priority: P4
        type: 8x5
        tsbci: SCO_AWS
        itopsbridge: "true"
      annotations:
        description: 'Application {{ $labels.job }} response time is more than 375 ms :{{ $value }}'
        summary: 'Yellow alert for response time reached for application'
        ######################################################################
    - alert: COB_app_verify_email_warning_alert_{{ AWS_ENVIRONMENT }}
      expr: (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) > .300 and (cob_app_verify_email_response_time_{{ AWS_ENVIRONMENT }}) <=.375
      for: 5s
      labels:
        action: Application is likely impacted
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: GREEN
        platform: AWS
        namespace: cob
        severity: WARNING
        priority: P4
        type: 8x5
        tsbci: SCO_AWS
        itopsbridge: "true"
      annotations:
        description: 'Application {{ $labels.job }} response time is more than 300 ms :{{ $value }}'
        summary: 'Green alert for response time reached for application'

