apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: prometheus
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
    inhibit_rules:
      - source_match:
          severity: 'CRITICAL'
        target_match:
          severity: 'WARNING'
        equal: ['deployment']
      - source_match:
          severity: 'CRITICAL'
        target_match:
          severity: 'WARNING'
        equal: ['statefulset'] 
    receivers:
      - name: "null"
      - name: itom-dev-servicenow
        webhook_configs:
        - url: "https://tsbbankdev1.service-now.com/api/itsbb/alertmanager"
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
            basic_auth:
              username: 'prometheus_user'
              password_file: '/etc/alertmanager/secrets/servicenow-secret/servicenow_pw.txt'
      - name: itom-test-servicenow
        webhook_configs:
        - url: "https://tsbbanktest1.service-now.com/api/itsbb/alertmanager"
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
            basic_auth:
              username: 'prometheus_user'
              password_file: '/etc/alertmanager/secrets/servicenow-secret/servicenow_pw.txt'
      - name: itom-prod-servicenow
        webhook_configs:
        - url: "https://tsbprod001.service-now.com/api/itsbb/alertmanager"
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
            basic_auth:
              username: 'prometheus_user'
              password_file: '/etc/alertmanager/secrets/servicenow-secret/servicenow_pw.txt'
      - name: rax-monitoring-email
        webhook_configs:
        - url: "http://alertmanager-sns-forwarder-svc:9087/alert/{{ AWS_ENVIRONMENT }}-rax-alertmanager"
          send_resolved: true
      - name: itops-monitoring-email
        webhook_configs:
        - url: "http://alertmanager-sns-forwarder-svc:9087/alert/{{ AWS_ENVIRONMENT }}-itops-alertmanager"
          send_resolved: false
      - name: cmos-event-management
        webhook_configs:
        - url: "https://webhook.cmos-eventmanagement.com:9443/probe/webhook"
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: rax-pagerduty-critical
        pagerduty_configs:
        - routing_key: "{{ SECRET_RAX_PAGERDUTY_KEY }}"
          severity: critical
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: rax-pagerduty-error
        pagerduty_configs:
        - routing_key: "{{ SECRET_RAX_PAGERDUTY_KEY }}"
          severity: error
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: rax-pagerduty-warning
        pagerduty_configs:
        - routing_key: "{{ SECRET_RAX_PAGERDUTY_KEY }}"
          severity: warning
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: rax-pagerduty-info
        pagerduty_configs:
        - routing_key: "{{ SECRET_RAX_PAGERDUTY_KEY }}"
          severity: info
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: "sns-forwarder-cdcalerts"
        webhook_configs:
        - url: "http://alertmanager-sns-forwarder-svc:9087/alert/tsb-CDCalerts"
          send_resolved: true
      - name: "sns-forwarder-cbcriticalalerts"
        webhook_configs:
        - url: "http://alertmanager-sns-forwarder-svc:9087/alert/cb-criticalalerts"
          send_resolved: true
      - name: 'cb-slack-notifications'
        slack_configs:
        - channel: '#cb_alert_notifications'
          api_url: 'https://hooks.slack.com/services/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'
          icon_url: 'https://github.com/prometheus/docs/raw/master/static/prometheus_logo.png'
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .CommonAnnotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .CommonAnnotations.description }}
            {{ end }}
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: 'cb-slack-notifications-new'
        slack_configs:
        - channel: '#cb_alerts_pre_prod'
          api_url: 'https://hooks.slack.com/services/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'
          icon_url: 'https://github.com/prometheus/docs/raw/master/static/prometheus_logo.png'
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: 'cb-critical-slack-notifications'
        slack_configs:
        - channel: '#cb_alerts_critical_prod'
          api_url: 'https://hooks.slack.com/services/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'
          icon_url: 'https://github.com/prometheus/docs/raw/master/static/prometheus_logo.png'
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: 'cb-warning-slack-notifications'
        slack_configs:
        - channel: '#cb_alerts_warning_prod'
          api_url: 'https://hooks.slack.com/services/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'
          icon_url: 'https://github.com/prometheus/docs/raw/master/static/prometheus_logo.png'
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
            {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
              {{" "}}(
              {{- with .CommonLabels.Remove .GroupLabels.Names }}
                {{- range $index, $label := .SortedPairs -}}
                  {{ if $index }}, {{ end }}
                  {{- $label.Name }}="{{ $label.Value -}}"
                {{- end }}
              {{- end -}}
              )
            {{- end }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            {{ end }}
          send_resolved: true
          http_config:
            proxy_url: "http://eu-west-2.proxy.aws.uk.tsb:3128"

    route:
      group_by: ['...']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 30m
      receiver: "null"
      routes:
        #- match_re:
        #    namespace: cb
        #    group: INFRA
        #    environment: preprod|prod
        #  receiver: sns-forwarder-cbalerts
        #  continue: true
        - match:
            namespace: cb
            group: INFRA
            environment: prod
            severity: CRITICAL
          receiver: sns-forwarder-cbcriticalalerts
          continue: true
        - match_re:
            environment: preprod|prod
            application: cdc
          receiver: sns-forwarder-cdcalerts
          continue: true
        - match:
            namespace: cb
            group: INFRA
            environment: prod
          receiver: cb-slack-notifications
          continue: true
        - match_re:
            namespace: cb
            group: INFRA
            environment: preprod
            severity: WARNING|CRITICAL
          receiver: cb-slack-notifications-new
          continue: true
        - match:
            namespace: cb
            group: INFRA
            environment: prod
            severity: CRITICAL
          receiver: cb-critical-slack-notifications
          continue: true
        - match:
            namespace: cb
            group: INFRA
            environment: prod
            severity: WARNING
          receiver: cb-warning-slack-notifications
          continue: true
        - match_re:
            priority: P1
            rackspace: "true"
            environment: preprod|prod
          receiver: rax-pagerduty-critical
          continue: true
        - match_re:
            priority: P2
            rackspace: "true"
            environment: preprod|prod
          receiver: rax-pagerduty-error
          continue: true
        - match_re:
            priority: P3
            rackspace: "true"
            environment: preprod|prod
          receiver: rax-pagerduty-warning
          continue: true
        - match_re:
            priority: P4
            rackspace: "true"
            environment: preprod|prod
          receiver: rax-pagerduty-info
          continue: true
        - match_re:
            rackspace: "true"
            environment: dev|nonprod
          receiver: rax-pagerduty-info
          continue: true
        - match_re:
            severity: CRITICAL
            rackspace: "true"
            environment: preprod|prod
          receiver: rax-monitoring-email
          continue: true
        - match_re:
            environment: preprod|prod
          receiver: itom-dev-servicenow
          continue: true
        - match_re:
            severity: ^(CRITICAL|WARNING)
            environment: preprod|prod
          receiver: itom-test-servicenow
          continue: true
        - match_re:
            environment: prod
          receiver: itom-prod-servicenow
          continue: true
        - match_re:
            itopsbridge: "true"
            environment: prod  
          receiver: itops-monitoring-email
          continue: true
        - match_re:
            environment: preprod|prod
            application: cdc
          receiver: cmos-event-management
          continue: true
        - match_re:
            environment: preprod|prod    
            application: cdc
            severity: ^(CRITICAL|WARNING)
          receiver: rax-pagerduty-critical  
