---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dl-cwexporter
  namespace: prometheus
spec:
  releaseName: dl-cwexporter
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-cloudwatch-exporter
    version: 0.14.1
  values:
    ## helm upgrade dl-cwexporter -n prometheus prometheus-community/prometheus-cloudwatch-exporter --version 0.14.1 -f values-min.yaml
    replicaCount: 1
    command:
      - 'java'
      - '-Dhttp.proxyHost=eu-west-2.proxy.aws.uk.tsb'
      - '-Dhttp.proxyPort=3128'
      - '-Dhttps.proxyHost=eu-west-2.proxy.aws.uk.tsb'
      - '-Dhttps.proxyPort=3128'
      - '-Dhttp.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|10.0.0.0/8|.internal|.eu-west-2.elb.amazonaws.com|vault.service.consul|ssm.eu-west-2.amazonaws.com|ssmmessages.eu-west-2.amazonaws.com|ec2.eu-west-2.amazonaws.com|ec2messages.eu-west-2.amazonaws.com|s3.eu-west-2.amazonaws.com|autoscaling.eu-west-2.amazonaws.com|secretsmanager.eu-west-2.amazonaws.com|kms.eu-west-2.amazonaws.com|ecr.eu-west-2.amazonaws.com|.eks.amazonaws.com|.ecr.eu-west-2.amazonaws.com|.s3.eu-west-2.amazonaws.com|.aws.uk.tsb'
      - '-Dhttps.nonProxyHosts=localhost|127.0.0.1|169.254.169.254|10.0.0.0/8|.internal|.eu-west-2.elb.amazonaws.com|vault.service.consul|ssm.eu-west-2.amazonaws.com|ssmmessages.eu-west-2.amazonaws.com|ec2.eu-west-2.amazonaws.com|ec2messages.eu-west-2.amazonaws.com|s3.eu-west-2.amazonaws.com|autoscaling.eu-west-2.amazonaws.com|secretsmanager.eu-west-2.amazonaws.com|kms.eu-west-2.amazonaws.com|ecr.eu-west-2.amazonaws.com|.eks.amazonaws.com|.ecr.eu-west-2.amazonaws.com|.s3.eu-west-2.amazonaws.com|.aws.uk.tsb'
      - '-Daws.region=eu-west-2'
      - '-jar'
      - '/cloudwatch_exporter.jar'
      - '9106'
      - '/config/config.yml'

    containerPort: 9106

    service:
      type: ClusterIP
      port: 9106
      portName: http
      annotations: {}
      labels: {}

    # pod:
    #   labels:
    #     app: tsb-datalake

    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi


    aws:
      role: prometheus-thanos-s3
      # Enables usage of regional STS endpoints rather than global which is default
      stsRegional:
        enabled: false

      secret:
        name:
        includesSessionToken: false

    serviceAccount:
      create: false
      name: prometheus-sa
    rbac:
      create: true

    # Configuration is rendered with `tpl` function, therefore you can use any Helm variables and/or templates here
    config: |-
      region: eu-west-2
      period_seconds: 240
      metrics:
      - aws_namespace: AWS/RDS
        aws_metric_name: BurstBalance
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: CPUUtilization
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: CPUCreditBalance
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: DiskQueueDepth
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: FreeableMemory
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: FreeStorageSpace
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/RDS
        aws_metric_name: SwapUsageThreshold
        aws_dimensions: [DBInstanceIdentifier]
        aws_dimension_select_regex:
          DBInstanceIdentifier: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/SQS
        aws_metric_name: ApproximateNumberOfMessagesVisible
        aws_dimensions: [QueueName]
        aws_dimension_select_regex:
          QueueName: ["^tsb-datalake.*$"]
      - aws_namespace: AWS/SQS
        aws_metric_name: ApproximateAgeOfOldestMessage
        aws_dimensions: [QueueName]
        aws_dimension_select_regex:
          QueueName: ["^tsb-datalake.*$"]
      - aws_namespace: AWS/Lambda
        aws_metric_name: Errors
        aws_dimensions: [FunctionName]
        aws_dimension_select_regex:
          FunctionName: ["^tsb-datalake.*$"]
        aws_statistics: [Average]
      - aws_namespace: AWS/Glue
        aws_metric_name: "glue.driver.aggregate.numFailedTasks"
        aws_dimensions: [JobName]
        aws_dimension_select_regex:
          JobName: ["^tsb-datalake.*$"]
        aws_statistics: [Sum]
      - aws_namespace: AWS/States
        aws_metric_name: ExecutionsFailed
        aws_dimensions: [StateMachineArn]
        aws_dimension_select_regex:
          StateMachineArn: [".*tsb-datalake.*$"]
        aws_statistics: [Sum]
      - aws_namespace: AWS/States
        aws_metric_name: ExecutionsTimedOut
        aws_dimensions: [StateMachineArn]
        aws_dimension_select_regex:
          StateMachineArn: [".*tsb-datalake.*$"]
        aws_statistics: [Sum]
      - aws_namespace: CloudTrailMetrics
        aws_metric_name: EmrSecurityChangesEventCount
        period_seconds: 120
        aws_statistics: [Sum]
      - aws_namespace: CloudTrailMetrics
        aws_metric_name: EmrJobFlowsUnauthorizedCount
        aws_statistics: [Sum]
        period_seconds: 120
      - aws_namespace: tsb-datalake-cb
        aws_metric_name: CbGlueInError
      - aws_namespace: tsb-datalake-push
        aws_metric_name: PushGlueInError
      - aws_namespace: tsb-datalake-navilog
        aws_metric_name: NavilogGlueInError
      - aws_namespace: tsb-datalake-sco
        aws_metric_name: ScoGlueInError
      - aws_namespace: tsb-datalake-gdpr
        aws_metric_name: GdprGlueInError
      - aws_namespace: tsb-datalake-cop
        aws_metric_name: CopGlueInError

    # Configurable health checks against the /healthy and /ready endpoints
    livenessProbe:
      path: /-/healthy
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    readinessProbe:
      path: /-/ready
      initialDelaySeconds: 120
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    serviceMonitor:
      enabled: true
      namespace: prometheus
      interval: 240s
      telemetryPath: /metrics
      timeout: 10s
