apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sca-stepup-auth-api-failure-rate-alertrule-alerts
  namespace: prometheus
spec:
  groups:
    - name: sca_stepup_auth_api_failure_rate
      rules:
  ###########################################Failure Rate for Stepup Auth##########################################################                 
        - record: stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca",outcome!="SUCCESS", uri=~".*stepup-auth-response"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca", uri=~".*stepup-auth-response"}[5m]))) * 100
      
        - alert: stepup_auth_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: stepup_auth_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: stepup_auth_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (stepup_auth_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Validate pwd##########################################################                 
        - record: validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca",outcome!="SUCCESS", uri=~".*validate-pwd"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca", uri=~".*validate-pwd"}[5m]))) * 100
        
        - alert: validate_pwd_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: validate_pwd_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
            
        - alert: validate_pwd_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (validate_pwd_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
