apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cdc-down-alerts
  namespace: prometheus
spec:
  groups:
  - name: CDC_Alerts
      
    rules:
    - record: datastore_state
      expr: (datastore_state)

    - alert: datastore_state
      expr: (datastore_state) < 1
      for: 2m
      labels:
        environment: "{{ AWS_ENVIRONMENT }}"
        level: CRITICAL
        platform: AWS
        severity: CRITICAL
        application: cdc
      annotations:
        Description: '***Data of CDC_Subscription {{ $labels.subscription }} is not available. Value:{{ $value }}'
        Summary: Alert CDC- {{ $labels.subscription }} is not available

    - alert: datastore_state
      expr: (datastore_state{state="Mirror Continuous"}) < 1
      for: 2m
      labels:
        environment: "{{ AWS_ENVIRONMENT }}"
        level: CRITICAL
        platform: AWS
        severity: CRITICAL
        application: cdc
      annotations:
        Description: '***State of {{ $labels.subscription }} is not Mirror Continuous. Value:{{ $value }}'
        Summary: Alert CDC- State of {{ $labels.subscription }} is not Mirror Continuous

    