apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop-s3-sink-alerts
  namespace: prometheus
spec:
  groups:
  - name: COP_S3_SINK_APP_ALERTS
    rules:
  ##################COP_S3SINK_OUTBOUND - more than 20 requests failure  per minutes for last 5 minutes? ########################################################## 
    - record: cop_tsb_cop_outbound_s3_sink_totalcount20{{ AWS_ENVIRONMENT }}
      expr: (sum by (job, namespace) (rate(tsb_cop_outbound_s3_sink_total {namespace="cop"}[5m]))*60)          
    - alert: COP_tsb_cop_outbound_s3_sink_totalcount20_red_alert_{{ AWS_ENVIRONMENT }}
      expr: (cop_tsb_cop_outbound_s3_sink_totalcount20{{ AWS_ENVIRONMENT }}) > 20
      for: 5m
      labels:
        action: Closely monitor
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: RED
        platform: AWS
        namespace: cop
        severity: CRITICAL
        priority: P4
        type: 8x5
        tsbci: COP
      annotations:
        description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with failure count more than 20 times in 5 min. Value: {{ $value }}'
        summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}} 
  ##################COP_S3SINK_INBOUND - more than 20 requests failure  per minutes for last 5 minutes? ########################################################## 
    - record: cop_tsb_cop_inbound_s3_sink_totalcount20{{ AWS_ENVIRONMENT }}
      expr: (sum by (job, namespace) (rate(tsb_cop_inbound_s3_sink_total {namespace="cop"}[5m]))*60)          
    - alert: COP_tsb_cop_inbound_s3_sink_totalcount20_red_alert_{{ AWS_ENVIRONMENT }}
      expr: (cop_tsb_cop_inbound_s3_sink_totalcount20{{ AWS_ENVIRONMENT }}) > 20
      for: 5m
      labels:
        action: Closely monitor
        environment: "{{ AWS_ENVIRONMENT }}"
        group: INFRA
        level: RED
        platform: AWS
        namespace: cop
        severity: CRITICAL
        priority: P4
        type: 8x5
        tsbci: COP
      annotations:
        description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with failure count more than 20 times in 5 min. Value: {{ $value }}'
        summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}} 
