apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sca-transaction-query-api-failure-rate-alerts
  namespace: prometheus
spec:
  groups:
    - name: sca_transaction_query_api_failure_rate
      rules:
  ###########################################Failure Rate for Get Transaction##########################################################
        - record: get_transaction_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca",outcome!="SUCCESS", uri=~".*transaction"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca", uri=~".*transaction"}[5m]))) * 100

        - alert: get_transaction_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((get_transaction_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((get_transaction_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
        
        - alert: get_transaction_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((get_transaction_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((get_transaction_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
        
        - alert: get_transaction_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (get_transaction_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Transactions by userid##########################################################          
        - record: transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca",outcome!="SUCCESS", uri=~".*transactions-by-userid"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sca", uri=~".*transactions-by-userid"}[5m]))) * 100

        - alert: transactions_by_userid_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
        
        - alert: transactions_by_userid_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: transactions_by_userid_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (transactions_by_userid_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}