apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop-down-alerts
  namespace: prometheus
spec:
  groups:
    - name: COP_APPS_DOWN_STATE
      rules:
  ###########################################COP_APP_ALL_DOWN_CRITICAL##########################################################
        - record: cop_app_all_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{deployment=~"tsb-cop.*",namespace="cop"})
        - alert: COP_app_all_down_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop_app_all_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no pods running
    ###########################################COP_APP_ALL_DOWN_CRITICAL##########################################################
        - record: cop_app_all_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_statefulset_status_replicas_ready{statefulset=~"tsb-cop.*",namespace="cop"})
        - alert: COP_app_all_down_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop_app_all_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running
    ###########################################COP_NGINX_CONTROLLER_DOWN_CRITICAL##########################################################
        - record: cop_nginx_controller_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{deployment="tsb-cop-api-gateway-ingress-nginx-controller",namespace="cop"})
        - alert: COP_NGINX_controller_down_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop_nginx_controller_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no pods running   
