apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sca-authentication-api-responsetime-alerts
  namespace: prometheus
spec:
  groups:
    - name: sca_authentication_api_responsetime
      rules:
  ###########################################Response Time for Auth Method##########################################################
        - record: auth_method_responsetime_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace="sca",uri=~".*auth-method"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sca",uri=~".*auth-method"}[5m]))

        - alert: auth_method_responsetime_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((auth_method_responsetime_{{ AWS_ENVIRONMENT }}) > 0.005) and ((auth_method_responsetime_{{ AWS_ENVIRONMENT }}) < 0.100) # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 3s for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}

        - alert: auth_method_responsetime_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (auth_method_responsetime_{{ AWS_ENVIRONMENT }}) > 0.100 # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 4s for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}
    ###########################################Response Time for Init App##########################################################
        - record: init_app_responsetime_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace="sca",uri=~".*init-app-auth"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sca",uri=~".*init-app-auth"}[5m]))

        - alert: init_app_responsetime_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((init_app_responsetime_{{ AWS_ENVIRONMENT }}) > 0.005) and ((init_app_responsetime_{{ AWS_ENVIRONMENT }}) < 0.100) # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 3s for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}

        - alert: init_app_responsetime_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (init_app_responsetime_{{ AWS_ENVIRONMENT }}) > 0.100 # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 4s for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}
    ###########################################Response Time for Send otp##########################################################
        - record: send_otp_responsetime_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum {namespace="sca",uri=~".*send-otp"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sca",uri=~".*send-otp"}[5m]))

        - alert: send_otp_responsetime_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((send_otp_responsetime_{{ AWS_ENVIRONMENT }}) > 0.005) and ((send_otp_responsetime_{{ AWS_ENVIRONMENT }}) < 0.100) # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sca
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 3s for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}

        - alert: send_otp_responsetime_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (send_otp_responsetime_{{ AWS_ENVIRONMENT }}) > 0.100 # Responsetime will be provided by NFT team
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sca
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCA_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 4s for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}
