apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop2-outbound-app-state-alerts
  namespace: prometheus
spec:
  groups:
    - name: COP2_OUTBOUND_FLOW_APPS_STATE
      rules:
        ################## No Requests for 20 minutes ##########################################################
        - record: cop2_outbound_no_request_{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job) (rate(http_server_requests_seconds_count {namespace="cop-phase2", method="POST", uri=~".*outbound.*|.*authorisation.*"}[1m])*60))
        - alert: COP2_no_request_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_outbound_no_request_{{ AWS_ENVIRONMENT }}) == 0
          for: 19m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: cop-phase2
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached no requests since 20 minutes'
            summary: No requests received by Application {{ $labels.job }} Endpoint {{$labels.uri}} for last 20 minutes

        ################## 20 50x errors in 10 minutes ##########################################################
        - record: cop2_outbound_status_50x_count_{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job) (rate(http_server_requests_seconds_count {namespace="cop-phase2", status=~"50.*", uri=~".*outbound.*|.*authorisation.*"}[10m])*60))
        - alert: COP2_outbound_status_50x_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_outbound_status_50x_count_{{ AWS_ENVIRONMENT }}) > 20
          for: 10m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 50x more than 20 times in 10 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}
        ################## 20 40x errors in 10 minutes ##########################################################
        - record: cop2_outbound_status_40x_count_{{ AWS_ENVIRONMENT }}
          expr:  (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2", status=~"40.*", uri=~".*outbound.*|.*authorisation.*"}[10m]))*60)
        - alert: COP2_outbound_status_40x_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_outbound_status_40x_count_{{ AWS_ENVIRONMENT }}) > 20
          for: 10m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 50x more than 20 times in 10 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

        ################## Response Time more than 3.5 ##########################################################
        - record: cop2_outbound_obconnect_response_time_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job) (rate(http_server_requests_seconds_sum {namespace="cop-phase2", uri=~".*outbound.*|.*authorisation.*"}[5m])) / sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="cop-phase2", uri=~".*outbound.*|.*authorisation.*"}[5m]))
        - alert: COP2_outbound_obconnect_response_time_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_outbound_obconnect_response_time_{{ AWS_ENVIRONMENT }}) > 0.1
          for: 20m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: cop-phase2
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 3.5s for last 20 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}
