apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sco-fl-restproxy-api-stage1-failure-rate-alerts
  namespace: prometheus
spec:
  groups:
    - name: sco_fl_restproxy_api_stage1-failure_rate
      rules:
  ###########################################Failure Rate for Eligibility-Start API##########################################################                 
        - record: eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/eligibility"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/eligibility"}[5m]))) * 100

        - alert: eligibility_start_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: eligibility_start_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: eligibility_start_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (eligibility_start_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Eligibility-Report API##########################################################                 
        - record: eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/eligibility/status"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/eligibility/status"}[5m]))) * 100

        - alert: eligibility_report_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: eligibility_report_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: eligibility_report_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (eligibility_report_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Application-Start API##########################################################                 
        - record: application_start_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan"}[5m]))) * 100
        
        - alert: application_start_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((application_start_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((application_start_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: application_start_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((application_start_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((application_start_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: application_start_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (application_start_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Application-Report API##########################################################                 
        - record: application_report_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/status"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/status"}[5m]))) * 100
        
        - alert: application_report_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((application_report_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((application_report_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: application_report_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((application_report_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((application_report_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: application_report_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (application_report_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Block-Customer API##########################################################                 
        - record: block_customer_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/block"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/block"}[5m]))) * 100
        
        - alert: block_customer_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((block_customer_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((block_customer_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: block_customer_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((block_customer_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((block_customer_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: block_customer_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (block_customer_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}