apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop2-low-replica-count-alerts
  namespace: prometheus
spec:
  groups:
    - name: COP2_LOW_REPLICA_COUNT_STATE
      rules:
  ###########################################COP2_REPLICA_COUNT##########################################################
        - record: cop2_low_replica_count_critical_{{ AWS_ENVIRONMENT }}
          expr:  (kube_deployment_status_replicas_available{deployment=~"tsb-cop2.*",namespace="cop-phase2"}) - on(deployment) label_replace(kube_hpa_spec_min_replicas{namespace="cop-phase2"}, "deployment", "$1", "hpa", "(.+)")
        - alert: cop2_app_low_replica_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: cop2_low_replica_count_critical_{{ AWS_ENVIRONMENT }} <= 0
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Deployment {{ $labels.deployment }} current replica count is less than minimum replica count. Value:{{ $value }}'
            summary: Critical alert deployment {{ $labels.deployment }} running with replica less than minimum.
        - alert: cop2_app_low_replica_warning_alert_{{ AWS_ENVIRONMENT }}
          expr: cop2_low_replica_count_warning_{{ AWS_ENVIRONMENT }} < 3
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: WARNING
            platform: AWS
            namespace: cop-phase2
            severity: WARNING
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Deployment {{ $labels.deployment }} current replica count is less than normal replica count. Value:{{ $value }}'
            summary: warning alert deployment {{ $labels.deployment }} running with replica less than normal value. 
