apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop2-down-alerts
  namespace: prometheus
spec:
  groups:
    - name: COP2_APPS_DOWN_STATE
      rules:
        ###########################################COP2_APP_REPLICAS_DOWN_CRITICAL##########################################################
        - record: tsb_cop2_api_gateway_replica_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-api-gateway"})
        - alert: COP2_replica_down_tsb_cop2_api_gateway_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_api_gateway_replica_down_critical_{{ AWS_ENVIRONMENT }}) < 12
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no replicas running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no replicas running
        - record: tsb_cop2_fetch_name_details_replica_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-fetch-name-details"})
        - alert: COP2_replica_down_tsb_cop2_fetch_name_details_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_fetch_name_details_replica_down_critical_{{ AWS_ENVIRONMENT }}) < 12
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no replicas running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no replicas running
        - record: tsb_cop2_hmac_validator_replica_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-hmac-validator"})
        - alert: COP2_replica_down_tsb_cop2_hmac_validator_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_hmac_validator_replica_down_critical_{{ AWS_ENVIRONMENT }}) < 12
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no replicas running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no replicas running
        - record: tsb_cop2_mi_topology_replica_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-mi-topology"})
        - alert: COP2_replica_down_tsb_cop2_mi_topology_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_mi_topology_replica_down_critical_{{ AWS_ENVIRONMENT }}) < 9
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no replicas running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no replicas running
        - record: tsb_cop2_outbound_obconnect_replica_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-outbound-obconnect"})
        - alert: COP2_replica_down_tsb_cop2_outbound_obconnect_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_outbound_obconnect_replica_down_critical_{{ AWS_ENVIRONMENT }}) < 15
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.deployment }} of job {{ $labels.job }} has no replicas running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.deployment }} of job {{ $labels.job }} has no replicas running
        ###########################################COP_APP_ALL_POD_DOWN_CRITICAL##########################################################
        - record: tsb_cop2_api_gateway_pod_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-api-gateway"})
        - alert: COP2_all_pod_down_tsb_cop2_api_gateway_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_api_gateway_pod_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running
        - record: tsb_cop2_fetch_name_details_pod_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-fetch-name-details"})
        - alert: COP2_all_pod_down_tsb_cop2_fetch_name_details_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_fetch_name_details_pod_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running
        - record: tsb_cop2_hmac_validator_pod_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-hmac-validator"})
        - alert: COP2_all_pod_down_tsb_cop2_hmac_validator_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_hmac_validator_pod_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running
        - record: tsb_cop2_mi_topology_pod_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-mi-topology"})
        - alert: COP2_all_pod_down_tsb_cop2_mi_topology_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_mi_topology_pod_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running
        - record: tsb_cop2_outbound_obconnect_pod_down_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_deployment_status_replicas_available{namespace="cop-phase2", deployment="tsb-cop2-outbound-obconnect"})
        - alert: COP2_all_pod_down_tsb_cop2_outbound_obconnect_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: (tsb_cop2_outbound_obconnect_pod_down_critical_{{ AWS_ENVIRONMENT }}) < 1
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP_AWS
            itopsbridge: "true"
          annotations:
            description: '{{ $labels.statefulset }} of job {{ $labels.job }} has no pods running. Value:{{ $value }}'
            summary: Critical deployment {{ $labels.statefulset }} of job {{ $labels.job }} has no pods running

        ###########################################COP2_POD_RESTART_WARNING##########################################################
        - record: cop2_pod_restart_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_pod_container_status_restarts_total{namespace="cop-phase2", pod=~"tsb-cop2.*"} offset 5m)
        - alert: cop2_pod_restart_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: cop2_pod_restart_critical_{{ AWS_ENVIRONMENT }} >=3
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: WARNING
            platform: AWS
            namespace: cop-phase2
            severity: WARNING
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'POD {{ $labels.pod }} for Microservice {{ $labels.container }} restarted 3 times or more in last 5m. Restart Count:{{ $value }}'
            summary: Warning Alert POD {{ $labels.pod }} restart indicates that its not healthy.
        ###########################################COP2_POD_RESTART_CRITICAL##########################################################
        - record: cop2_pod_restart_critical_{{ AWS_ENVIRONMENT }}
          expr: (kube_pod_container_status_restarts_total{namespace="cop-phase2", pod=~"tsb-cop2.*"} offset 5m)
        - alert: cop2_pod_restart_critical_alert_{{ AWS_ENVIRONMENT }}
          expr: cop2_pod_restart_critical_{{ AWS_ENVIRONMENT }} >=6
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: CRITICAL
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'POD {{ $labels.pod }} for Microservice {{ $labels.container }} restarted 6 times or more in last 5m. Restart Count:{{ $value }}'
            summary: Critical Alert POD {{ $labels.pod }} restart indicates that its not healthy.
