apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sco-fl-responsetime-alerts
  namespace: prometheus
spec:
  groups:
    - name: SCO_FL_APP_RESPONSE_TIME
      rules:
  ##########################Response Time for first set of APIs#########################################################
        - record: sco_fl_app_response_time_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum{namespace="sco",uri=~".*/customer/loan/eligibility/status.*|.*/customer/loan.*|.*/customer/loan/status.*|.*/customer/loan/block.*|.*/customer/loan/{applycode}/status.*|.*/customer/loan/{applycode}/cca.*"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sco",uri=~".*/customer/loan/eligibility/status.*|.*/customer/loan.*|.*/customer/loan/status.*|.*/customer/loan/block.*|.*/customer/loan/{applycode}/status.*|.*/customer/loan/{applycode}/cca.*"}[5m]))
        - alert: SCO_FL_app_response_time_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app_response_time_{{ AWS_ENVIRONMENT }}) > 0.78 and (sco_fl_app_response_time_{{ AWS_ENVIRONMENT }}) <= 1.04
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 780ms for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}
        - alert: SCO_FL_app_response_time_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app_response_time_{{ AWS_ENVIRONMENT }}) > 1.04
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 1040ms for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}
            
  ########################Response Time eligibilitystart - confirm-pcci - get-confirm-pcci#############################################
        - record: sco_fl_app1_response_time_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum{namespace="sco",uri=~".*/customer/loan/eligibility.*|.*/customer/loan/{applycode}/pcci.*|.*/customer/loan/pcci.*"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sco",uri=~".*/customer/loan/eligibility.*|.*/customer/loan/{applycode}/pcci.*|.*/customer/loan/pcci.*"}[5m]))
        - alert: SCO_FL_app1_response_time_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app1_response_time_{{ AWS_ENVIRONMENT }}) > 0.9 and (sco_fl_app1_response_time_{{ AWS_ENVIRONMENT }}) <= 1.2
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 900ms for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}
        - alert: SCO_FL_app1_response_time_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app1_response_time_{{ AWS_ENVIRONMENT }}) > 1.2
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 1200ms for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}
            
  ########################Response Time - calculator-getquote#############################################
        - record: sco_fl_app2_response_time_{{ AWS_ENVIRONMENT }}
          expr: sum by (namespace, job)(rate(http_server_requests_seconds_sum{namespace="sco",uri="/customer/loan/quote"}[5m]))/ sum by (namespace, job)(rate(http_server_requests_seconds_count{namespace="sco",uri="/customer/loan/quote"}[5m]))
        - alert: SCO_FL_app2_response_time_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app2_response_time_{{ AWS_ENVIRONMENT }}) > 1.515 and (sco_fl_app2_response_time_{{ AWS_ENVIRONMENT }}) <= 2.02
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 1515ms for last 5 mins. Value: {{ $value }}'
            summary: Yellow alert for response time reached for Application {{ $labels.job }}
        - alert: SCO_FL_app2_response_time_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (sco_fl_app2_response_time_{{ AWS_ENVIRONMENT }}) > 2.02
          for: 5m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} response time is more than 2020ms for last 5 mins. Value: {{ $value }}'
            summary: Red alert for response time reached for Application {{ $labels.job }}