apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: cop2-inbound-app-state-alerts
  namespace: prometheus
spec:
  groups:
    - name: COP2_INBOUND_FLOW_APPS_STATE
      rules:
    ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 408 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status408_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="408",uri=~".*account-verification.*"}[1m])*60)
        - alert: COP2_inbound_v1_status408_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status408_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 408 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 400 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status400_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="400",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status400_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status400_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 400 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 401 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status401_count20{{ AWS_ENVIRONMENT }}
          expr:  (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="401",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status401_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status401_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 401 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 403 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status403_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="403",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status403_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status403_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 403 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 404 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status404_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="404",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status404_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status404_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 404 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 405 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status405_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="405",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status405_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status405_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 405 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP_INBOUND_RESTPROXY - more than 20 requests failure of 406 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status406_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="406",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status406_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status406_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 406 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 429 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status429_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="429",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status429_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status429_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 429 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 500 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status500_{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="500",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status500_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status500_{{ AWS_ENVIRONMENT }}) >20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 500 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Yellow rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      ##################COP2_INBOUND_RESTPROXY - more than 20 requests failure of 503 status per minutes for last 5 minutes? ##########################################################
        - record: cop2_inbound_v1_status503_count20{{ AWS_ENVIRONMENT }}
          expr: (sum by (job, namespace, uri) (rate(http_server_requests_seconds_count {namespace="cop-phase2",status="503",uri=~".*account-verification.*"}[1m])*60))
        - alert: COP2_inbound_v1_status503_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (cop2_inbound_v1_status503_count20{{ AWS_ENVIRONMENT }}) > 20
          for: 5m
          labels:
            action: Closely monitor
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: cop-phase2
            severity: CRITICAL
            priority: P2
            type: 8x5
            tsbci: COP2_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.uri}} has reached failure peak rate with http_status of 503 more than 20 times in 5 min. Value: {{ $value }}'
            summary: Red rate reached for Application {{ $labels.job }} Endpoint {{$labels.uri}}

      
