apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: rax-endpoint-monitoring
  namespace: prometheus
spec:
  groups:
  - name: BLACKBOX_ENDPOINT_MONITORING_RULES
    rules:
    - alert: probe_http_2xx_status_code
      expr: (probe_http_status_code{job="blackbox"}) != 200
      for: 1m
      labels:
        severity: CRITICAL
        environment: "{{ AWS_ENVIRONMENT }}"
        monitoring: endpoints
        rackspace: "true"
      annotations:
        summary: "Endpoint {{ $labels.instance }} unhealthy"
    - alert: probe_http_4xx_status_code
      expr: (probe_http_status_code{job="blackbox_4xx"}) != 403
      for: 1m
      labels:
        severity: CRITICAL
        environment: "{{ AWS_ENVIRONMENT }}"
        monitoring: endpoints
        rackspace: "true"
      annotations:
        summary: "Endpoint {{ $labels.instance }} unhealthy"
