apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: sco-fl-restproxy-api-stage2-failure-rate-alerts
  namespace: prometheus
spec:
  groups:
    - name: sco_fl_restproxy_api_stage2-failure_rate
      rules:
  ###########################################Failure Rate for Completion-Start API##########################################################                 
        - record: completion_start_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/completion/start"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/completion/start"}[5m]))) * 100

        - alert: completion_start_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((completion_start_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((completion_start_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: completion_start_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((completion_start_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((completion_start_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: completion_start_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (completion_start_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Completion-Report API##########################################################                 
        - record: completion_report_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/completion/report"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/completion/report"}[5m]))) * 100

        - alert: completion_report_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((completion_report_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((completion_report_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: completion_report_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((completion_report_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((completion_report_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: completion_report_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (completion_report_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Get-Confirm-PCCI API##########################################################                 
        - record: get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/pcci"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/pcci"}[5m]))) * 100
        
        - alert: get_confirm_pcci_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: get_confirm_pcci_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: get_confirm_pcci_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (get_confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Confirm-PCCI API##########################################################                 
        - record: confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/{applycode}/pcci"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/{applycode}/pcci"}[5m]))) * 100
        
        - alert: confirm_pcci_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: confirm_pcci_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: confirm_pcci_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (confirm_pcci_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
  ###########################################Failure Rate for Calculator-GetQuote API##########################################################                 
        - record: calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/quote"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/quote"}[5m]))) * 100
        
        - alert: calculator_getquote_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: calculator_getquote_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: calculator_getquote_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (calculator_getquote_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}
###########################################Failure Rate for Refinance API##########################################################                 
        - record: refinance_failure_rate{{ AWS_ENVIRONMENT }}
          expr: (sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco",outcome!="SUCCESS", uri=~".*/sco-fl/customer/loan/refinance"}[5m])) / sum by (namespace, job, uri) (rate(http_server_requests_seconds_count {namespace="sco", uri=~".*/sco-fl/customer/loan/refinance"}[5m]))) * 100
        
        - alert: refinance_failure_rate_yellow_alert_{{ AWS_ENVIRONMENT }}
          expr: ((refinance_failure_rate{{ AWS_ENVIRONMENT }}) > 1) and ((refinance_failure_rate{{ AWS_ENVIRONMENT }}) < 10) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: YELLOW
            platform: AWS
            namespace: sco
            severity: WARNING
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached failure requst in 1 min. Value: {{ $value }}'
            summary: YELLOW alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: refinance_failure_rate_amber_alert_{{ AWS_ENVIRONMENT }}
          expr: ((refinance_failure_rate{{ AWS_ENVIRONMENT }}) > 10) and ((refinance_failure_rate{{ AWS_ENVIRONMENT }}) < 50) # Value is in percentage (%) 
          for: 1m
          labels:
            action: Application is likely impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: AMBER
            platform: AWS
            namespace: sco
            severity: MAJOR
            priority: P4
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 10 % failure requst in 1 min. Value: {{ $value }}'
            summary: AMBER alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}

        - alert: refinance_failure_rate_red_alert_{{ AWS_ENVIRONMENT }}
          expr: (refinance_failure_rate{{ AWS_ENVIRONMENT }}) > 50
          for: 1m
          labels:
            action: Application will be impacted
            environment: "{{ AWS_ENVIRONMENT }}"
            group: INFRA
            level: RED
            platform: AWS
            namespace: sco
            severity: CRITICAL
            priority: P3
            type: 8x5
            tsbci: SCO_FL_AWS
            itopsbridge: "true"
          annotations:
            description: 'Application {{ $labels.job }} Endpoint {{$labels.routeId}} has reached more than 50 % failure requst in 1 min. Value: {{ $value }}'
            summary: RED alert reached for Application {{ $labels.job }} Endpoint {{$labels.routeId}}