---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: prometheus
  labels:
    prometheus: "data"
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ EFS_ID }}::{{ EFS_PROMETHEUS_ID }}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-volume
  namespace: prometheus
  labels:
    thanos: "data"
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ EFS_ID }}::{{ EFS_THANOS_ID }}"