---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fr-admin-role
  namespace: forgerock
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fr-admin-binding
  namespace: forgerock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fr-admin-role
subjects:
  - kind: ServiceAccount
    name: tsb-fr
  - kind: Group
    name: fr-admin
  - kind: ServiceAccount
    name: jenkins-terraform
    namespace: jenkins