---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-fr
  namespace: forgerock
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/tsb-ob-{{ AWS_ENVIRONMENT }}-role
  labels:
    role: jenkins-agent
    component: forgerock