---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-ods
  namespace: ods
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-ods
  labels:
    role: jenkins-agent
    component: ods
