---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-sco
  namespace: sco
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-sco
  labels:
    role: jenkins-agent
    component: sco
