---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ods-view-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ods-view-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ods-view-role
subjects:
- kind: Group
  name: ods-view-kube-system
- kind: ServiceAccount
  name: tsb-ods
  namespace: ods
