---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-ods-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-ods
    namespace: ods
  - kind: ServiceAccount
    name: tsb-ods
    namespace: ods
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-ods
  namespace: ods
