---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ods-admin-role
  namespace: ods
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ods-admin-binding
  namespace: ods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ods-admin-role
subjects:
- kind: ServiceAccount
  name: tsb-ods
- kind: Group
  name: ods-admin
- kind: ServiceAccount
  name: jenkins-terraform
  namespace: jenkins
