---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tigera-operator
  namespace: kube-system
spec:
  releaseName: tigera-operator
  chart:
    repository: https://docs.projectcalico.org/charts
    name: tigera-operator
    version: v3.21.4
  values:
    apiServer:
      enabled: true
    calicoctl:
      image: docker.io/calico/ctl
      tag: v3.21.4
    certs:
      node:
        cert: null
        commonName: null
        key: null
      typha:
        caBundle: null
        cert: null
        commonName: null
        key: null
    imagePullSecrets: {}
    installation:
      enabled: true
      kubernetesProvider: EKS
    tigeraOperator:
      image: tigera/operator
      registry: quay.io
      version: v1.23.5
