---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-datalake
  namespace: datalake
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-datalake
  labels:
    role: jenkins-agent
    component: datalake
