---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-cop
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-cop
  labels:
    role: jenkins-agent
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cop-sink-connector
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/cop-sink-connector
  labels:
    component: cop