---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tsb-cop
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/tsb-cop
  labels:
    role: jenkins-agent
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cop-sink-connector
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/cop-sink-connector
  labels:
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-tsb-onboarding-identity-onfido-download-asset
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/sa-tsb-onboarding-identity-onfido-download-asset
  labels:
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-tsb-onboarding-product-data-upload 
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/sa-tsb-onboarding-product-data-upload
  labels:
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-tsb-onboarding-email-sender
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/sa-tsb-onboarding-email-sender
  labels:
    component: cop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-tsb-onboarding-otp-sender
  namespace: cop
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ AWS_ACCOUNT }}:role/eks/sa-tsb-onboarding-otp-sender
  labels:
    component: cop