apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/oneagent-privileged: "true"
spec:
  apiUrl: https://rxl69895.live.dynatrace.com/api
  networkZone: uk.fhnh.aws
  proxy:
    value: http://eu-west-2.proxy.aws.uk.tsb:3128
  oneAgent:
    classicFullStack:
      image:
      args:
        - --set-host-group=AWSS-EKSS-NOLAYER-NOLINE-DEV
      
      env:
      - name: https_proxy
        value: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: http_proxy
        value: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    image: ""
    env:
      - name: https_proxy
        value: "http://eu-west-2.proxy.aws.uk.tsb:3128"
      - name: http_proxy
        value: "http://eu-west-2.proxy.aws.uk.tsb:3128"
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi