apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/oneagent-privileged: "true"
spec:
  apiUrl: https://{{ DYNATRACE_ENV_ID }}.live.dynatrace.com/api
  proxy:
    value: http://eu-west-2.proxy.aws.uk.tsb:3128
  networkZone: uk.fhnh.aws
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    image: ""
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  oneAgent:
    classicFullStack:
      enabled: true
      env:
      - name: https_proxy
      value: http://eu-west-2.proxy.aws.uk.tsb:3128
      image: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
        - key: role
          operator: Equal
          value: mgmt
          effect: NoSchedule
        - key: role
          operator: Equal
          value: sco
          effect: NoSchedule
        - key: role
          operator: Equal
          value: ods
          effect: NoSchedule
        - key: role
          operator: Equal
          value: cop
          effect: NoSchedule
        - key: role
          operator: Equal
          value: highcompute
          effect: NoSchedule
        - key: role
          operator: Equal
          value: sca
          effect: NoSchedule
        - key: role
          operator: Equal
          value: obs
          effect: NoSchedule
        - key: role
          operator: Equal
          value: scofl
          effect: NoSchedule
      args:
        - --set-host-group={{ DYNATRACE_HOST_GROUP }}  

