apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  releaseName: dynatrace-operator
  chart:
    repository: https://charts.fluxcd.io
    name: dynatrace-operator
    version: 0.3.0
  values:
    platform: "kubernetes"
    name: "dynakube"
    apiUrl: "https://{{ DYNATRACE_ENV_ID }}.live.dynatrace.com/api"
    customPullSecret: ""
    skipCertCheck: false
    proxy: "http://eu-west-2.proxy.aws.uk.tsb:3128"
    trustedCAs: ""
    networkZone: "uk.fhnh.aws"
    enableIstio: false
    namespaceSelector: {}
    autoCreateSecret: true
    apiToken: "ZHQwYzAxLjNEQVQ0NEpPVURHMkpFVFZNQlJJVlFMUC5ENzZKREhKV1ozWTJaRVhXQUUyN0NQSEtMM0RPU1JVWTZYNUpORFROUUZUUkFGWUMzUUhWNEU0RU1BNUpBTkFZCg"
    paasToken: "ZHQwYzAxLjNEQVQ0NEpPVURHMkpFVFZNQlJJVlFMUC5ENzZKREhKV1ozWTJaRVhXQUUyN0NQSEtMM0RPU1JVWTZYNUpORFROUUZUUkFGWUMzUUhWNEU0RU1BNUpBTkFZCg" 

    operator:
      image: ""
      customPullSecret: ""
      nodeSelector: {}
      tolerations: []
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    webhook:
      requests:
        cpu: 300m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 128Mi
    createSecurityContextConstraints: true # Only applicable for Openshift
    installCRD: true

    classicFullStack:
      enabled: true
      image: ""
      version: ""
      nodeSelector: {}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mgmt
        - effect: NoSchedule
          key: role
          operator: Equal
          value: sco
        - effect: NoSchedule
          key: role
          operator: Equal
          value: ods
        - effect: NoSchedule
          key: role
          operator: Equal
          value: cop
        - effect: NoSchedule
          key: role
          operator: Equal
          value: highcompute
        - effect: NoSchedule
          key: role
          operator: Equal
          value: sca
        - effect: NoSchedule
          key: role
          operator: Equal
          value: obs
        - effect: NoSchedule
          key: role
          operator: Equal
          value: scofl
      oneAgentResources: {}
      args: []
      env:
      - name: https_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: http_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      autoUpdate: true
      priorityClassName: ""
      dnsPolicy: ""
      labels: {}
    
    activeGate:
      capabilities:
      - routing
      - kubernetes-monitoring
      image: ""
      replicas: 1
      group: ""
      customProperties:
        value: ""
        valueFrom: ""
      resources: {}
      nodeSelector: {}
      tolerations: []
      labels: {}
      env:
      - name: https_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      - name: http_proxy
        value: http://eu-west-2.proxy.aws.uk.tsb:3128
      tlsSecretName: "" 