---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
  namespace: dynatrace
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-egress
  namespace: dynatrace
spec:
  podSelector: {}
  egress:
  - {}
  policyTypes:
  - Egress
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: dynatrace
  namespace: dynatrace
spec:
  types:
    - Ingress
    - Egress
  egress:    
    - action: Allow
      destination:
        nets:
          - "{{ VPC_CIDR }}"
  ingress:    
    - action: Allow
      source:
        nets:
          - "{{ VPC_CIDR }}"